//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOT_SAVE_ARBO_RESA8_H36
    {
        public long H36_ID { get; set; }
        public Nullable<long> H36_ID_RESERVATION_H01 { get; set; }
        public Nullable<int> H36_ID_TYPE8_H13 { get; set; }
    }
}
