//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOT_PLANNING_CALENDRIER_H32
    {
        public int H32_ID { get; set; }
        public string H32_NOM { get; set; }
        public string H32_CHAMP_COLONNE { get; set; }
        public string H32_ALIAS_CHAMP_COLONNE { get; set; }
        public Nullable<int> H32_VISIBLE { get; set; }
        public Nullable<int> H32_ALIGNEMENT_COLONNE { get; set; }
        public Nullable<int> H32_TAILLE { get; set; }
        public Nullable<int> H32_USES { get; set; }
        public Nullable<int> H32_USE_IN_SQL { get; set; }
        public Nullable<int> H32_FORCED_USES { get; set; }
        public Nullable<int> H32_NO_MODIFY_USES { get; set; }
        public Nullable<int> H32_ORDRE_CHAMP { get; set; }
        public Nullable<int> H32_ORDRE_CHAMP_INIT { get; set; }
        public Nullable<int> H32_ORDRE_REFERENCE { get; set; }
        public Nullable<int> H32_MODE { get; set; }
        public Nullable<int> H32_USER_C18 { get; set; }
    }
}
