//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOT_TYPE_INDISPONIBILITE_H47
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOT_TYPE_INDISPONIBILITE_H47()
        {
            this.HOT_INDISPONIBILITES_CHAMBRES_H46 = new HashSet<HOT_INDISPONIBILITES_CHAMBRES_H46>();
        }
    
        public long H47_ID { get; set; }
        public string H47_LIBELLE { get; set; }
        public Nullable<short> H47_ORDRE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOT_INDISPONIBILITES_CHAMBRES_H46> HOT_INDISPONIBILITES_CHAMBRES_H46 { get; set; }
    }
}
