//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOT_PLANNING_OCCUPATION_H33
    {
        public int H33_ID { get; set; }
        public Nullable<short> H33_ORDRE { get; set; }
        public string H33_NOM_CONFIG { get; set; }
        public Nullable<int> H33_LARGEUR { get; set; }
        public Nullable<int> H33_HAUTEUR { get; set; }
        public Nullable<int> H33_LARGEUR_FIXE { get; set; }
        public Nullable<int> H33_HAUTEUR_FIXE { get; set; }
        public string H33_CONTENU { get; set; }
        public string H33_CELL_CONTENT { get; set; }
        public Nullable<int> H33_NUM_TRANCHE_C29 { get; set; }
        public Nullable<short> H33_MODE { get; set; }
        public Nullable<short> H33_BORDURE { get; set; }
        public Nullable<short> H33_DIVISE_CELL { get; set; }
        public Nullable<int> H33_USER_C18 { get; set; }
        public Nullable<int> H33_FUSION_FORMAT { get; set; }
        public Nullable<short> H33_IMGPLA { get; set; }
    }
}
