//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOT_RESA_CTC_PART_H31
    {
        public int H31_ID { get; set; }
        public Nullable<long> H31_ID_SS_RESA_H02 { get; set; }
        public Nullable<long> H31_ID_CONTACT_G03 { get; set; }
        public Nullable<long> H31_ID_PART_A09 { get; set; }
    }
}
