//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOT_CHAMBRE_H03
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOT_CHAMBRE_H03()
        {
            this.HOT_CARDEX_CHAMBRE_H48 = new HashSet<HOT_CARDEX_CHAMBRE_H48>();
            this.HOT_PRODUITS_CHAMBRE_H41 = new HashSet<HOT_PRODUITS_CHAMBRE_H41>();
            this.HOT_INDISPONIBILITES_CHAMBRES_H46 = new HashSet<HOT_INDISPONIBILITES_CHAMBRES_H46>();
            this.HOT_CHAMBRE_H031 = new HashSet<HOT_CHAMBRE_H03>();
            this.HOT_SOUS_RESERVATION_H02 = new HashSet<HOT_SOUS_RESERVATION_H02>();
        }
    
        public long H03_ID { get; set; }
        public Nullable<long> H03_ID_MERE_H03 { get; set; }
        public Nullable<int> H03_ID_ETAGE_H04 { get; set; }
        public Nullable<short> H03_CLIM { get; set; }
        public Nullable<short> H03_TELE { get; set; }
        public Nullable<int> H03_ID_SANITAIRE_H30 { get; set; }
        public Nullable<short> H03_TOILETTE { get; set; }
        public Nullable<short> H03_INTERNET { get; set; }
        public Nullable<short> H03_MINIBAR { get; set; }
        public Nullable<int> H03_TYPE_CHAMBRE1_H22 { get; set; }
        public Nullable<int> H03_TYPE_CHAMBRE2_H23 { get; set; }
        public Nullable<int> H03_TYPE_CHAMBRE3_H24 { get; set; }
        public Nullable<int> H03_TYPE_CHAMBRE4_H25 { get; set; }
        public Nullable<int> H03_TYPE_CHAMBRE5_H26 { get; set; }
        public Nullable<int> H03_TYPE_CHAMBRE6_H27 { get; set; }
        public Nullable<int> H03_TYPE_ARBO_CHAMBRE7_H28 { get; set; }
        public Nullable<int> H03_TYPE_ARBO_CHAMBRE8_H29 { get; set; }
        public string H03_LIBRE1 { get; set; }
        public string H03_LIBRE2 { get; set; }
        public string H03_LIBRE3 { get; set; }
        public string H03_LIBRE4 { get; set; }
        public string H03_LIBRE5 { get; set; }
        public string H03_LIBRE6 { get; set; }
        public string H03_LIBRE7 { get; set; }
        public string H03_LIBRE8 { get; set; }
        public string H03_NOTE { get; set; }
        public Nullable<long> H03_NUMERO_CLEF { get; set; }
        public string H03_NOM { get; set; }
        public string H03_DESC { get; set; }
        public Nullable<int> H03_SUPERFICIE { get; set; }
        public Nullable<int> H03_LIT_SIMPLE { get; set; }
        public Nullable<int> H03_LIT_DOUBLE { get; set; }
        public Nullable<int> H03_COUCHAGE_SUPP { get; set; }
        public Nullable<int> H03_NIVEAU { get; set; }
        public Nullable<int> H03_ORDRE { get; set; }
        public Nullable<int> H03_ID_SOC_C13 { get; set; }
        public Nullable<int> H03_QTE { get; set; }
        public Nullable<short> H03_FLAG_HOTEL { get; set; }
        public Nullable<short> H03_ISDIRTY { get; set; }
        public Nullable<short> H03_HORSSERVICE { get; set; }
        public Nullable<short> H03_INLOUABLE { get; set; }
        public Nullable<short> H03_MENAGE { get; set; }
        public string H03_REF { get; set; }
        public Nullable<int> H03_HOTEL_H44 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOT_CARDEX_CHAMBRE_H48> HOT_CARDEX_CHAMBRE_H48 { get; set; }
        public virtual HOT_TYPE_CHAMBRE2_H23 HOT_TYPE_CHAMBRE2_H23 { get; set; }
        public virtual HOT_TYPE_CHAMBRE1_H22 HOT_TYPE_CHAMBRE1_H22 { get; set; }
        public virtual HOT_TYPE_CHAMBRE3_H24 HOT_TYPE_CHAMBRE3_H24 { get; set; }
        public virtual HOT_TYPE_CHAMBRE4_H25 HOT_TYPE_CHAMBRE4_H25 { get; set; }
        public virtual HOT_TYPE_CHAMBRE5_H26 HOT_TYPE_CHAMBRE5_H26 { get; set; }
        public virtual HOT_TYPE_CHAMBRE6_H27 HOT_TYPE_CHAMBRE6_H27 { get; set; }
        public virtual HOT_TYPE_ARBO_CHAMBRE7_H28 HOT_TYPE_ARBO_CHAMBRE7_H28 { get; set; }
        public virtual HOT_TYPE_ARBO_CHAMBRE8_H29 HOT_TYPE_ARBO_CHAMBRE8_H29 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOT_PRODUITS_CHAMBRE_H41> HOT_PRODUITS_CHAMBRE_H41 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOT_INDISPONIBILITES_CHAMBRES_H46> HOT_INDISPONIBILITES_CHAMBRES_H46 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOT_CHAMBRE_H03> HOT_CHAMBRE_H031 { get; set; }
        public virtual HOT_CHAMBRE_H03 HOT_CHAMBRE_H032 { get; set; }
        public virtual HOT_ETAGE_H04 HOT_ETAGE_H04 { get; set; }
        public virtual HOT_SANITAIRE_H30 HOT_SANITAIRE_H30 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOT_SOUS_RESERVATION_H02> HOT_SOUS_RESERVATION_H02 { get; set; }
    }
}
