//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOT_CHAMBRE_PAR_TYPE_H45
    {
        public int H45_ID { get; set; }
        public long H45_ID_HOT_H44 { get; set; }
        public int H45_ID_TYPE_H22 { get; set; }
        public Nullable<int> H45_ID_TVA_F17 { get; set; }
        public Nullable<int> H45_ID_PRODUIT_F13 { get; set; }
        public Nullable<int> H45_QTE { get; set; }
        public Nullable<decimal> H45_PRIX_CH { get; set; }
        public Nullable<decimal> H45_PRIX_CH_TTC { get; set; }
        public string H45_LIBELLE { get; set; }
        public string H45_DESC { get; set; }
        public string H45_LIBELLE_EN { get; set; }
        public string H45_LIBELLE_AL { get; set; }
        public string H45_LIBELLE_ES { get; set; }
        public string H45_LIBELLE_IT { get; set; }
    }
}
