//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOT_SOUS_RESERVATION_H02
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOT_SOUS_RESERVATION_H02()
        {
            this.HOT_SOUS_RESERVATION_H021 = new HashSet<HOT_SOUS_RESERVATION_H02>();
        }
    
        public long H02_ID { get; set; }
        public Nullable<long> H02_ID_RESERVATION_H01 { get; set; }
        public Nullable<long> H02_ID_CONTACT_G03 { get; set; }
        public Nullable<long> H02_ID_PERE_H02 { get; set; }
        public Nullable<long> H02_ID_CHAMBRE_H03 { get; set; }
        public Nullable<System.DateTime> H02_DATE_DEBUT { get; set; }
        public Nullable<System.DateTime> H02_DATE_FIN { get; set; }
        public Nullable<System.DateTime> H02_HEURE_DEBUT { get; set; }
        public Nullable<System.DateTime> H02_HEURE_FIN { get; set; }
        public Nullable<int> H02_QTE { get; set; }
        public Nullable<short> H02_DEJEUNER { get; set; }
        public Nullable<short> H02_MENAGE_FAIT { get; set; }
        public Nullable<int> H02_ID_RESTAURATION_H05 { get; set; }
        public Nullable<int> H02_QTE_LITS_SUPP { get; set; }
        public Nullable<short> H02_DEMANDE_MENAGE { get; set; }
        public Nullable<short> H02_CLEF_RENDUE { get; set; }
        public Nullable<int> H02_TYPE_SS_RESA1_H14 { get; set; }
        public Nullable<int> H02_TYPE_SS_RESA2_H15 { get; set; }
        public Nullable<int> H02_TYPE_SS_RESA3_H16 { get; set; }
        public Nullable<int> H02_TYPE_SS_RESA4_H17 { get; set; }
        public Nullable<int> H02_TYPE_SS_RESA5_H18 { get; set; }
        public Nullable<int> H02_TYPE_SS_RESA6_H19 { get; set; }
        public Nullable<int> H02_TYPE_ARBO_SS_RESA7_H20 { get; set; }
        public Nullable<int> H02_TYPE_ARBO_SS_RESA8_H21 { get; set; }
        public string H02_LIBRE1 { get; set; }
        public string H02_LIBRE2 { get; set; }
        public string H02_LIBRE3 { get; set; }
        public string H02_LIBRE4 { get; set; }
        public string H02_LIBRE5 { get; set; }
        public string H02_LIBRE6 { get; set; }
        public string H02_LIBRE7 { get; set; }
        public string H02_LIBRE8 { get; set; }
        public string H02_NOTE { get; set; }
        public Nullable<int> H02_ETAT_H42 { get; set; }
        public Nullable<int> H02_COULEUR { get; set; }
        public Nullable<int> H02_POSITION { get; set; }
        public Nullable<int> H02_ID_USER_C18 { get; set; }
        public Nullable<int> H02_ID_SOC_C13 { get; set; }
        public Nullable<System.DateTime> H02_DATE_ANNULATION { get; set; }
        public Nullable<System.DateTime> H02_DATE_CONFIRMATION { get; set; }
        public Nullable<System.DateTime> H02_DATE_POSE_OPTION { get; set; }
        public Nullable<short> H02_NB_ADULTES { get; set; }
        public Nullable<short> H02_NB_ENFANTS { get; set; }
        public Nullable<System.DateTime> H02_DATE_ECHEANCE { get; set; }
        public Nullable<long> H02_REFERENCE { get; set; }
        public Nullable<short> H02_CHECKIN { get; set; }
        public Nullable<short> H02_CHECKOUT { get; set; }
        public Nullable<int> H02_ID_PARTICIPANT_A09 { get; set; }
        public Nullable<short> H02_PETITDEJ { get; set; }
        public Nullable<short> H02_DINER { get; set; }
        public string H02_CB { get; set; }
        public string H02_REF_BADGE { get; set; }
        public Nullable<long> H02_ID_ORGANISME_G09 { get; set; }
        public Nullable<System.DateTime> H02_DATE_REVEIL { get; set; }
        public string H02_CB_TYPE { get; set; }
        public string H02_CB_CRIPT { get; set; }
        public string H02_CB_EXP { get; set; }
        public string H02_LGWIFI { get; set; }
        public string H02_PWDWIFI { get; set; }
        public Nullable<int> H02_ID_MOTIF_ANNULE_M15 { get; set; }
    
        public virtual GRC_CONTACTS_G03 GRC_CONTACTS_G03 { get; set; }
        public virtual HOT_CHAMBRE_H03 HOT_CHAMBRE_H03 { get; set; }
        public virtual HOT_RESERVATION_H01 HOT_RESERVATION_H01 { get; set; }
        public virtual HOT_RESTAURATION_H05 HOT_RESTAURATION_H05 { get; set; }
        public virtual HOT_TYPE_SS_RESA1_H14 HOT_TYPE_SS_RESA1_H14 { get; set; }
        public virtual HOT_TYPE_SS_RESA2_H15 HOT_TYPE_SS_RESA2_H15 { get; set; }
        public virtual HOT_TYPE_SS_RESA3_H16 HOT_TYPE_SS_RESA3_H16 { get; set; }
        public virtual HOT_TYPE_SS_RESA4_H17 HOT_TYPE_SS_RESA4_H17 { get; set; }
        public virtual HOT_TYPE_SS_RESA5_H18 HOT_TYPE_SS_RESA5_H18 { get; set; }
        public virtual HOT_TYPE_SS_RESA6_H19 HOT_TYPE_SS_RESA6_H19 { get; set; }
        public virtual HOT_TYPE_ARBO_SS_RESA7_H20 HOT_TYPE_ARBO_SS_RESA7_H20 { get; set; }
        public virtual HOT_TYPE_ARBO_SS_RESA8_H21 HOT_TYPE_ARBO_SS_RESA8_H21 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOT_SOUS_RESERVATION_H02> HOT_SOUS_RESERVATION_H021 { get; set; }
        public virtual HOT_SOUS_RESERVATION_H02 HOT_SOUS_RESERVATION_H022 { get; set; }
    }
}
