//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOT_TYPE_ARBO_RESA7_H12
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOT_TYPE_ARBO_RESA7_H12()
        {
            this.HOT_RESERVATION_H01 = new HashSet<HOT_RESERVATION_H01>();
        }
    
        public int H12_ID { get; set; }
        public string H12_LIBELLE { get; set; }
        public Nullable<int> H12_ORDRE { get; set; }
        public Nullable<int> H12_ID_PERE_H12 { get; set; }
        public Nullable<int> H12_NIVEAU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOT_RESERVATION_H01> HOT_RESERVATION_H01 { get; set; }
    }
}
