//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOT_MENAGE_H43
    {
        public int H43_ID { get; set; }
        public Nullable<long> H43_ID_SOUS_RESA_H02 { get; set; }
        public int H43_ID_CHAMBRE_H03 { get; set; }
        public Nullable<int> H43_ID_USER_C18 { get; set; }
        public Nullable<System.DateTime> H43_DATE_MENAGE_PREVU { get; set; }
        public Nullable<System.DateTime> H43_DATE_MENAGE_FAIT { get; set; }
        public Nullable<short> H43_FAIT { get; set; }
        public Nullable<short> H43_ABLANC { get; set; }
    }
}
