//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOT_SAVE_ARBO_CHAMBRE7_H39
    {
        public long H39_ID { get; set; }
        public Nullable<int> H39_ID_CHAMBRE_H03 { get; set; }
        public Nullable<int> H39_ID_TYPE7_H28 { get; set; }
    }
}
