//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REC_PASSAGE_R04
    {
        public int R04_ID { get; set; }
        public Nullable<long> R04_ID_LIEUX_M07 { get; set; }
        public Nullable<int> R04_ID_TYPE_PASSAGE_R05 { get; set; }
        public Nullable<int> R04_ID_CTC_G03 { get; set; }
        public Nullable<int> R04_ID_MANIF_M14 { get; set; }
        public Nullable<int> R04_REF_LIEUX { get; set; }
        public string R04_NUM_CARTE { get; set; }
        public string R04_TYPE_PASSAGE { get; set; }
        public Nullable<int> R04_NOMBRE_POINT { get; set; }
        public Nullable<double> R04_CA { get; set; }
        public Nullable<int> R04_QT { get; set; }
        public Nullable<System.DateTime> R04_DATE_PASSAGE { get; set; }
        public Nullable<System.DateTime> R04_DATE_ENREGISTREMENT { get; set; }
        public Nullable<int> R04_REMISE { get; set; }
        public string R04_SITE { get; set; }
        public string R04_NUMCAISSE { get; set; }
        public string R04_NUMTICKET { get; set; }
    }
}
