//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REC_DEMANDE_CADEAU_R03
    {
        public int R03_ID { get; set; }
        public Nullable<int> R03_ID_CADEAU_R01 { get; set; }
        public Nullable<int> R03_ID_CONTACT_G03 { get; set; }
        public Nullable<short> R03_STATUT { get; set; }
        public Nullable<System.DateTime> R03_DATE_DEMANDE { get; set; }
        public Nullable<System.DateTime> R03_DATE_STATUT { get; set; }
        public Nullable<int> R03_NOMBRE_POINT { get; set; }
    }
}
