//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REC_TYPE_PASSAGE_R05
    {
        public int R05_ID { get; set; }
        public string R05_LIBELLE { get; set; }
        public Nullable<int> R05_NOMBRE_POINT { get; set; }
    }
}
