//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEB_EXTERNAL_MAPPINGS_W02
    {
        public long W02_ID { get; set; }
        public string W02_NOM_COURT { get; set; }
        public Nullable<long> W02_ID_AGORAEVENT { get; set; }
        public Nullable<int> W02_ID_ADMIN_A48 { get; set; }
        public Nullable<long> W02_EXTERNAL_ID { get; set; }
        public Nullable<System.DateTime> W02_DATE_CREATION { get; set; }
        public Nullable<System.DateTime> W02_LAST_UPDATE { get; set; }
    
        public virtual ADH_EPARTICIPANT_ADMIN_A48 ADH_EPARTICIPANT_ADMIN_A48 { get; set; }
    }
}
