//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAN_TYPE_MAN3_M29
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAN_TYPE_MAN3_M29()
        {
            this.MAN_MANIFESTATIONS_M14 = new HashSet<MAN_MANIFESTATIONS_M14>();
        }
    
        public int M29_ID { get; set; }
        public string M29_LIBELLE { get; set; }
        public Nullable<int> M29_ORDRE { get; set; }
        public Nullable<short> M29_INACTIF { get; set; }
        public Nullable<int> M29_ID_SOC_C13 { get; set; }
        public Nullable<int> M29_ID_TYPE_MAN2_M28 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAN_MANIFESTATIONS_M14> MAN_MANIFESTATIONS_M14 { get; set; }
    }
}
