//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAN_PRESTATIONS_M16
    {
        public int M16_ID { get; set; }
        public Nullable<int> M16_PRESTATION_M17 { get; set; }
        public Nullable<long> M16_ID_MANIFESTATION_M14 { get; set; }
        public Nullable<long> M16_ID_CONTACT_G03 { get; set; }
        public Nullable<System.DateTime> M16_HEURE_DEBUT { get; set; }
        public Nullable<System.DateTime> M16_HEURE_FIN { get; set; }
        public Nullable<System.DateTime> M16_DUREE_MONTAGE { get; set; }
        public Nullable<System.DateTime> M16_DUREE_DEMONTAGE { get; set; }
        public string M16_NOTE { get; set; }
        public Nullable<int> M16_PRESTATION { get; set; }
        public Nullable<int> M16_INTERFACAGE { get; set; }
        public Nullable<int> M16_QTE1 { get; set; }
        public Nullable<int> M16_QTE2 { get; set; }
        public Nullable<int> M16_QTE3 { get; set; }
        public Nullable<int> M16_QTE4 { get; set; }
        public Nullable<int> M16_QTE5 { get; set; }
        public Nullable<int> M16_REPONSE { get; set; }
        public Nullable<int> M16_RETENUE { get; set; }
        public Nullable<int> M16_PRESTATION_ANNULEE { get; set; }
        public Nullable<int> M16_INTERFACE_ANNULEE { get; set; }
        public Nullable<int> M16_CA { get; set; }
        public Nullable<long> M16_ID_ORGANISMES_G09 { get; set; }
    
        public virtual GRC_CONTACTS_G03 GRC_CONTACTS_G03 { get; set; }
        public virtual MAN_MANIFESTATIONS_M14 MAN_MANIFESTATIONS_M14 { get; set; }
        public virtual MAN_TYPE_PRES_M17 MAN_TYPE_PRES_M17 { get; set; }
    }
}
