//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAN_LIEUX_M07
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAN_LIEUX_M07()
        {
            this.ADH_MESSAGE_A62 = new HashSet<ADH_MESSAGE_A62>();
            this.ADH_PANIER_A61 = new HashSet<ADH_PANIER_A61>();
            this.ADH_PRESTATION_A10 = new HashSet<ADH_PRESTATION_A10>();
            this.FIN_DETAILS_COMMANDES_F07 = new HashSet<FIN_DETAILS_COMMANDES_F07>();
            this.FIN_OCCUPATION_LIEUX_F62 = new HashSet<FIN_OCCUPATION_LIEUX_F62>();
            this.FIN_PRODUIT_LIEUX_F36 = new HashSet<FIN_PRODUIT_LIEUX_F36>();
            this.MAN_LIEUX_CONFIGURATION_M08 = new HashSet<MAN_LIEUX_CONFIGURATION_M08>();
            this.MAN_LIEUX_M071 = new HashSet<MAN_LIEUX_M07>();
            this.MAN_LIEUX_MANIF_M10 = new HashSet<MAN_LIEUX_MANIF_M10>();
            this.MAN_LIEUX_ORG_DROIT_M54 = new HashSet<MAN_LIEUX_ORG_DROIT_M54>();
            this.MAN_LIEUX_USER_DROIT_M61 = new HashSet<MAN_LIEUX_USER_DROIT_M61>();
            this.MAN_LISTE_IMAGES_LIEUX_M64 = new HashSet<MAN_LISTE_IMAGES_LIEUX_M64>();
            this.REC_CARTE_R02 = new HashSet<REC_CARTE_R02>();
            this.TBL_PLAN_SALLE_T03 = new HashSet<TBL_PLAN_SALLE_T03>();
            this.TBL_RESERVATION_T04 = new HashSet<TBL_RESERVATION_T04>();
        }
    
        public int M07_ID { get; set; }
        public string M07_LIBELLE { get; set; }
        public Nullable<int> M07_ID_SOC_C13 { get; set; }
        public Nullable<long> M07_ID_ORGANISME_G09 { get; set; }
        public string M07_DESC { get; set; }
        public Nullable<int> M07_ID_CONFIGURATION_M01 { get; set; }
        public Nullable<int> M07_NB_PLACES { get; set; }
        public Nullable<int> M07_TAILLE { get; set; }
        public Nullable<int> M07_NIVEAU { get; set; }
        public Nullable<System.DateTime> M07_DATE_VERROU { get; set; }
        public Nullable<int> M07_ORDRE { get; set; }
        public string M07_ADRESSE { get; set; }
        public string M07_CODE_POSTAL { get; set; }
        public string M07_VILLE { get; set; }
        public Nullable<int> M07_ID_PERE_M07 { get; set; }
        public Nullable<long> M07_MANIFESTATIONS_M14 { get; set; }
        public Nullable<System.DateTime> M07_DATE_ACCES_DEB { get; set; }
        public Nullable<System.DateTime> M07_DATE_ACCES_FIN { get; set; }
        public string M07_GESTION_LIEU { get; set; }
        public string M07_PLAN_ACCES { get; set; }
        public string M07_PLAN_SALLE { get; set; }
        public Nullable<int> M07_SEG_M35 { get; set; }
        public Nullable<int> M07_SEG_M36 { get; set; }
        public Nullable<int> M07_SEG_M37 { get; set; }
        public Nullable<int> M07_SEG_M38 { get; set; }
        public Nullable<int> M07_SEG_M39 { get; set; }
        public string M07_LIBRE1 { get; set; }
        public string M07_LIBRE2 { get; set; }
        public string M07_LIBRE3 { get; set; }
        public string M07_LIBRE4 { get; set; }
        public string M07_LIBRE5 { get; set; }
        public Nullable<short> M07_TACTILE { get; set; }
        public string M07_DESC_GEN { get; set; }
        public string M07_DESC_IMG { get; set; }
        public string M07_DESC_ACC { get; set; }
        public string M07_RESTAURATION { get; set; }
        public string M07_DIVERS { get; set; }
        public string M07_PRESTATION { get; set; }
        public string M07_SERVICES { get; set; }
        public string M07_OUVERTURE { get; set; }
        public string M07_DESC_ACCESS { get; set; }
        public Nullable<short> M07_GESTION_ACCES { get; set; }
        public Nullable<short> M07_TYPE { get; set; }
        public string M07_TMP { get; set; }
        public string M07_MAIL { get; set; }
        public string M07_MAIL_LOGISTIC { get; set; }
        public Nullable<short> M07_MONTAGE { get; set; }
        public Nullable<short> M07_DEMONTAGE { get; set; }
        public string M07_TEL { get; set; }
        public string M07_FAX { get; set; }
        public string M07_REF_BADGEUSE { get; set; }
        public Nullable<int> M07_TYPE_M59 { get; set; }
        public Nullable<short> M07_PLAGE_ACCES { get; set; }
        public string M07_REF { get; set; }
        public Nullable<short> M07_TABLE { get; set; }
        public Nullable<short> M07_TYPE_PRESTATAIRE { get; set; }
        public Nullable<short> M07_VISIBLE_WEB { get; set; }
        public Nullable<int> M07_ID_ORG_G12 { get; set; }
        public Nullable<int> M07_ID_UNITE_STOCK_F46 { get; set; }
        public Nullable<int> M07_ID_CENTRE_DE_PROFIT_F51 { get; set; }
        public Nullable<decimal> M07_LONGITUDE { get; set; }
        public Nullable<decimal> M07_LATITUDE { get; set; }
        public string M07_GEOLOC_ADRESSE { get; set; }
        public string M07_DESC_HTM { get; set; }
        public string M07_PREFIX { get; set; }
        public Nullable<short> M07_CARTE { get; set; }
        public string M07_COULEUR { get; set; }
        public Nullable<int> M07_NB_TABLES { get; set; }
        public Nullable<int> M07_NB_PLACES_PAR_TABLE { get; set; }
        public Nullable<int> M07_ID_TYPE_M71 { get; set; }
        public Nullable<int> M07_ID_ADMIN_A48 { get; set; }
        public Nullable<int> M07_CAPACITE_MINI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADH_MESSAGE_A62> ADH_MESSAGE_A62 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADH_PANIER_A61> ADH_PANIER_A61 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADH_PRESTATION_A10> ADH_PRESTATION_A10 { get; set; }
        public virtual CFG_SOCIETE_C13 CFG_SOCIETE_C13 { get; set; }
        public virtual FIN_CENTRE_DE_PROFIT_F51 FIN_CENTRE_DE_PROFIT_F51 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FIN_DETAILS_COMMANDES_F07> FIN_DETAILS_COMMANDES_F07 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FIN_OCCUPATION_LIEUX_F62> FIN_OCCUPATION_LIEUX_F62 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FIN_PRODUIT_LIEUX_F36> FIN_PRODUIT_LIEUX_F36 { get; set; }
        public virtual GRC_ORGANISMES_G09 GRC_ORGANISMES_G09 { get; set; }
        public virtual MAN_CONFIGURATION_M01 MAN_CONFIGURATION_M01 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAN_LIEUX_CONFIGURATION_M08> MAN_LIEUX_CONFIGURATION_M08 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAN_LIEUX_M07> MAN_LIEUX_M071 { get; set; }
        public virtual MAN_LIEUX_M07 MAN_LIEUX_M072 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAN_LIEUX_MANIF_M10> MAN_LIEUX_MANIF_M10 { get; set; }
        public virtual MAN_MANIFESTATIONS_M14 MAN_MANIFESTATIONS_M14 { get; set; }
        public virtual MAN_TYPE_LIEU_M35 MAN_TYPE_LIEU_M35 { get; set; }
        public virtual MAN_TYPE_LIEU_M36 MAN_TYPE_LIEU_M36 { get; set; }
        public virtual MAN_TYPE_LIEU_M37 MAN_TYPE_LIEU_M37 { get; set; }
        public virtual MAN_TYPE_LIEU_M38 MAN_TYPE_LIEU_M38 { get; set; }
        public virtual MAN_TYPE_LIEU_M39 MAN_TYPE_LIEU_M39 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAN_LIEUX_ORG_DROIT_M54> MAN_LIEUX_ORG_DROIT_M54 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAN_LIEUX_USER_DROIT_M61> MAN_LIEUX_USER_DROIT_M61 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAN_LISTE_IMAGES_LIEUX_M64> MAN_LISTE_IMAGES_LIEUX_M64 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REC_CARTE_R02> REC_CARTE_R02 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_PLAN_SALLE_T03> TBL_PLAN_SALLE_T03 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_RESERVATION_T04> TBL_RESERVATION_T04 { get; set; }
    }
}
