//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAN_TYPE_RSX_PARAM_M60
    {
        public int M60_ID { get; set; }
        public Nullable<int> M60_ID_M59 { get; set; }
        public Nullable<int> M60_ID_C41 { get; set; }
        public string M60_NOM_CHAMP { get; set; }
        public string M60_LIBELLE { get; set; }
        public string M60_VALUES_SEG { get; set; }
        public string M60_NOM_CTL { get; set; }
        public Nullable<short> M60_ORIGINAL { get; set; }
        public Nullable<short> M60_ORDRE { get; set; }
        public string M60_NOM_CTL_LIE { get; set; }
        public string M60_VALUES_SEG_LIB { get; set; }
    }
}
