//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAN_CLIENTS_M41
    {
        public int M41_ID { get; set; }
        public Nullable<long> M41_ID_ORG_G09 { get; set; }
        public Nullable<long> M41_ID_CTC_G03 { get; set; }
        public Nullable<long> M41_ID_MANIF_M14 { get; set; }
        public Nullable<long> M41_ID_EVENT_M02 { get; set; }
        public Nullable<int> M41_PAX_EVT { get; set; }
        public Nullable<int> M41_PAX_MAN { get; set; }
        public Nullable<int> M41_SUPERFICIE { get; set; }
        public Nullable<System.DateTime> M41_DATE_DEB { get; set; }
        public Nullable<System.DateTime> M41_DATE_FIN { get; set; }
        public Nullable<System.DateTime> M41_DATE_DEB1 { get; set; }
        public Nullable<System.DateTime> M41_DATE_FIN1 { get; set; }
        public string M41_LIBRE1 { get; set; }
        public string M41_LIBRE2 { get; set; }
        public string M41_LIBRE3 { get; set; }
        public string M41_LIBRE4 { get; set; }
        public string M41_LIBRE5 { get; set; }
        public Nullable<short> M41_CHK1 { get; set; }
        public Nullable<short> M41_CHK2 { get; set; }
        public Nullable<short> M41_CHK3 { get; set; }
        public Nullable<short> M41_CHK4 { get; set; }
        public Nullable<short> M41_CHK5 { get; set; }
        public Nullable<int> M41_TYPE_M42 { get; set; }
        public Nullable<int> M41_TYPE_M43 { get; set; }
        public Nullable<int> M41_TYPE_M44 { get; set; }
        public Nullable<int> M41_TYPE_M45 { get; set; }
        public Nullable<int> M41_TYPE_M46 { get; set; }
        public Nullable<int> M41_ETAT_M49 { get; set; }
        public string M41_IMG { get; set; }
        public string M41_PLAN { get; set; }
        public string M41_DESC1 { get; set; }
        public string M41_DESC2 { get; set; }
        public Nullable<int> M41_ID_USER_C18 { get; set; }
        public Nullable<int> M41_PAX_EVT_OPT { get; set; }
        public Nullable<int> M41_PAX_EVT_GRT { get; set; }
        public Nullable<int> M41_PAX_MAN_OPT { get; set; }
        public Nullable<int> M41_PAX_MAN_GRT { get; set; }
        public string M41_TEXTSTANDS { get; set; }
    }
}
