//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAN_TYPE_MAN_CLI_M45
    {
        public int M45_ID { get; set; }
        public string M45_LIBELLE { get; set; }
        public Nullable<int> M45_ORDRE { get; set; }
        public Nullable<short> M45_INACTIF { get; set; }
    }
}
