//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAN_ETAT_CLI_M49
    {
        public int M49_ID { get; set; }
        public string M49_LIBELLE { get; set; }
        public Nullable<int> M49_VALEUR { get; set; }
        public Nullable<int> M49_ORDRE { get; set; }
        public Nullable<int> M49_COULEUR { get; set; }
    }
}
