//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAN_TYPES_MAN_M78
    {
        public int M78_ID { get; set; }
        public Nullable<long> M78_ID_MAN_M14 { get; set; }
        public Nullable<int> M78_ID_TYPES_M77 { get; set; }
    }
}
