//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAN_MANCLI_STANDS_M55
    {
        public int M55_ID { get; set; }
        public string M55_LIBELLE { get; set; }
        public Nullable<int> M55_ID_PERE_M55 { get; set; }
        public Nullable<long> M55_ID_MANIF_M14 { get; set; }
        public Nullable<int> M55_NB_PLACES { get; set; }
        public Nullable<int> M55_TAILLE { get; set; }
        public Nullable<int> M55_NIVEAU { get; set; }
        public Nullable<System.DateTime> M55_DATE_VERROU { get; set; }
        public Nullable<int> M55_ORDRE { get; set; }
        public Nullable<System.DateTime> M55_DATE_ACCES_DEB { get; set; }
        public Nullable<System.DateTime> M55_DATE_ACCES_FIN { get; set; }
        public string M55_GESTION_LIEU { get; set; }
        public string M55_PLAN_ACCES { get; set; }
        public string M55_PLAN_SALLE { get; set; }
        public Nullable<short> M55_CHK1 { get; set; }
        public Nullable<short> M55_CHK2 { get; set; }
        public Nullable<short> M55_CHK3 { get; set; }
        public Nullable<short> M55_CHK4 { get; set; }
        public Nullable<short> M55_CHK5 { get; set; }
        public string M55_LIBRE1 { get; set; }
        public string M55_LIBRE2 { get; set; }
        public string M55_LIBRE3 { get; set; }
        public string M55_LIBRE4 { get; set; }
        public string M55_LIBRE5 { get; set; }
        public Nullable<int> M55_ID_PRODUIT_F13 { get; set; }
    }
}
