//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAN_EVENEMENTS_M02
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAN_EVENEMENTS_M02()
        {
            this.FIN_COMMANDES_F04 = new HashSet<FIN_COMMANDES_F04>();
            this.FIN_DETAILS_COMMANDES_F07 = new HashSet<FIN_DETAILS_COMMANDES_F07>();
            this.GRC_ACTIONS_G01 = new HashSet<GRC_ACTIONS_G01>();
            this.MAN_LIEUX_MANIF_M10 = new HashSet<MAN_LIEUX_MANIF_M10>();
            this.TBL_RESERVATION_T04 = new HashSet<TBL_RESERVATION_T04>();
        }
    
        public long M02_ID { get; set; }
        public Nullable<long> M02_ID_MANIF_M14 { get; set; }
        public Nullable<int> M02_ID_CONFIGURATION_M01 { get; set; }
        public Nullable<int> M02_ID_SOC_C13 { get; set; }
        public Nullable<int> M02_ID_USER_C18 { get; set; }
        public Nullable<int> M02_ID_MOTIF_ANNULE_M15 { get; set; }
        public string M02_NOTE { get; set; }
        public Nullable<System.DateTime> M02_DATE_DEBUT { get; set; }
        public Nullable<System.DateTime> M02_DATE_FIN { get; set; }
        public Nullable<int> M02_PAX { get; set; }
        public Nullable<int> M02_POSITION { get; set; }
        public Nullable<System.DateTime> M02_DATE_POSE_OPTION { get; set; }
        public Nullable<System.DateTime> M02_DATE_CONFIRMATION { get; set; }
        public Nullable<System.DateTime> M02_DATE_ANNULATION { get; set; }
        public Nullable<int> M02_REVALIDATION { get; set; }
        public Nullable<System.DateTime> M02_DATE_REVALIDATION { get; set; }
        public Nullable<System.DateTime> M02_HEURE_DEBUT { get; set; }
        public Nullable<System.DateTime> M02_HEURE_FIN { get; set; }
        public Nullable<int> M02_COULEUR { get; set; }
        public Nullable<System.DateTime> M02_DATE_ECHEANCE { get; set; }
        public Nullable<System.DateTime> M02_DATE_VERROU { get; set; }
        public string M02_NOTE_CONFIRMATION { get; set; }
        public string M02_NOTE_BATIMENT { get; set; }
        public string M02_LIBRE1 { get; set; }
        public string M02_LIBRE2 { get; set; }
        public string M02_LIBRE3 { get; set; }
        public string M02_LIBRE4 { get; set; }
        public string M02_LIBRE5 { get; set; }
        public string M02_LIBRE6 { get; set; }
        public string M02_LIBRE7 { get; set; }
        public string M02_LIBRE8 { get; set; }
        public Nullable<int> M02_ETAT_M21 { get; set; }
        public Nullable<int> M02_TYPE_EVT1_M18 { get; set; }
        public Nullable<int> M02_TYPE_EVT2_M19 { get; set; }
        public Nullable<int> M02_TYPE_EVT3_M20 { get; set; }
        public Nullable<int> M02_TYPE_EVT4_M22 { get; set; }
        public Nullable<int> M02_TYPE_EVT5_M23 { get; set; }
        public Nullable<int> M02_TYPE_EVT6_M24 { get; set; }
        public Nullable<int> M02_TYPE_EVT7_M25 { get; set; }
        public Nullable<int> M02_TYPE_EVT8_M26 { get; set; }
        public string M02_CODE { get; set; }
        public Nullable<short> M02_CHK1 { get; set; }
        public Nullable<short> M02_CHK2 { get; set; }
        public Nullable<short> M02_CHK3 { get; set; }
        public Nullable<short> M02_DOUBLON { get; set; }
        public Nullable<short> M02_INSTALL { get; set; }
        public Nullable<short> M02_POSITION2 { get; set; }
        public Nullable<short> M02_PUBLIQUE { get; set; }
        public Nullable<short> M02_MONTAGE { get; set; }
        public Nullable<short> M02_DEMONTAGE { get; set; }
        public string M02_NOTE_ANNULATION { get; set; }
        public Nullable<System.DateTime> M02_DATE_DERN_MODIF { get; set; }
        public Nullable<long> M02_ID_EVENT_ORI_M02 { get; set; }
        public Nullable<short> M02_MAJEUR { get; set; }
        public string M02_LIBELLE { get; set; }
        public Nullable<int> M02_NB_TABLES { get; set; }
        public Nullable<int> M02_APIID { get; set; }
        public Nullable<int> M02_ID_TYPE_EVT9_M74 { get; set; }
        public Nullable<int> M02_ID_TYPE_EVT10_M75 { get; set; }
    
        public virtual CFG_SOCIETE_C13 CFG_SOCIETE_C13 { get; set; }
        public virtual CFG_UTILISATEURS_C18 CFG_UTILISATEURS_C18 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FIN_COMMANDES_F04> FIN_COMMANDES_F04 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FIN_DETAILS_COMMANDES_F07> FIN_DETAILS_COMMANDES_F07 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRC_ACTIONS_G01> GRC_ACTIONS_G01 { get; set; }
        public virtual MAN_CONFIGURATION_M01 MAN_CONFIGURATION_M01 { get; set; }
        public virtual MAN_ETAT_M21 MAN_ETAT_M21 { get; set; }
        public virtual MAN_TYPE_EVT1_M18 MAN_TYPE_EVT1_M18 { get; set; }
        public virtual MAN_TYPE_EVT2_M19 MAN_TYPE_EVT2_M19 { get; set; }
        public virtual MAN_TYPE_EVT3_M20 MAN_TYPE_EVT3_M20 { get; set; }
        public virtual MAN_TYPE_EVT4_M22 MAN_TYPE_EVT4_M22 { get; set; }
        public virtual MAN_TYPE_EVT5_M23 MAN_TYPE_EVT5_M23 { get; set; }
        public virtual MAN_TYPE_EVT6_M24 MAN_TYPE_EVT6_M24 { get; set; }
        public virtual MAN_TYPE_EVT7_M25 MAN_TYPE_EVT7_M25 { get; set; }
        public virtual MAN_TYPE_EVT8_M26 MAN_TYPE_EVT8_M26 { get; set; }
        public virtual MAN_MANIFESTATIONS_M14 MAN_MANIFESTATIONS_M14 { get; set; }
        public virtual MAN_MOTIF_ANNULE_M15 MAN_MOTIF_ANNULE_M15 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAN_LIEUX_MANIF_M10> MAN_LIEUX_MANIF_M10 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_RESERVATION_T04> TBL_RESERVATION_T04 { get; set; }
    }
}
