//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAN_MANIFESTATIONS_M14
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAN_MANIFESTATIONS_M14()
        {
            this.ADH_ACTIONS_A01 = new HashSet<ADH_ACTIONS_A01>();
            this.ADH_COMMENTAIRE_A94 = new HashSet<ADH_COMMENTAIRE_A94>();
            this.BIL_BADGE_MODELE_B02 = new HashSet<BIL_BADGE_MODELE_B02>();
            this.BIL_EBILLET_MODELE_B01 = new HashSet<BIL_EBILLET_MODELE_B01>();
            this.FIN_COMMANDES_F04 = new HashSet<FIN_COMMANDES_F04>();
            this.FIN_DETAILS_COMMANDES_F07 = new HashSet<FIN_DETAILS_COMMANDES_F07>();
            this.GRC_ACTIONS_G01 = new HashSet<GRC_ACTIONS_G01>();
            this.HOT_RESERVATION_H01 = new HashSet<HOT_RESERVATION_H01>();
            this.INV_CHAMPS_PRIORISES_I29 = new HashSet<INV_CHAMPS_PRIORISES_I29>();
            this.INV_COL_GRDLOGISTIQUE_I21 = new HashSet<INV_COL_GRDLOGISTIQUE_I21>();
            this.INV_COL_ROOMINGLIST_I17 = new HashSet<INV_COL_ROOMINGLIST_I17>();
            this.INV_CONFIG_HEBERGEMENT_I10 = new HashSet<INV_CONFIG_HEBERGEMENT_I10>();
            this.INV_CONFIG_TRANSFERT_I16 = new HashSet<INV_CONFIG_TRANSFERT_I16>();
            this.INV_FORFAIT_I24 = new HashSet<INV_FORFAIT_I24>();
            this.INV_FORMAT_PRESTA_I09 = new HashSet<INV_FORMAT_PRESTA_I09>();
            this.INV_INSCRIPTION_I25 = new HashSet<INV_INSCRIPTION_I25>();
            this.INV_LISTES_I18 = new HashSet<INV_LISTES_I18>();
            this.INV_MENUS_SITE_I31 = new HashSet<INV_MENUS_SITE_I31>();
            this.INV_NOTIFICATION_I28 = new HashSet<INV_NOTIFICATION_I28>();
            this.INV_REC_I22 = new HashSet<INV_REC_I22>();
            this.INV_REGLES_CATEGORIES_I02 = new HashSet<INV_REGLES_CATEGORIES_I02>();
            this.INV_TRANSFERT_I15 = new HashSet<INV_TRANSFERT_I15>();
            this.INV_TRANSPORT_I39 = new HashSet<INV_TRANSPORT_I39>();
            this.MAN_EVENEMENTS_M02 = new HashSet<MAN_EVENEMENTS_M02>();
            this.MAN_LIEUX_FILTRE_M09 = new HashSet<MAN_LIEUX_FILTRE_M09>();
            this.MAN_LIEUX_M07 = new HashSet<MAN_LIEUX_M07>();
            this.MAN_PRESTATIONS_M16 = new HashSet<MAN_PRESTATIONS_M16>();
            this.PDC_DOCUMENT_P02 = new HashSet<PDC_DOCUMENT_P02>();
            this.USR_MESSAGE_U14 = new HashSet<USR_MESSAGE_U14>();
            this.USR_MESSAGE_ARCHIVE_U22 = new HashSet<USR_MESSAGE_ARCHIVE_U22>();
            this.USR_ITEM_PORTAIL_U33 = new HashSet<USR_ITEM_PORTAIL_U33>();
        }
    
        public long M14_ID { get; set; }
        public Nullable<long> M14_ID_ORGANISME_G09 { get; set; }
        public Nullable<long> M14_ID_ORGANISME1_G09 { get; set; }
        public Nullable<long> M14_ID_ORGANISME2_G09 { get; set; }
        public Nullable<long> M14_ID_CONTACT_G03 { get; set; }
        public Nullable<int> M14_ID_MOTIF_ANNULE_M15 { get; set; }
        public Nullable<int> M14_ID_USER_C18 { get; set; }
        public Nullable<int> M14_ID_USER_COMMERCIAL_C18 { get; set; }
        public Nullable<int> M14_ID_USER_TECHNIQUE_C18 { get; set; }
        public Nullable<int> M14_ID_SOC_C13 { get; set; }
        public string M14_CODE { get; set; }
        public string M14_LIBELLE { get; set; }
        public string M14_NOM_ORGANISME1_G09 { get; set; }
        public string M14_NOTE { get; set; }
        public Nullable<System.DateTime> M14_DATE_DEBUT { get; set; }
        public Nullable<System.DateTime> M14_DATE_FIN { get; set; }
        public Nullable<int> M14_PAX { get; set; }
        public Nullable<System.DateTime> M14_HEURE_DEBUT { get; set; }
        public Nullable<System.DateTime> M14_HEURE_FIN { get; set; }
        public string M14_USER_NOM { get; set; }
        public Nullable<System.DateTime> M14_DATE_ECHEANCE { get; set; }
        public Nullable<System.DateTime> M14_DATE_VERROU { get; set; }
        public string M14_NOTE_CONFIRMATION { get; set; }
        public Nullable<System.DateTime> M14_DATE_CREATION { get; set; }
        public Nullable<int> M14_INTERLOCUTEUR { get; set; }
        public string M14_TEXTE_CLIENT { get; set; }
        public Nullable<short> M14_DOUBLON { get; set; }
        public Nullable<int> M14_NB_REVALIDATION { get; set; }
        public Nullable<System.DateTime> M14_DATE_GLOBALE { get; set; }
        public Nullable<decimal> M14_ACOMPTEF { get; set; }
        public Nullable<decimal> M14_TOTAL_COMMANDE { get; set; }
        public Nullable<decimal> M14_BUDGET { get; set; }
        public Nullable<int> M14_ETAT_M21 { get; set; }
        public string M14_LIBRE1 { get; set; }
        public string M14_LIBRE2 { get; set; }
        public string M14_LIBRE3 { get; set; }
        public string M14_LIBRE4 { get; set; }
        public string M14_LIBRE5 { get; set; }
        public string M14_LIBRE6 { get; set; }
        public string M14_LIBRE7 { get; set; }
        public string M14_LIBRE8 { get; set; }
        public Nullable<int> M14_TYPE_MAN1_M27 { get; set; }
        public Nullable<int> M14_TYPE_MAN2_M28 { get; set; }
        public Nullable<int> M14_TYPE_MAN3_M29 { get; set; }
        public Nullable<int> M14_TYPE_MAN4_M30 { get; set; }
        public Nullable<int> M14_TYPE_MAN5_M31 { get; set; }
        public Nullable<int> M14_TYPE_MAN6_M32 { get; set; }
        public Nullable<int> M14_TYPE_MAN7_M33 { get; set; }
        public Nullable<int> M14_TYPE_MAN8_M34 { get; set; }
        public Nullable<short> M14_SOLDE { get; set; }
        public Nullable<short> M14_CHK1 { get; set; }
        public Nullable<short> M14_CHK2 { get; set; }
        public Nullable<short> M14_CHK3 { get; set; }
        public Nullable<short> M14_DESIDERATAS_ON { get; set; }
        public Nullable<int> M14_ID_GROUPE { get; set; }
        public Nullable<decimal> M14_ACOMPTEE { get; set; }
        public Nullable<long> M14_ID_CONTACT2_G03 { get; set; }
        public Nullable<int> M14_POSITION { get; set; }
        public Nullable<short> M14_NEEDVALID { get; set; }
        public string M14_MOTIFVALID { get; set; }
        public string M14_LIBELLE2 { get; set; }
        public Nullable<short> M14_POSITION2 { get; set; }
        public Nullable<int> M14_ID_USER_VALIDEUR_C18 { get; set; }
        public Nullable<System.DateTime> M14_DATE_DERN_MODIF { get; set; }
        public Nullable<short> M14_IN_EPARTICIPANT { get; set; }
        public Nullable<int> M14_ID_ADMIN_A48 { get; set; }
        public Nullable<int> M14_ID_REGION_G30 { get; set; }
        public Nullable<int> M14_ID_DPT_G31 { get; set; }
        public string M14_NOM_LIEU { get; set; }
        public string M14_ADRESSE_LIEU { get; set; }
        public string M14_CP_LIEU { get; set; }
        public string M14_VILLE_LIEU { get; set; }
        public string M14_ADRESSE_LIEU_CPLT { get; set; }
        public Nullable<int> M14_ID_PAYS_G29 { get; set; }
        public string M14_TEMPLATE { get; set; }
        public Nullable<long> M14_ID_AGORAEVENT { get; set; }
        public Nullable<decimal> M14_PRIXPAX_HT { get; set; }
        public Nullable<decimal> M14_PRIXPAX_TTC { get; set; }
        public Nullable<int> M14_ID_TVA_PRIXPAX_F17 { get; set; }
        public Nullable<decimal> M14_AHRES { get; set; }
        public Nullable<decimal> M14_AHRES_PCT { get; set; }
        public Nullable<int> M14_ID_LAST_USER_C18 { get; set; }
        public Nullable<short> M14_REFUS { get; set; }
        public Nullable<long> M14_ID_FORECAST_F41 { get; set; }
        public Nullable<int> M14_ID_USER_MODIF_C18 { get; set; }
        public string M14_NOM_URL { get; set; }
        public Nullable<System.DateTime> M14_DATE1 { get; set; }
        public Nullable<System.DateTime> M14_DATE2 { get; set; }
        public Nullable<short> M14_INDIV { get; set; }
        public Nullable<int> M14_ITERATION { get; set; }
        public Nullable<int> M14_APIID { get; set; }
        public Nullable<int> M14_MODE_REGLEMENT_G60 { get; set; }
        public string M14_LIB_DRE { get; set; }
        public Nullable<short> M14_FAVORIS { get; set; }
        public Nullable<int> M14_ID_CONTACT3_G03 { get; set; }
        public Nullable<int> M14_ID_TYPE_MAN9_M72 { get; set; }
        public Nullable<int> M14_ID_TYPE_MAN10_M73 { get; set; }
        public string M14_LIBRE9 { get; set; }
        public Nullable<int> M14_ID_TYPE_MAN11_M79 { get; set; }
        public Nullable<int> M14_ID_TYPE_MAN12_M80 { get; set; }
        public Nullable<int> M14_ID_TYPE_MAN13_M81 { get; set; }
        public Nullable<int> M14_ID_TYPE_MAN14_M82 { get; set; }
        public Nullable<int> M14_ID_TYPE_MAN15_M83 { get; set; }
        public string M14_IMAGE { get; set; }
        public Nullable<short> M14_VITRINE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADH_ACTIONS_A01> ADH_ACTIONS_A01 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADH_COMMENTAIRE_A94> ADH_COMMENTAIRE_A94 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BIL_BADGE_MODELE_B02> BIL_BADGE_MODELE_B02 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BIL_EBILLET_MODELE_B01> BIL_EBILLET_MODELE_B01 { get; set; }
        public virtual CFG_SOCIETE_C13 CFG_SOCIETE_C13 { get; set; }
        public virtual CFG_UTILISATEURS_C18 CFG_UTILISATEURS_C18 { get; set; }
        public virtual CFG_UTILISATEURS_C18 CFG_UTILISATEURS_C181 { get; set; }
        public virtual CFG_UTILISATEURS_C18 CFG_UTILISATEURS_C182 { get; set; }
        public virtual CFG_UTILISATEURS_C18 CFG_UTILISATEURS_C183 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FIN_COMMANDES_F04> FIN_COMMANDES_F04 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FIN_DETAILS_COMMANDES_F07> FIN_DETAILS_COMMANDES_F07 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRC_ACTIONS_G01> GRC_ACTIONS_G01 { get; set; }
        public virtual GRC_CONTACTS_G03 GRC_CONTACTS_G03 { get; set; }
        public virtual GRC_ORGANISMES_G09 GRC_ORGANISMES_G09 { get; set; }
        public virtual GRC_ORGANISMES_G09 GRC_ORGANISMES_G091 { get; set; }
        public virtual GRC_ORGANISMES_G09 GRC_ORGANISMES_G092 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOT_RESERVATION_H01> HOT_RESERVATION_H01 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_CHAMPS_PRIORISES_I29> INV_CHAMPS_PRIORISES_I29 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_COL_GRDLOGISTIQUE_I21> INV_COL_GRDLOGISTIQUE_I21 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_COL_ROOMINGLIST_I17> INV_COL_ROOMINGLIST_I17 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_CONFIG_HEBERGEMENT_I10> INV_CONFIG_HEBERGEMENT_I10 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_CONFIG_TRANSFERT_I16> INV_CONFIG_TRANSFERT_I16 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_FORFAIT_I24> INV_FORFAIT_I24 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_FORMAT_PRESTA_I09> INV_FORMAT_PRESTA_I09 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_INSCRIPTION_I25> INV_INSCRIPTION_I25 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_LISTES_I18> INV_LISTES_I18 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_MENUS_SITE_I31> INV_MENUS_SITE_I31 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_NOTIFICATION_I28> INV_NOTIFICATION_I28 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_REC_I22> INV_REC_I22 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_REGLES_CATEGORIES_I02> INV_REGLES_CATEGORIES_I02 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_TRANSFERT_I15> INV_TRANSFERT_I15 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_TRANSPORT_I39> INV_TRANSPORT_I39 { get; set; }
        public virtual MAN_ETAT_M21 MAN_ETAT_M21 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAN_EVENEMENTS_M02> MAN_EVENEMENTS_M02 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAN_LIEUX_FILTRE_M09> MAN_LIEUX_FILTRE_M09 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAN_LIEUX_M07> MAN_LIEUX_M07 { get; set; }
        public virtual MAN_TYPE_MAN1_M27 MAN_TYPE_MAN1_M27 { get; set; }
        public virtual MAN_TYPE_MAN2_M28 MAN_TYPE_MAN2_M28 { get; set; }
        public virtual MAN_TYPE_MAN3_M29 MAN_TYPE_MAN3_M29 { get; set; }
        public virtual MAN_TYPE_MAN4_M30 MAN_TYPE_MAN4_M30 { get; set; }
        public virtual MAN_TYPE_MAN5_M31 MAN_TYPE_MAN5_M31 { get; set; }
        public virtual MAN_TYPE_MAN6_M32 MAN_TYPE_MAN6_M32 { get; set; }
        public virtual MAN_TYPE_MAN7_M33 MAN_TYPE_MAN7_M33 { get; set; }
        public virtual MAN_TYPE_MAN8_M34 MAN_TYPE_MAN8_M34 { get; set; }
        public virtual MAN_MOTIF_ANNULE_M15 MAN_MOTIF_ANNULE_M15 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAN_PRESTATIONS_M16> MAN_PRESTATIONS_M16 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PDC_DOCUMENT_P02> PDC_DOCUMENT_P02 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USR_MESSAGE_U14> USR_MESSAGE_U14 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USR_MESSAGE_ARCHIVE_U22> USR_MESSAGE_ARCHIVE_U22 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USR_ITEM_PORTAIL_U33> USR_ITEM_PORTAIL_U33 { get; set; }
    }
}
