//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAN_LIEUX_FILTRE_M09
    {
        public int M09_ID { get; set; }
        public Nullable<long> M09_ID_MANIF_M14 { get; set; }
        public Nullable<int> M09_ID_CONFIGURATION_M01 { get; set; }
        public string M09_LIBELLE { get; set; }
        public Nullable<int> M09_NB_PLACES { get; set; }
        public Nullable<int> M09_SIGNE_NB_PLACE { get; set; }
        public Nullable<int> M09_SUPERFICIE { get; set; }
        public Nullable<int> M09_SIGNE_SUPERFICIE { get; set; }
        public string M09_CODE_POSTAL { get; set; }
        public string M09_VILLE { get; set; }
        public string M09_LIBRE1 { get; set; }
        public string M09_LIBRE2 { get; set; }
        public string M09_LIBRE3 { get; set; }
        public string M09_LIBRE4 { get; set; }
        public string M09_LIBRE5 { get; set; }
        public Nullable<int> M09_SIGNE_LIBRE1 { get; set; }
        public Nullable<int> M09_SIGNE_LIBRE2 { get; set; }
        public Nullable<int> M09_SIGNE_LIBRE3 { get; set; }
        public Nullable<int> M09_SIGNE_LIBRE4 { get; set; }
        public Nullable<int> M09_SIGNE_LIBRE5 { get; set; }
        public Nullable<int> M09_SEG1 { get; set; }
        public Nullable<int> M09_SEG2 { get; set; }
        public Nullable<int> M09_SEG3 { get; set; }
        public Nullable<int> M09_SEG4 { get; set; }
        public Nullable<int> M09_SEG5 { get; set; }
    
        public virtual MAN_CONFIGURATION_M01 MAN_CONFIGURATION_M01 { get; set; }
        public virtual MAN_MANIFESTATIONS_M14 MAN_MANIFESTATIONS_M14 { get; set; }
    }
}
