//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAN_INTERVENANTS_M06
    {
        public int M06_ID { get; set; }
        public Nullable<int> M06_ID_TITRE { get; set; }
        public string M06_NOM { get; set; }
        public string M06_PRENOM { get; set; }
        public string M06_FONCTION { get; set; }
        public string M06_TELEPHONE { get; set; }
        public string M06_EMAIL { get; set; }
    }
}
