//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAN_EVT_VAL_SEGS_LIBRES_M05
    {
        public int M05_ID { get; set; }
        public string M05_VALUE { get; set; }
        public Nullable<int> M05_ID_REF { get; set; }
    }
}
