//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAN_LIEU_LISTE_M51
    {
        public int M51_ID { get; set; }
        public Nullable<int> M51_ID_LIEU_M07 { get; set; }
        public string M51_LIBRE1 { get; set; }
        public string M51_LIBRE2 { get; set; }
        public Nullable<System.DateTime> M51_DATE_1 { get; set; }
        public Nullable<System.DateTime> M51_DATE_2 { get; set; }
        public Nullable<short> M51_STATUT { get; set; }
        public Nullable<int> M51_SEG_M52 { get; set; }
        public Nullable<int> M51_SEG_M53 { get; set; }
    }
}
