//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAN_TYPE_LIEU_M71
    {
        public int M71_ID { get; set; }
        public Nullable<int> M71_ORDRE { get; set; }
        public string M71_LIBELLE { get; set; }
        public string M71_LIBELLE_EN { get; set; }
        public string M71_LIBELLE_AL { get; set; }
        public string M71_LIBELLE_IT { get; set; }
        public string M71_LIBELLE_ES { get; set; }
    }
}
