//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAN_TYPE_EVT1_M18
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAN_TYPE_EVT1_M18()
        {
            this.MAN_EVENEMENTS_M02 = new HashSet<MAN_EVENEMENTS_M02>();
        }
    
        public int M18_ID { get; set; }
        public string M18_LIBELLE { get; set; }
        public Nullable<int> M18_ORDRE { get; set; }
        public Nullable<System.DateTime> M18_HEURE_DEBUT { get; set; }
        public Nullable<System.DateTime> M18_HEURE_FIN { get; set; }
        public Nullable<int> M18_COULEUR { get; set; }
        public Nullable<short> M18_INACTIF { get; set; }
        public Nullable<int> M18_ID_SOC_C13 { get; set; }
        public Nullable<int> M18_ID_TYPE_MANIF1_M27 { get; set; }
        public Nullable<short> M18_TYPE_HEBERGEMENT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAN_EVENEMENTS_M02> MAN_EVENEMENTS_M02 { get; set; }
    }
}
