//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USR_PACKFILTRE_AFFICHAGE_U02
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USR_PACKFILTRE_AFFICHAGE_U02()
        {
            this.USR_PARAM_PACKFILTRE_U12 = new HashSet<USR_PARAM_PACKFILTRE_U12>();
        }
    
        public int U02_ID { get; set; }
        public Nullable<int> U02_ID_LANGUE_U05 { get; set; }
        public string U02_NOM_MODULE { get; set; }
        public string U02_NOM_TABLE { get; set; }
        public string U02_NOM_CHAMP { get; set; }
        public string U02_NOM_TRI { get; set; }
        public Nullable<int> U02_TYPE { get; set; }
        public string U02_NOM_TBL_LIEN { get; set; }
        public string U02_COL_ID_TBL_LIEN { get; set; }
        public string U02_COL_LIBELLE_TBL_LIEN { get; set; }
        public string U02_COL_ORDRE_TBL_LIEN { get; set; }
        public string U02_CHAMP_SOCIETE { get; set; }
    
        public virtual USR_PACKLANGUE_LANGUES_U05 USR_PACKLANGUE_LANGUES_U05 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USR_PARAM_PACKFILTRE_U12> USR_PARAM_PACKFILTRE_U12 { get; set; }
    }
}
