//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USR_RESTRICTIONS_EDITEUR_U37
    {
        public int U37_ID { get; set; }
        public string U37_VALUE { get; set; }
        public int U37_ID_ADMIN_A48 { get; set; }
        public Nullable<short> U37_ORDRE { get; set; }
        public Nullable<short> U37_TYPE { get; set; }
    
        public virtual ADH_EPARTICIPANT_ADMIN_A48 ADH_EPARTICIPANT_ADMIN_A48 { get; set; }
    }
}
