//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USR_ITEM_PORTAIL_U33
    {
        public int U33_ID { get; set; }
        public int U33_ID_ADMIN_A48 { get; set; }
        public Nullable<int> U33_ID_TYPE_M33 { get; set; }
        public string U33_BACKGROUND_IMAGE { get; set; }
        public string U33_FULL_IMAGE { get; set; }
        public string U33_HTML_TEXT { get; set; }
        public int U33_ORDRE { get; set; }
        public Nullable<System.DateTime> U33_DATE_FROM { get; set; }
        public Nullable<System.DateTime> U33_DATE_TO { get; set; }
        public string U33_LINK { get; set; }
        public Nullable<long> U33_LINK_MANIFESTATION_M14 { get; set; }
        public Nullable<short> U33_ITEM_TYPE { get; set; }
        public Nullable<int> U33_ID_TYPE_U36 { get; set; }
        public Nullable<int> U33_ID_TYPE_U35 { get; set; }
    
        public virtual ADH_EPARTICIPANT_ADMIN_A48 ADH_EPARTICIPANT_ADMIN_A48 { get; set; }
        public virtual MAN_MANIFESTATIONS_M14 MAN_MANIFESTATIONS_M14 { get; set; }
        public virtual MAN_TYPE_MAN7_M33 MAN_TYPE_MAN7_M33 { get; set; }
        public virtual USR_TYPE_OUTILS_U36 USR_TYPE_OUTILS_U36 { get; set; }
    }
}
