//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USR_MAILING_PROG_U30
    {
        public int U30_ID { get; set; }
        public Nullable<long> U30_ID_MANIF_M14 { get; set; }
        public Nullable<int> U30_ID_ADMIN_A48 { get; set; }
        public Nullable<int> U30_ID_TEMPLATE_P20 { get; set; }
        public Nullable<int> U30_ID_LANG_C40 { get; set; }
        public Nullable<short> U30_TYPE { get; set; }
        public Nullable<short> U30_ETAT { get; set; }
        public Nullable<int> U30_NB_MAILS { get; set; }
        public Nullable<int> U30_ID_LIST_I18 { get; set; }
        public Nullable<int> U30_ID_LIST_G46 { get; set; }
        public string U30_SQLSTRING { get; set; }
        public Nullable<System.DateTime> U30_DATE_MODIF { get; set; }
        public Nullable<System.DateTime> U30_DATE_ENVOI_PG { get; set; }
        public Nullable<System.DateTime> U30_DATE_ENVOI { get; set; }
        public string U30_OBJET { get; set; }
        public string U30_BODY { get; set; }
        public string U30_URL { get; set; }
        public string U30_APPLIPATH { get; set; }
        public string U30_APPLIHOST { get; set; }
        public Nullable<short> U30_ISHTTPS { get; set; }
    }
}
