//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USR_FORMULAIRE_SOCIETE_U32
    {
        public int U32_ID { get; set; }
        public int U32_ID_FORM_U28 { get; set; }
        public int U32_ID_SOC_C13 { get; set; }
    
        public virtual CFG_SOCIETE_C13 CFG_SOCIETE_C13 { get; set; }
        public virtual USR_FORMULAIRE_U28 USR_FORMULAIRE_U28 { get; set; }
    }
}
