//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USR_MAILING_U15
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USR_MAILING_U15()
        {
            this.USR_LIST_ATTACHMENTS_U24 = new HashSet<USR_LIST_ATTACHMENTS_U24>();
        }
    
        public int U15_ID { get; set; }
        public Nullable<long> U15_ID_EMETTEUR_G03 { get; set; }
        public Nullable<long> U15_ID_MANIF_M14 { get; set; }
        public Nullable<int> U15_ID_ADMIN_A48 { get; set; }
        public Nullable<int> U15_ID_MESSAGE_U15 { get; set; }
        public string U15_EMAIL_EMETTEUR { get; set; }
        public string U15_NOM_EMETTEUR { get; set; }
        public string U15_PRENOM_EMETTEUR { get; set; }
        public Nullable<short> U15_TYPE { get; set; }
        public Nullable<short> U15_ETAT { get; set; }
        public Nullable<short> U15_IMPORTANCE { get; set; }
        public Nullable<short> U15_DMD_CONF { get; set; }
        public Nullable<short> U15_HAS_ATTACHMENT { get; set; }
        public Nullable<System.DateTime> U15_DATE_MODIF { get; set; }
        public Nullable<System.DateTime> U15_DATE_ENVOI_PG { get; set; }
        public Nullable<System.DateTime> U15_DATE_ENVOI { get; set; }
        public string U15_OBJET { get; set; }
        public string U15_BODY { get; set; }
        public string U15_URL { get; set; }
        public string U15_APPLIHOST { get; set; }
        public string U15_APPLIPATH { get; set; }
        public string U15_MAIL_UID { get; set; }
        public Nullable<short> U15_ISHTTPS { get; set; }
        public string U15_LIBELLE { get; set; }
        public Nullable<short> U15_BULKMAILS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USR_LIST_ATTACHMENTS_U24> USR_LIST_ATTACHMENTS_U24 { get; set; }
    }
}
