//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USR_TYPE_ACTUALITES_U35
    {
        public int U35_ID { get; set; }
        public string U35_LIBELLE { get; set; }
        public int U35_ID_ADMIN_A48 { get; set; }
        public Nullable<int> U33_ID_TYPE_U35 { get; set; }
        public Nullable<short> U35_ORDRE { get; set; }
    
        public virtual ADH_EPARTICIPANT_ADMIN_A48 ADH_EPARTICIPANT_ADMIN_A48 { get; set; }
    }
}
