//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USR_PACKFILTRE_NUMFILTRE_U08
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USR_PACKFILTRE_NUMFILTRE_U08()
        {
            this.FIN_EXPORT_COMPTA_AUTO_F49 = new HashSet<FIN_EXPORT_COMPTA_AUTO_F49>();
            this.USR_PACKFILTRE_FILTRE_U03 = new HashSet<USR_PACKFILTRE_FILTRE_U03>();
            this.USR_PACKFILTRE_SAVE_U09 = new HashSet<USR_PACKFILTRE_SAVE_U09>();
            this.USR_PACKFILTRE_PART_U10 = new HashSet<USR_PACKFILTRE_PART_U10>();
        }
    
        public int U08_ID { get; set; }
        public string U08_LIBELLE { get; set; }
        public Nullable<int> U08_ORDRE { get; set; }
        public string U08_NOM_MODULE { get; set; }
        public Nullable<short> U08_WEB { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FIN_EXPORT_COMPTA_AUTO_F49> FIN_EXPORT_COMPTA_AUTO_F49 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USR_PACKFILTRE_FILTRE_U03> USR_PACKFILTRE_FILTRE_U03 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USR_PACKFILTRE_SAVE_U09> USR_PACKFILTRE_SAVE_U09 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USR_PACKFILTRE_PART_U10> USR_PACKFILTRE_PART_U10 { get; set; }
    }
}
