//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USR_FILTRE_SQL_U16
    {
        public int U16_ID { get; set; }
        public Nullable<int> U16_ID_USER_C18 { get; set; }
        public Nullable<int> U16_ID_SOC_C13 { get; set; }
        public string U16_LIBELLE { get; set; }
        public string U16_SQLW { get; set; }
        public string U16_MODULE_FILTRE { get; set; }
    }
}
