//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STA_BUDGET_SOCIETE_S04
    {
        public int S04_ID { get; set; }
        public string S04_LIBELLE { get; set; }
        public Nullable<int> S04_SOCIETE_C12 { get; set; }
        public Nullable<int> S04_DATE_CAL { get; set; }
        public Nullable<int> S04_CALENDRIER_S01 { get; set; }
        public Nullable<int> S04_PERIODE_S02 { get; set; }
        public Nullable<int> S04_NUM_PERIODE_CALENDRIER { get; set; }
        public Nullable<int> S04_BUDGET1 { get; set; }
        public Nullable<int> S04_BUDGET2 { get; set; }
        public Nullable<int> S04_BUDGET3 { get; set; }
        public Nullable<int> S04_MARGE1 { get; set; }
        public Nullable<int> S04_MARGE2 { get; set; }
        public Nullable<int> S04_MARGE3 { get; set; }
        public Nullable<int> S04_QTE1 { get; set; }
        public Nullable<int> S04_QTE2 { get; set; }
        public Nullable<int> S04_QTE3 { get; set; }
    
        public virtual CFG_SEQUENCE_C12 CFG_SEQUENCE_C12 { get; set; }
        public virtual STA_CALENDRIER_S01 STA_CALENDRIER_S01 { get; set; }
        public virtual STA_PERIODE_S02 STA_PERIODE_S02 { get; set; }
    }
}
