//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STA_QCM_NUM_S16
    {
        public int S16_ID { get; set; }
        public string S16_LIBELLE { get; set; }
        public string S16_ETIQUETTE { get; set; }
        public Nullable<short> S16_VISIBLE { get; set; }
        public Nullable<int> S16_ORDRE { get; set; }
        public string S16_LIBELLE_EN { get; set; }
        public string S16_LIBELLE_AL { get; set; }
        public string S16_LIBELLE_ES { get; set; }
        public string S16_LIBELLE_IT { get; set; }
        public Nullable<long> S16_ID_MANIF_M14 { get; set; }
        public Nullable<int> S16_TYPE_QUESTION { get; set; }
        public Nullable<int> S16_HORIZONTALE { get; set; }
    }
}
