//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STA_REP_QCM_S15
    {
        public int S15_ID { get; set; }
        public Nullable<int> S15_ID_QUESTION_S13 { get; set; }
        public Nullable<long> S15_ID_PART_A09 { get; set; }
        public string S15_NOTE { get; set; }
        public Nullable<short> S15_STATUT { get; set; }
        public Nullable<short> S15_VALEUR { get; set; }
        public string S15_IP_USER { get; set; }
        public string S15_MACID_USER { get; set; }
    }
}
