//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STA_ENQUETE_S13
    {
        public int S13_ID { get; set; }
        public Nullable<long> S13_ID_MANIF_M14 { get; set; }
        public string S13_QUESTION { get; set; }
        public Nullable<short> S13_STATUT { get; set; }
        public string S13_NOTE { get; set; }
        public string S13_LIBRE1 { get; set; }
        public Nullable<short> S13_REPONSE { get; set; }
        public Nullable<System.DateTime> S13_DATE_ACTION { get; set; }
        public Nullable<int> S13_ID_QCM_S16 { get; set; }
        public Nullable<int> S13_ID_MODELE_S17 { get; set; }
        public Nullable<short> S13_ORDRE { get; set; }
        public string S13_QUESTION_EN { get; set; }
        public string S13_QUESTION_AL { get; set; }
        public string S13_QUESTION_ES { get; set; }
        public string S13_QUESTION_IT { get; set; }
        public Nullable<int> S13_QUESTION_OBLIGATOIRE { get; set; }
    }
}
