//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STA_CHAMPS_S11
    {
        public int S11_ID { get; set; }
        public string S11_LIBELLE { get; set; }
        public string S11_ETIQUETTE { get; set; }
        public Nullable<short> S11_VISIBLE { get; set; }
        public Nullable<int> S11_ORDRE { get; set; }
    }
}
