//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STA_ETAT_PERSO_S12
    {
        public int S12_ID { get; set; }
        public string S12_LIBELLE { get; set; }
        public Nullable<int> S12_ORDRE { get; set; }
        public string S12_NOM_MENU { get; set; }
        public Nullable<short> S12_NUMFILTRE { get; set; }
        public string S12_NOM_ETAT_AGORA { get; set; }
        public string S12_NIVEAU1 { get; set; }
        public string S12_NIVEAU2 { get; set; }
        public string S12_NIVEAU3 { get; set; }
        public string S12_NIVEAU4 { get; set; }
        public Nullable<short> S12_VENTILATION { get; set; }
        public string S12_DONNEEAFF { get; set; }
        public Nullable<short> S12_AUTO { get; set; }
        public Nullable<short> S12_VISIBLE { get; set; }
        public Nullable<short> S12_DEVISE { get; set; }
        public Nullable<short> S12_TYPE { get; set; }
        public string S12_REGROUPEMENT { get; set; }
        public Nullable<short> S12_SOUS_TOTAUX { get; set; }
        public Nullable<short> S12_GRAPHIQUE { get; set; }
    }
}
