//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STA_DONNEES_S05
    {
        public int S05_ID { get; set; }
        public Nullable<int> S05_ID_MANIF_M14 { get; set; }
        public Nullable<int> S05_ID_EVENT_M02 { get; set; }
        public Nullable<int> S05_ID_LIEU_M07 { get; set; }
        public Nullable<short> S05_CONFIRMEE { get; set; }
        public Nullable<int> S05_PARTICIPANTS { get; set; }
        public Nullable<System.DateTime> S05_DATE_POSE_OPTION { get; set; }
        public Nullable<System.DateTime> S05_DATE_CONFIRMATION { get; set; }
        public Nullable<System.DateTime> S05_DATE_ANNULATION { get; set; }
        public Nullable<System.DateTime> S05_HEURE_DEBUT { get; set; }
        public Nullable<System.DateTime> S05_HEURE_FIN { get; set; }
        public Nullable<System.DateTime> S05_DATE_ECHEANCE { get; set; }
        public Nullable<int> S05_TYPE_EVT1_M18 { get; set; }
        public Nullable<int> S05_TYPE_EVT2_M19 { get; set; }
        public Nullable<int> S05_TYPE_EVT3_M20 { get; set; }
        public Nullable<int> S05_TYPE_EVT4_M22 { get; set; }
        public Nullable<int> S05_TYPE_EVT5_M23 { get; set; }
        public Nullable<int> S05_TYPE_EVT6_M24 { get; set; }
        public Nullable<int> S05_TYPE_EVT7_M25 { get; set; }
        public Nullable<int> S05_TYPE_EVT8_M26 { get; set; }
        public Nullable<int> S05_ID_ORGANISME_G09 { get; set; }
        public string S05_NOM_ORGANISME { get; set; }
        public Nullable<int> S05_ID_CONTACT_G03 { get; set; }
        public string S05_NOM_CONTACT { get; set; }
        public Nullable<int> S05_ID_USER_COMMERCIAL_C18 { get; set; }
        public Nullable<int> S05_ID_USER_TECHNIQUE_C18 { get; set; }
        public string S05_NOM_COMMERCIAL { get; set; }
        public string S05_NOM_TECHNIQUE { get; set; }
        public Nullable<int> S05_ID_USER_C18 { get; set; }
        public string S05_NOM_USER { get; set; }
        public Nullable<int> S05_ID_ETAT_M21 { get; set; }
        public string S05_NOM_ETAT { get; set; }
        public Nullable<int> S05_TYPE_MAN1_M27 { get; set; }
        public Nullable<int> S05_TYPE_MAN2_M28 { get; set; }
        public Nullable<int> S05_TYPE_MAN3_M29 { get; set; }
        public Nullable<int> S05_TYPE_MAN4_M30 { get; set; }
        public Nullable<int> S05_TYPE_MAN5_M31 { get; set; }
        public Nullable<int> S05_TYPE_MAN6_M32 { get; set; }
        public Nullable<int> S05_TYPE_MAN7_M33 { get; set; }
        public Nullable<int> S05_TYPE_MAN8_M34 { get; set; }
        public string S05_LIBELLE_LIEU { get; set; }
        public Nullable<int> S05_TYPE_CTC1_G22 { get; set; }
        public Nullable<int> S05_TYPE_CTC2_G23 { get; set; }
        public Nullable<int> S05_TYPE_CTC3_G24 { get; set; }
        public Nullable<int> S05_TYPE_CTC4_G25 { get; set; }
        public Nullable<int> S05_TYPE_CTC5_G26 { get; set; }
        public Nullable<int> S05_TYPE_ORG1_G12 { get; set; }
        public Nullable<int> S05_TYPE_ORG2_G13 { get; set; }
        public Nullable<int> S05_TYPE_ORG3_G14 { get; set; }
        public Nullable<int> S05_TYPE_ORG4_G15 { get; set; }
        public Nullable<int> S05_TYPE_ORG5_G17 { get; set; }
        public Nullable<int> S05_TYPE_ORG6_G18 { get; set; }
        public Nullable<int> S05_TYPE_ORG7_G19 { get; set; }
        public Nullable<int> S05_TYPE_ORG8_G20 { get; set; }
        public Nullable<int> S05_TYPE_ORG9_G21 { get; set; }
        public Nullable<int> S05_MONTANT { get; set; }
        public Nullable<int> S05_ACOMPTEE { get; set; }
        public Nullable<int> S05_ACOMPTEF { get; set; }
        public string S05_LIB_TYPE_EVT1 { get; set; }
        public string S05_LIB_TYPE_EVT2 { get; set; }
        public string S05_LIB_TYPE_EVT3 { get; set; }
        public string S05_LIB_TYPE_EVT4 { get; set; }
        public string S05_LIB_TYPE_EVT5 { get; set; }
        public string S05_LIB_TYPE_EVT6 { get; set; }
        public string S05_LIB_TYPE_EVT7 { get; set; }
        public string S05_LIB_TYPE_EVT8 { get; set; }
        public string S05_LIB_TYPE_MAN1 { get; set; }
        public string S05_LIB_TYPE_MAN2 { get; set; }
        public string S05_LIB_TYPE_MAN3 { get; set; }
        public string S05_LIB_TYPE_MAN4 { get; set; }
        public string S05_LIB_TYPE_MAN5 { get; set; }
        public string S05_LIB_TYPE_MAN6 { get; set; }
        public string S05_LIB_TYPE_MAN7 { get; set; }
        public string S05_LIB_TYPE_MAN8 { get; set; }
        public string S05_LIB_TYPE_CTC1 { get; set; }
        public string S05_LIB_TYPE_CTC2 { get; set; }
        public string S05_LIB_TYPE_CTC3 { get; set; }
        public string S05_LIB_TYPE_CTC4 { get; set; }
        public string S05_LIB_TYPE_CTC5 { get; set; }
        public string S05_LIB_TYPE_ORG1 { get; set; }
        public string S05_LIB_TYPE_ORG2 { get; set; }
        public string S05_LIB_TYPE_ORG3 { get; set; }
        public string S05_LIB_TYPE_ORG4 { get; set; }
        public string S05_LIB_TYPE_ORG5 { get; set; }
        public string S05_LIB_TYPE_ORG6 { get; set; }
        public string S05_LIB_TYPE_ORG7 { get; set; }
        public string S05_LIB_TYPE_ORG8 { get; set; }
        public string S05_LIB_TYPE_ORG9 { get; set; }
        public Nullable<int> S05_NB_PLACES { get; set; }
        public Nullable<int> S05_PAX_MANIF { get; set; }
        public Nullable<int> S05_ID_PERE_ORGA_G09 { get; set; }
        public Nullable<int> S05_ID_SITE_M07 { get; set; }
        public string S05_NOM_PERE_ORGA_G09 { get; set; }
        public string S05_NOM_SITE_M07 { get; set; }
        public Nullable<int> S05_ID_MOTIF_ANNULE_M15 { get; set; }
        public string S05_LIBELLE_MOTIF_ANNULE { get; set; }
    }
}
