//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDC_DOSSIER_TEMPLATE_P05
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PDC_DOSSIER_TEMPLATE_P05()
        {
            this.PDC_DOSSIER_TEMPLATE_P051 = new HashSet<PDC_DOSSIER_TEMPLATE_P05>();
            this.PDC_TEMPLATE_P08 = new HashSet<PDC_TEMPLATE_P08>();
        }
    
        public int P05_ID { get; set; }
        public Nullable<int> P05_ID_MERE_P05 { get; set; }
        public Nullable<int> P05_CONTEXTE { get; set; }
        public string P05_NOM { get; set; }
        public Nullable<int> P05_NIVEAU { get; set; }
        public Nullable<int> P05_ORDRE { get; set; }
        public string P05_DESC { get; set; }
        public Nullable<int> P05_ID_ADMIN_A48 { get; set; }
        public Nullable<long> P05_ID_MANIF_M14 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PDC_DOSSIER_TEMPLATE_P05> PDC_DOSSIER_TEMPLATE_P051 { get; set; }
        public virtual PDC_DOSSIER_TEMPLATE_P05 PDC_DOSSIER_TEMPLATE_P052 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PDC_TEMPLATE_P08> PDC_TEMPLATE_P08 { get; set; }
    }
}
