//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDC_TEMPLATE_CTXVALUE_P20
    {
        public int P20_ID { get; set; }
        public string P20_LIBELLE { get; set; }
        public Nullable<int> P20_ID_CONTEXTE_P01 { get; set; }
        public Nullable<long> P20_CONTEXTE_VALUE { get; set; }
        public string P20_TEXT { get; set; }
        public string P20_OBJET { get; set; }
        public Nullable<int> P20_ID_LANG_C40 { get; set; }
        public Nullable<short> P20_TYPE_MAIL { get; set; }
        public Nullable<long> P20_ID_MANIF_M14 { get; set; }
        public Nullable<long> P20_ID_ADMIN_A48 { get; set; }
        public string P20_TEXT_EN { get; set; }
        public string P20_TEXT_AL { get; set; }
        public string P20_TEXT_ES { get; set; }
        public string P20_TEXT_IT { get; set; }
        public string P20_OBJET_EN { get; set; }
        public string P20_OBJET_AL { get; set; }
        public string P20_OBJET_ES { get; set; }
        public string P20_OBJET_IT { get; set; }
        public Nullable<short> P20_TEXTE_BRUT { get; set; }
        public Nullable<short> P20_MAIL_CC { get; set; }
        public Nullable<int> P20_ID_DOSSIER_P05 { get; set; }
        public Nullable<short> P20_SMS { get; set; }
        public Nullable<long> P20_ID_FORM_U28 { get; set; }
        public Nullable<short> P20_MULTILANG { get; set; }
        public Nullable<short> P20_EMBEDEB_CID { get; set; }
        public Nullable<int> P20_ID_FORM_F28 { get; set; }
    }
}
