//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDC_TEMPLATE_LOCAL_P09
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PDC_TEMPLATE_LOCAL_P09()
        {
            this.PDC_TEMPLATE_P08 = new HashSet<PDC_TEMPLATE_P08>();
        }
    
        public int P09_ID { get; set; }
        public string P09_NOM { get; set; }
        public Nullable<int> P09_ORDRE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PDC_TEMPLATE_P08> PDC_TEMPLATE_P08 { get; set; }
    }
}
