//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDC_MAIL_P16
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PDC_MAIL_P16()
        {
            this.PDC_ATTACHEMENTS_P18 = new HashSet<PDC_ATTACHEMENTS_P18>();
            this.PDC_USERS_MAIL_P19 = new HashSet<PDC_USERS_MAIL_P19>();
        }
    
        public int P16_ID { get; set; }
        public int P16_ID_USER_C18 { get; set; }
        public string P16_RECEIVER { get; set; }
        public Nullable<System.DateTime> P16_DATE_ENVOI { get; set; }
        public string P16_MAIL_TITLE { get; set; }
        public string P16_BODY { get; set; }
        public Nullable<short> P16_HAS_ATTACHEMENT { get; set; }
        public Nullable<short> P16_TYPE_MAIL { get; set; }
        public string P16_MSGOUTL { get; set; }
        public Nullable<short> P16_ETAT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PDC_ATTACHEMENTS_P18> PDC_ATTACHEMENTS_P18 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PDC_USERS_MAIL_P19> PDC_USERS_MAIL_P19 { get; set; }
    }
}
