//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDC_USERS_MAIL_P19
    {
        public int P19_ID { get; set; }
        public Nullable<int> P19_MAIL_ID_P16 { get; set; }
        public Nullable<long> P19_ID_CONTACT_G03 { get; set; }
        public Nullable<long> P19_ID_ORGANISME_G09 { get; set; }
    
        public virtual GRC_CONTACTS_G03 GRC_CONTACTS_G03 { get; set; }
        public virtual GRC_ORGANISMES_G09 GRC_ORGANISMES_G09 { get; set; }
        public virtual PDC_MAIL_P16 PDC_MAIL_P16 { get; set; }
    }
}
