//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDC_ATTACHEMENT_P17
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PDC_ATTACHEMENT_P17()
        {
            this.PDC_ATTACHEMENTS_P18 = new HashSet<PDC_ATTACHEMENTS_P18>();
        }
    
        public int P17_ID { get; set; }
        public string P17_TITLE { get; set; }
        public string P17_PATH { get; set; }
        public Nullable<int> P17_FOLDER { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PDC_ATTACHEMENTS_P18> PDC_ATTACHEMENTS_P18 { get; set; }
    }
}
