//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDC_IMPRIMANTES_P21
    {
        public int P21_ID { get; set; }
        public string P21_LIBELLE { get; set; }
        public string P21_PC { get; set; }
        public Nullable<int> P21_ORDRE { get; set; }
    }
}
