//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDC_TYPE_DOCUMENT_P10
    {
        public int P10_ID { get; set; }
        public string P10_NOM { get; set; }
        public Nullable<int> P10_APPLICATION { get; set; }
        public string P10_FORMAT_APP { get; set; }
        public Nullable<int> P10_ORDRE { get; set; }
    }
}
