//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFG_CHAMP_DYNAMIQUE_C54
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CFG_CHAMP_DYNAMIQUE_C54()
        {
            this.CFG_CHAMP_DYNAMIQUE_VALEUR_C53 = new HashSet<CFG_CHAMP_DYNAMIQUE_VALEUR_C53>();
            this.INV_COL_GRDINVITE_I01 = new HashSet<INV_COL_GRDINVITE_I01>();
            this.INV_COL_GRDCTC_I04 = new HashSet<INV_COL_GRDCTC_I04>();
            this.INV_COL_GRDORG_I48 = new HashSet<INV_COL_GRDORG_I48>();
            this.USR_CHAMP_PERSO_U13 = new HashSet<USR_CHAMP_PERSO_U13>();
        }
    
        public int C54_ID { get; set; }
        public Nullable<int> C54_ID_ADMIN_A48 { get; set; }
        public Nullable<int> C54_ID_SOC_C13 { get; set; }
        public string C54_NOM_TABLE { get; set; }
        public string C54_CHAMP { get; set; }
        public string C54_LIBELLE { get; set; }
        public Nullable<short> C54_TYPE { get; set; }
        public Nullable<short> C54_CONTROLE { get; set; }
        public string C54_FORMAT_CHAMP { get; set; }
        public Nullable<short> C54_OBLIGATOIRE { get; set; }
        public Nullable<short> C54_VISIBLE { get; set; }
        public Nullable<short> C54_ORDRE { get; set; }
        public string C54_NOM_TABLE_BY { get; set; }
        public Nullable<long> C54_ID_DS_TABLE_BY { get; set; }
        public Nullable<int> C54_ID_CHAMP_LIE_C54 { get; set; }
        public Nullable<short> C54_ORIENTATION { get; set; }
        public Nullable<short> C54_VISIBLE_FILTRE { get; set; }
        public string C54_VALEUR_CHAMP_LIE { get; set; }
        public string C54_ACTION_1 { get; set; }
        public string C54_ACTION_2 { get; set; }
        public string C54_ACTION_3 { get; set; }
    
        public virtual ADH_EPARTICIPANT_ADMIN_A48 ADH_EPARTICIPANT_ADMIN_A48 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFG_CHAMP_DYNAMIQUE_VALEUR_C53> CFG_CHAMP_DYNAMIQUE_VALEUR_C53 { get; set; }
        public virtual CFG_SOCIETE_C13 CFG_SOCIETE_C13 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_COL_GRDINVITE_I01> INV_COL_GRDINVITE_I01 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_COL_GRDCTC_I04> INV_COL_GRDCTC_I04 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_COL_GRDORG_I48> INV_COL_GRDORG_I48 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USR_CHAMP_PERSO_U13> USR_CHAMP_PERSO_U13 { get; set; }
    }
}
