//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFG_RSX_C42
    {
        public int C42_ID { get; set; }
        public string C42_NOM { get; set; }
        public Nullable<int> C42_ID_LANG_C40 { get; set; }
        public string C42_LANG { get; set; }
        public string C42_TEXT { get; set; }
        public Nullable<long> C42_ID_MANIF_M14 { get; set; }
    }
}
