//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFG_LICENSE_C19
    {
        public int C19_ID { get; set; }
        public string C19_NOM_POSTE { get; set; }
        public string C19_NUM_LICENSE { get; set; }
        public string C19_TIME { get; set; }
        public string C19_TIME2 { get; set; }
        public Nullable<byte> C19_ACTIF { get; set; }
        public Nullable<int> C19_ID_SOC_C13 { get; set; }
    }
}
