//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFG_REQ_SYNCHRO_C47
    {
        public int C47_ID { get; set; }
        public string C47_CONNECTSTRING { get; set; }
        public string C47_NOM_TBL { get; set; }
        public string C47_STRSQL { get; set; }
        public Nullable<System.DateTime> C47_DATE_INSERTION { get; set; }
    }
}
