//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFG_LOG_C26
    {
        public int C26_ID { get; set; }
        public Nullable<int> C26_USER_C18 { get; set; }
        public Nullable<int> C26_TYPE_LOG { get; set; }
        public Nullable<System.DateTime> C26_DATE_LOG { get; set; }
        public string C26_DESC { get; set; }
        public string C26_TRACE { get; set; }
        public string C26_SOURCE { get; set; }
    
        public virtual CFG_UTILISATEURS_C18 CFG_UTILISATEURS_C18 { get; set; }
    }
}
