//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFG_GROUPES_UTILISATEURS_C28
    {
        public int C28_ID { get; set; }
        public string C28_LIBELLE { get; set; }
        public Nullable<int> C28_ORDRE { get; set; }
    }
}
