//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFG_PARAM_A55_C43
    {
        public int C43_ID { get; set; }
        public string C43_NOM_CHAMP { get; set; }
        public string C43_NOM_CTL { get; set; }
        public string C43_LIBELLE { get; set; }
        public string C43_LIBELLE1 { get; set; }
        public Nullable<short> C43_ORDRE { get; set; }
    }
}
