//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFG_LOG_ACTIONS_C34
    {
        public int C34_ID { get; set; }
        public Nullable<int> C34_ID_USER_C18 { get; set; }
        public string C34_NATURE_ACTION { get; set; }
        public string C34_OBJET { get; set; }
        public Nullable<System.DateTime> C34_DATE_ACTION { get; set; }
        public Nullable<long> C34_ID_ORGANISME_G09 { get; set; }
        public Nullable<long> C34_ID_USER_COMMERCIAL_C18 { get; set; }
        public Nullable<long> C34_ID_TYPE_ACTIONS_G11 { get; set; }
        public string C34_NOM_CHAMP { get; set; }
        public string C34_LAST_VALUE { get; set; }
        public string C34_NEW_VALUE { get; set; }
        public Nullable<long> C34_ID_MANIF_M14 { get; set; }
        public Nullable<long> C34_ID_EVENT_M02 { get; set; }
        public Nullable<long> C34_ID_CMD_F04 { get; set; }
        public Nullable<long> C34_ID_DETAIL_CMD_F07 { get; set; }
        public Nullable<int> C34_ID_SOUS_RESA_H02 { get; set; }
    }
}
