//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFG_SEQUENCE_C12
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CFG_SEQUENCE_C12()
        {
            this.STA_BUDGET_USER_S03 = new HashSet<STA_BUDGET_USER_S03>();
            this.STA_BUDGET_SOCIETE_S04 = new HashSet<STA_BUDGET_SOCIETE_S04>();
        }
    
        public int C12_ID { get; set; }
        public string C12_NOM_TABLE { get; set; }
        public Nullable<long> C12_NEXT_VALUE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STA_BUDGET_USER_S03> STA_BUDGET_USER_S03 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STA_BUDGET_SOCIETE_S04> STA_BUDGET_SOCIETE_S04 { get; set; }
    }
}
