//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFG_TBL_SYNCHRO_C46
    {
        public int C46_ID { get; set; }
        public string C46_CODE_TBL { get; set; }
        public string C46_NOM_TBL { get; set; }
        public Nullable<int> C46_ORDRE { get; set; }
        public Nullable<short> C46_SYNCHRO { get; set; }
        public Nullable<short> C46_LONGID { get; set; }
        public Nullable<System.DateTime> C46_DATE_SYNCHRO { get; set; }
    }
}
