//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFG_LOG_FONC_C48
    {
        public int C48_ID { get; set; }
        public Nullable<long> C48_ID_DANS_TBL { get; set; }
        public string C48_NOM_TBL { get; set; }
        public string C48_MODULE_FONC { get; set; }
        public string C48_DESCRIPTION { get; set; }
        public string C48_OBJET { get; set; }
        public Nullable<System.DateTime> C48_DATE_ACTION { get; set; }
        public string C48_LAST_VALUE { get; set; }
        public string C48_NEW_VALUE { get; set; }
        public Nullable<long> C48_ID_MANIF_M14 { get; set; }
        public Nullable<long> C48_ID_ADMIN_A48 { get; set; }
        public Nullable<long> C48_ID_PART_A09 { get; set; }
        public string C48_NOM_CHAMP { get; set; }
        public string C48_INTITULE_CHAMP { get; set; }
        public Nullable<short> C48_TYPE_MODIF { get; set; }
        public Nullable<short> C48_CHAMP_PRIORISE { get; set; }
        public Nullable<short> C48_AJ { get; set; }
    }
}
