//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFG_MENUPARAM_C21
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CFG_MENUPARAM_C21()
        {
            this.CFG_MENUPARAM_COL_C22 = new HashSet<CFG_MENUPARAM_COL_C22>();
            this.USR_PARAM_PACKFILTRE_U12 = new HashSet<USR_PARAM_PACKFILTRE_U12>();
            this.USR_PARAM_PACKFILTRE_U121 = new HashSet<USR_PARAM_PACKFILTRE_U12>();
        }
    
        public int C21_ID { get; set; }
        public Nullable<int> C21_ID_PERE { get; set; }
        public string C21_LIBELLE { get; set; }
        public Nullable<int> C21_NIVEAU { get; set; }
        public Nullable<int> C21_ORDRE { get; set; }
        public string C21_NOM_TBL { get; set; }
        public string C21_COL_ID_TBL { get; set; }
        public string C21_COL_LIBELLE_TBL { get; set; }
        public string C21_COL_ORDRE_TBL { get; set; }
        public string C21_COL_ID_PERE_TBL { get; set; }
        public string C21_COL_NIVEAU_TBL { get; set; }
        public Nullable<int> C21_TYPE_FRM { get; set; }
        public string C21_COL_PARENT { get; set; }
        public Nullable<int> C21_IDMENUPARAM_PARENT { get; set; }
        public string C21_NOM_FRMPERS { get; set; }
        public string C21_NOM_FRMPERS_DETAIL1 { get; set; }
        public string C21_NOM_FRMPERS_DETAIL2 { get; set; }
        public string C21_COL_LIBELLE_TBL1 { get; set; }
        public string C21_COL_LIBELLE_TBL2 { get; set; }
        public string C21_COL_LIBELLE_TBL_TXT { get; set; }
        public string C21_COL_LIBELLE_TBL_FORMAT { get; set; }
        public string C21_COL_LIBELLE_TBL1_FORMAT { get; set; }
        public string C21_COL_LIBELLE_TBL2_FORMAT { get; set; }
        public Nullable<short> C21_DROITS { get; set; }
        public Nullable<short> C21_MULTI_SOCIETE { get; set; }
        public Nullable<short> C21_ACTIF { get; set; }
        public string C21_ICON { get; set; }
        public string C21_LINK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFG_MENUPARAM_COL_C22> CFG_MENUPARAM_COL_C22 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USR_PARAM_PACKFILTRE_U12> USR_PARAM_PACKFILTRE_U12 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USR_PARAM_PACKFILTRE_U12> USR_PARAM_PACKFILTRE_U121 { get; set; }
    }
}
