//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFG_CODE_SEQUENCE_AVANCE_C44
    {
        public int C44_ID { get; set; }
        public int C44_ID_CODE_SEQUENCE_C04 { get; set; }
        public Nullable<System.DateTime> C44_DEBUT_APPLICATION { get; set; }
        public Nullable<System.DateTime> C44_FIN_APPLICATION { get; set; }
        public Nullable<int> C44_PREMIER { get; set; }
        public Nullable<int> C44_DERNIER { get; set; }
        public Nullable<short> C44_CLOS { get; set; }
    }
}
