//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFG_CHAMP_DYNAMIQUE_VALEUR_C53
    {
        public int C53_ID { get; set; }
        public Nullable<int> C53_ID_CHAMP_DYNAMIQUE_C54 { get; set; }
        public Nullable<long> C53_ID_OBJET { get; set; }
        public string C53_NOM_TABLE { get; set; }
        public Nullable<int> C53_VALEUR_ID_C55 { get; set; }
        public Nullable<short> C53_VALEUR_BIN { get; set; }
        public Nullable<int> C53_VALEUR_INT { get; set; }
        public Nullable<decimal> C53_VALEUR_DEC { get; set; }
        public string C53_VALEUR_TEXT { get; set; }
        public Nullable<System.DateTime> C53_VALEUR_DATE { get; set; }
        public string C53_MULTI_TEXT { get; set; }
    
        public virtual CFG_CHAMP_DYNAMIQUE_C54 CFG_CHAMP_DYNAMIQUE_C54 { get; set; }
        public virtual CFG_CHAMP_DYNAMIQUE_CONTENU_C55 CFG_CHAMP_DYNAMIQUE_CONTENU_C55 { get; set; }
    }
}
