//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFG_LABELS_C57
    {
        public int C57_ID { get; set; }
        public string C57_NOM_CHAMP { get; set; }
        public string C57_LIBELLE { get; set; }
        public string C57_NOM_FRM { get; set; }
        public string C57_OBJECT_TABLE { get; set; }
    }
}
