//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFG_PARAM_M60_C41
    {
        public int C41_ID { get; set; }
        public string C41_NOM_CHAMP { get; set; }
        public string C41_NOM_CTL { get; set; }
        public string C41_LIBELLE { get; set; }
        public string C41_LIBELLE1 { get; set; }
        public Nullable<short> C41_ORDRE { get; set; }
        public string C41_NOM_CTL_LIE { get; set; }
    }
}
