//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFG_UTILISATEURS_DROITS_C23
    {
        public int C23_ID { get; set; }
        public string C23_LIBELLE { get; set; }
        public Nullable<int> C23_VALEUR { get; set; }
        public string C23_LIB_PARAM { get; set; }
        public string C23_LIB_CONFIRM { get; set; }
        public string C23_LIB_TARIF { get; set; }
        public string C23_LIB_PUBLI { get; set; }
        public string C23_LIB_EXPORT { get; set; }
    }
}
