//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFG_FORMAT_CALENDRIER_C05
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CFG_FORMAT_CALENDRIER_C05()
        {
            this.TBL_PLAN_SALLE_T03 = new HashSet<TBL_PLAN_SALLE_T03>();
        }
    
        public int C05_ID { get; set; }
        public string C05_LIBELLE { get; set; }
        public Nullable<int> C05_NUMERO_JOUR { get; set; }
        public Nullable<int> C05_COULEUR { get; set; }
        public string C05_POLICE { get; set; }
        public Nullable<int> C05_ORDRE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_PLAN_SALLE_T03> TBL_PLAN_SALLE_T03 { get; set; }
    }
}
