//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFG_STATUT_C14
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CFG_STATUT_C14()
        {
            this.ADH_ACTIONS_AUTO_A02 = new HashSet<ADH_ACTIONS_AUTO_A02>();
            this.GRC_ACTIONS_AUTO_G02 = new HashSet<GRC_ACTIONS_AUTO_G02>();
        }
    
        public int C14_ID { get; set; }
        public string C14_LIBELLE { get; set; }
        public string C14_DESC { get; set; }
        public Nullable<int> C14_ORDRE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADH_ACTIONS_AUTO_A02> ADH_ACTIONS_AUTO_A02 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRC_ACTIONS_AUTO_G02> GRC_ACTIONS_AUTO_G02 { get; set; }
    }
}
