//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFG_PAYS_C10
    {
        public int C10_ID { get; set; }
        public Nullable<int> C10_INDIC { get; set; }
        public string C10_NOM { get; set; }
        public string C10_ISO { get; set; }
        public Nullable<int> C10_ORDRE { get; set; }
    }
}
