//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFG_DROITS_PROFILS_SOCIETE_C50
    {
        public int C50_ID { get; set; }
        public Nullable<int> C50_ID_SOC_C13 { get; set; }
        public Nullable<int> C50_ID_PROFILS_C11 { get; set; }
        public Nullable<short> C50_MODULE_ORGANISMES { get; set; }
        public Nullable<short> C50_MODULE_PLANNING { get; set; }
        public Nullable<short> C50_MODULE_STATISTIQUES { get; set; }
        public Nullable<short> C50_MODULE_FINANCIER { get; set; }
        public Nullable<short> C50_MODULE_DOCUMENT { get; set; }
        public Nullable<short> C50_MODULE_PARAMETRAGE { get; set; }
        public Nullable<short> C50_MODULE_ACTIONS { get; set; }
        public Nullable<short> C50_MODULE_EXPORT { get; set; }
        public Nullable<short> C50_MODULE_RESSOURCE { get; set; }
        public Nullable<short> C50_MODULE_HOTEL { get; set; }
        public Nullable<short> C50_MODULE_PLANNING_CONFIRMATION { get; set; }
        public Nullable<short> C50_MODULE_PARTICIPANTS { get; set; }
        public Nullable<short> C50_DROIT_CONTENTIEUX { get; set; }
        public Nullable<short> C50_FILTRE { get; set; }
        public Nullable<decimal> C50_REMISE_MAX { get; set; }
        public Nullable<short> C50_MODULE_PUBLIPOSTAGE { get; set; }
        public Nullable<short> C50_MODULE_TARIF { get; set; }
        public Nullable<short> C50_MODULE_INDIVIDUELLE { get; set; }
    
        public virtual CFG_PROFILS_C11 CFG_PROFILS_C11 { get; set; }
        public virtual CFG_SOCIETE_C13 CFG_SOCIETE_C13 { get; set; }
    }
}
