//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFG_PARAMETRES_C07
    {
        public int C07_ID { get; set; }
        public Nullable<int> C07_ID_SOC_C13 { get; set; }
        public Nullable<int> C07_COULEUR_CONFIRM { get; set; }
        public Nullable<int> C07_VALEUR_EURO { get; set; }
        public Nullable<int> C07_ACOMPTE { get; set; }
        public Nullable<int> C07_TAUX_TVA { get; set; }
        public Nullable<int> C07_POSITION_MAX { get; set; }
        public Nullable<int> C07_DUREE_REVALIDATION { get; set; }
        public Nullable<int> C07_COULEUR_CONFIRM1 { get; set; }
        public string C07_DOC_PATH_FICHIERS { get; set; }
        public string C07_DOC_PATH_MODELES { get; set; }
        public string C07_DOC_PATH_TMP { get; set; }
        public Nullable<int> C07_TYPE_REVALIDATION { get; set; }
        public Nullable<short> C07_MODE_TOUT_USER { get; set; }
        public Nullable<short> C07_CONTACT_AUTO { get; set; }
        public Nullable<short> C07_CLIENT_NUM_AUTO { get; set; }
        public Nullable<short> C07_MANIFESTATION_NUM_AUTO { get; set; }
        public string C07_INDEFINIE_VALUE { get; set; }
        public Nullable<short> C07_VERROUILLAGE_GLOBAL { get; set; }
        public Nullable<int> C07_ACOMPTE_POURCENT { get; set; }
        public string C07_CLIENT_FINAL { get; set; }
        public string C07_CLIENT { get; set; }
        public string C07_LIBRE_ORG1 { get; set; }
        public string C07_LIBRE_ORG2 { get; set; }
        public string C07_LIBRE_ORG3 { get; set; }
        public string C07_LIBRE_MAN1 { get; set; }
        public string C07_LIBRE_MAN2 { get; set; }
        public string C07_LIBRE_MAN3 { get; set; }
        public string C07_LIBRE_EVT1 { get; set; }
        public string C07_LIBRE_EVT2 { get; set; }
        public string C07_LIBRE_EVT3 { get; set; }
        public Nullable<int> C07_ORDRE { get; set; }
        public Nullable<System.DateTime> C07_HDEBJ { get; set; }
        public Nullable<System.DateTime> C07_HFINJ { get; set; }
        public string C07_DOC_PATH_STORAGE { get; set; }
        public Nullable<int> C07_ID_ADMIN_A48 { get; set; }
    
        public virtual CFG_SOCIETE_C13 CFG_SOCIETE_C13 { get; set; }
    }
}
