//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFG_TYPE_CHAMP_C56
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CFG_TYPE_CHAMP_C56()
        {
            this.MAN_CHAMP_TYPE_M69 = new HashSet<MAN_CHAMP_TYPE_M69>();
        }
    
        public int C56_ID { get; set; }
        public string C56_LIBELLE { get; set; }
        public Nullable<int> C56_ORDRE { get; set; }
        public Nullable<int> C56_VALUE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAN_CHAMP_TYPE_M69> MAN_CHAMP_TYPE_M69 { get; set; }
    }
}
