//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFG_PARAM_DOC_SOC_C52
    {
        public int C52_ID { get; set; }
        public int C52_ID_DOC_C08 { get; set; }
        public int C52_ID_SOC_C13 { get; set; }
        public Nullable<short> C52_NUM_AUTO { get; set; }
        public Nullable<short> C52_VERROUILLAGE { get; set; }
        public Nullable<short> C52_FIN { get; set; }
        public Nullable<short> C52_CA { get; set; }
        public Nullable<short> C52_FICHE { get; set; }
        public Nullable<short> C52_INACTIF { get; set; }
        public Nullable<short> C52_PART { get; set; }
        public Nullable<short> C52_MAN_CLI { get; set; }
        public Nullable<short> C52_HOT { get; set; }
        public Nullable<short> C52_NON_DUPLIQUER { get; set; }
        public Nullable<short> C52_SEMI_VERROUILLAGE { get; set; }
        public Nullable<int> C52_ETAT_VERROUILLAGE { get; set; }
        public Nullable<int> C52_VERROUILLAGE_REGLEMENTS { get; set; }
    }
}
