//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFG_FONCTIONNALITES_C59
    {
        public int C59_ID { get; set; }
        public Nullable<short> C59_ID_APPLICATION_C58 { get; set; }
        public string C59_NOM { get; set; }
        public string C59_DESCRIPTION { get; set; }
    }
}
