//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFG_DROITS_UTILISATEURS_SOCIETE_C33
    {
        public int C33_ID { get; set; }
        public Nullable<short> C33_MODULE_ORGANISMES { get; set; }
        public Nullable<short> C33_MODULE_PLANNING { get; set; }
        public Nullable<short> C33_MODULE_STATISTIQUES { get; set; }
        public Nullable<short> C33_MODULE_FINANCIER { get; set; }
        public Nullable<short> C33_MODULE_DOCUMENT { get; set; }
        public Nullable<short> C33_MODULE_PARAMETRAGE { get; set; }
        public Nullable<short> C33_MODULE_ACTIONS { get; set; }
        public Nullable<short> C33_MODULE_EXPORT { get; set; }
        public Nullable<short> C33_MODULE_RESSOURCE { get; set; }
        public Nullable<short> C33_MODULE_HOTEL { get; set; }
        public Nullable<short> C33_MODULE_PLANNING_CONFIRMATION { get; set; }
        public Nullable<short> C33_MODULE_PARTICIPANTS { get; set; }
        public Nullable<int> C33_ID_SOC_C13 { get; set; }
        public Nullable<int> C33_ID_USER_C18 { get; set; }
        public Nullable<short> C33_MODULE_TARIF { get; set; }
        public Nullable<short> C33_MODULE_PUBLIPOSTAGE { get; set; }
        public Nullable<short> C33_MODULE_INDIVIDUELLE { get; set; }
    
        public virtual CFG_SOCIETE_C13 CFG_SOCIETE_C13 { get; set; }
        public virtual CFG_UTILISATEURS_C18 CFG_UTILISATEURS_C18 { get; set; }
    }
}
