//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFG_PLANNING_OCCUPATION_C27
    {
        public int C27_ID { get; set; }
        public Nullable<short> C27_ORDRE { get; set; }
        public string C27_NOM_CONFIG { get; set; }
        public Nullable<int> C27_LARGEUR { get; set; }
        public Nullable<int> C27_HAUTEUR { get; set; }
        public Nullable<int> C27_LARGEUR_FIXE { get; set; }
        public Nullable<int> C27_HAUTEUR_FIXE { get; set; }
        public string C27_CONTENU { get; set; }
        public string C27_CELL_CONTENT { get; set; }
        public Nullable<int> C27_NUM_TRANCHE_C29 { get; set; }
        public Nullable<short> C27_MODE { get; set; }
        public Nullable<short> C27_BORDURE { get; set; }
        public Nullable<short> C27_DIVISE_CELL { get; set; }
        public Nullable<int> C27_USER_C18 { get; set; }
        public Nullable<short> C27_INV { get; set; }
        public Nullable<short> C27_SAUT { get; set; }
        public Nullable<short> C27_LIEUXPLACE { get; set; }
        public Nullable<short> C27_FUSION { get; set; }
        public Nullable<short> C27_IMGPLA { get; set; }
        public Nullable<short> C27_REPEAT_DATE { get; set; }
        public Nullable<int> C27_FUSION_FORMAT { get; set; }
        public Nullable<short> C27_LINE_MANIF { get; set; }
        public string C27_ORDER_BY { get; set; }
        public string C27_TYPES_EVT { get; set; }
        public Nullable<short> C27_CELL_PAR_EVENT { get; set; }
    
        public virtual CFG_HORAIRE_TRANCHE_C29 CFG_HORAIRE_TRANCHE_C29 { get; set; }
    }
}
