//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFG_SGBD_SYNCH_C45
    {
        public int C45_ID { get; set; }
        public string C45_CODE_SGBD { get; set; }
        public string C45_NOM_SGBD { get; set; }
        public string C45_CONNECTSTRING { get; set; }
        public string C45_CONNECTSTRING_L { get; set; }
        public Nullable<int> C45_ORDRE { get; set; }
        public Nullable<short> C45_SYNCHRO { get; set; }
        public Nullable<System.DateTime> C45_DATE_SYNCHRO { get; set; }
        public Nullable<long> C45_PLAGE_ID { get; set; }
    }
}
