//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFG_PROFILS_C11
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CFG_PROFILS_C11()
        {
            this.CFG_DROIT_TYPE_DOC_FIN_C51 = new HashSet<CFG_DROIT_TYPE_DOC_FIN_C51>();
            this.CFG_DROITS_PROFILS_SOCIETE_C50 = new HashSet<CFG_DROITS_PROFILS_SOCIETE_C50>();
            this.MAN_TYPE_LIEUX_PROFIL_DROIT_M67 = new HashSet<MAN_TYPE_LIEUX_PROFIL_DROIT_M67>();
        }
    
        public int C11_ID { get; set; }
        public string C11_LIBELLE { get; set; }
        public Nullable<int> C11_ORDRE { get; set; }
        public Nullable<short> C11_MODULE_ORGANISMES { get; set; }
        public Nullable<short> C11_MODULE_PLANNING { get; set; }
        public Nullable<short> C11_MODULE_STATISTIQUES { get; set; }
        public Nullable<short> C11_MODULE_FINANCIER { get; set; }
        public Nullable<short> C11_MODULE_DOCUMENT { get; set; }
        public Nullable<short> C11_MODULE_PARAMETRAGE { get; set; }
        public Nullable<short> C11_MODULE_ACTIONS { get; set; }
        public Nullable<short> C11_MODULE_EXPORT { get; set; }
        public Nullable<short> C11_MODULE_RESSOURCE { get; set; }
        public Nullable<short> C11_MODULE_PARTICIPANTS { get; set; }
        public Nullable<short> C11_MODULE_PLANNING_CONFIRMATION { get; set; }
        public Nullable<short> C11_MODULE_HOTELLERIE { get; set; }
        public Nullable<short> C11_MODULE_TARIF { get; set; }
        public Nullable<short> C11_MODULE_PUBLIPOSTAGE { get; set; }
        public Nullable<short> C11_MODULE_INDIVIDUELLE { get; set; }
        public Nullable<short> C11_DROIT_CONTENTIEUX { get; set; }
        public Nullable<short> C11_FILTRE { get; set; }
        public Nullable<decimal> C11_REMISE_MAX { get; set; }
        public Nullable<int> C11_ID_MULTI_SOCIETE_C35 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFG_DROIT_TYPE_DOC_FIN_C51> CFG_DROIT_TYPE_DOC_FIN_C51 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFG_DROITS_PROFILS_SOCIETE_C50> CFG_DROITS_PROFILS_SOCIETE_C50 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAN_TYPE_LIEUX_PROFIL_DROIT_M67> MAN_TYPE_LIEUX_PROFIL_DROIT_M67 { get; set; }
    }
}
