//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIN_PRODUIT_LIEUX_F36
    {
        public int F36_ID { get; set; }
        public Nullable<int> F36_ID_PRODUIT_F13 { get; set; }
        public Nullable<int> F36_ID_LIEUX_M07 { get; set; }
        public Nullable<short> F36_INSERT_COM { get; set; }
    
        public virtual FIN_PRODUITS_F13 FIN_PRODUITS_F13 { get; set; }
        public virtual MAN_LIEUX_M07 MAN_LIEUX_M07 { get; set; }
    }
}
