//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIN_ETAT_F38
    {
        public short F38_ID { get; set; }
        public string F38_LIBELLE { get; set; }
        public string F38_DESC { get; set; }
        public Nullable<short> F38_ORDRE { get; set; }
    }
}
