//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIN_PREFERENCES_CATEGORIES_F61
    {
        public int F61_ID { get; set; }
        public Nullable<int> F61_ID_CATEGORIE_F02 { get; set; }
        public Nullable<int> F61_ID_PREFERENCES_F59 { get; set; }
    
        public virtual FIN_CATEGORIE_PRODUIT_F02 FIN_CATEGORIE_PRODUIT_F02 { get; set; }
        public virtual FIN_PREFERENCES_F59 FIN_PREFERENCES_F59 { get; set; }
    }
}
