//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIN_PRODUIT_GRATUITE_F35
    {
        public int F35_ID { get; set; }
        public Nullable<int> F35_ID_PRODUIT_F13 { get; set; }
        public Nullable<int> F35_QTE_MIN { get; set; }
        public Nullable<int> F35_QTE_MAX { get; set; }
        public Nullable<int> F35_NB_GRATUITE { get; set; }
        public string F35_LIBELLE { get; set; }
    }
}
