//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIN_DEVISE_F08
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FIN_DEVISE_F08()
        {
            this.FIN_COMMANDES_F04 = new HashSet<FIN_COMMANDES_F04>();
        }
    
        public int F08_ID { get; set; }
        public string F08_LIBELLE { get; set; }
        public string F08_SIGLE { get; set; }
        public Nullable<int> F08_PARITE_EURO { get; set; }
        public Nullable<short> F08_IN_USE { get; set; }
        public string F08_DEVISE_ID { get; set; }
        public Nullable<int> F08_ID_DEVISE_REF_F08 { get; set; }
        public Nullable<decimal> F08_PARITE { get; set; }
        public Nullable<short> F08_DEFAUT { get; set; }
        public Nullable<long> F08_ID_MANIF_M14 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FIN_COMMANDES_F04> FIN_COMMANDES_F04 { get; set; }
    }
}
