//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIN_TYPE_TARIF_F19
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FIN_TYPE_TARIF_F19()
        {
            this.FIN_COMMANDES_F04 = new HashSet<FIN_COMMANDES_F04>();
            this.FIN_MONTANT_TT_F10 = new HashSet<FIN_MONTANT_TT_F10>();
            this.FIN_MONTANT_TU_TT_F12 = new HashSet<FIN_MONTANT_TU_TT_F12>();
            this.GRC_ORGANISMES_G09 = new HashSet<GRC_ORGANISMES_G09>();
        }
    
        public int F19_ID { get; set; }
        public string F19_LIBELLE { get; set; }
        public string F19_DESC { get; set; }
        public Nullable<int> F19_REF { get; set; }
        public Nullable<short> F19_ORDRE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FIN_COMMANDES_F04> FIN_COMMANDES_F04 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FIN_MONTANT_TT_F10> FIN_MONTANT_TT_F10 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FIN_MONTANT_TU_TT_F12> FIN_MONTANT_TU_TT_F12 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRC_ORGANISMES_G09> GRC_ORGANISMES_G09 { get; set; }
    }
}
