//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIN_DATE_EXPORT_COMPTA_AUTO_F50
    {
        public int F50_ID { get; set; }
        public int F50_ID_EXP_CPT_AUTO_F49 { get; set; }
        public Nullable<long> F50_ID_COMMANDE_F04 { get; set; }
        public Nullable<System.DateTime> F50_DATE_EXPORT { get; set; }
    
        public virtual FIN_COMMANDES_F04 FIN_COMMANDES_F04 { get; set; }
        public virtual FIN_EXPORT_COMPTA_AUTO_F49 FIN_EXPORT_COMPTA_AUTO_F49 { get; set; }
    }
}
