//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIN_TVA_F17
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FIN_TVA_F17()
        {
            this.FIN_DETAIL_COMPLEXE_F05 = new HashSet<FIN_DETAIL_COMPLEXE_F05>();
            this.FIN_DETAILS_COMMANDES_F07 = new HashSet<FIN_DETAILS_COMMANDES_F07>();
            this.FIN_MONTANT_TT_F10 = new HashSet<FIN_MONTANT_TT_F10>();
            this.FIN_MONTANT_TU_F11 = new HashSet<FIN_MONTANT_TU_F11>();
            this.FIN_MONTANT_TU_TT_F12 = new HashSet<FIN_MONTANT_TU_TT_F12>();
            this.FIN_TVA_VENTILATION_F48 = new HashSet<FIN_TVA_VENTILATION_F48>();
        }
    
        public int F17_ID { get; set; }
        public string F17_LIBELLE { get; set; }
        public Nullable<int> F17_ORDRE { get; set; }
        public Nullable<decimal> F17_TAUX { get; set; }
        public Nullable<short> F17_ACTIF { get; set; }
        public string F17_CODE_COMPTA_F03 { get; set; }
        public Nullable<short> F17_TVASURMARGE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FIN_DETAIL_COMPLEXE_F05> FIN_DETAIL_COMPLEXE_F05 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FIN_DETAILS_COMMANDES_F07> FIN_DETAILS_COMMANDES_F07 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FIN_MONTANT_TT_F10> FIN_MONTANT_TT_F10 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FIN_MONTANT_TU_F11> FIN_MONTANT_TU_F11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FIN_MONTANT_TU_TT_F12> FIN_MONTANT_TU_TT_F12 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FIN_TVA_VENTILATION_F48> FIN_TVA_VENTILATION_F48 { get; set; }
    }
}
