//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIN_TVA_VENTILATION_F48
    {
        public long F48_ID { get; set; }
        public long F48_ID_COMMANDE_F04 { get; set; }
        public int F48_ID_TVA_F17 { get; set; }
        public Nullable<decimal> F48_MONTANT { get; set; }
    
        public virtual FIN_COMMANDES_F04 FIN_COMMANDES_F04 { get; set; }
        public virtual FIN_TVA_F17 FIN_TVA_F17 { get; set; }
    }
}
