//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIN_TYPE_OCCUPATION_F18
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FIN_TYPE_OCCUPATION_F18()
        {
            this.FIN_RESS_OCCUPATION_F15 = new HashSet<FIN_RESS_OCCUPATION_F15>();
        }
    
        public int F18_ID { get; set; }
        public string F18_LIBELLE { get; set; }
        public string F18_DESC { get; set; }
        public Nullable<int> F18_COULEUR { get; set; }
        public Nullable<int> F18_DUREE { get; set; }
        public Nullable<int> F18_UNITE { get; set; }
        public Nullable<int> F18_TYPE_RESSOURCE { get; set; }
        public Nullable<int> F18_ORDRE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FIN_RESS_OCCUPATION_F15> FIN_RESS_OCCUPATION_F15 { get; set; }
    }
}
