//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIN_CATEG_DESC_F32
    {
        public int F32_ID { get; set; }
        public Nullable<int> F32_ID_CATEG_F02 { get; set; }
        public string F32_DESC_HTM { get; set; }
        public string F32_DESC_RTF { get; set; }
        public string F32_DESC { get; set; }
    }
}
