//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIN_DETAILS_COMMANDES_F07
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FIN_DETAILS_COMMANDES_F07()
        {
            this.FIN_DET_COMM_PREFERENCES_F60 = new HashSet<FIN_DET_COMM_PREFERENCES_F60>();
        }
    
        public long F07_ID { get; set; }
        public Nullable<int> F07_ID_CATEGORIE_F02 { get; set; }
        public Nullable<long> F07_ID_COMMANDE_F04 { get; set; }
        public Nullable<int> F07_ID_PRODUIT_F13 { get; set; }
        public Nullable<long> F07_ID_EVT_M02 { get; set; }
        public Nullable<int> F07_ID_LIEUX_M07 { get; set; }
        public Nullable<int> F07_ID_CODE_COMPTABLE_F03 { get; set; }
        public Nullable<long> F07_ID_MANIF_M14 { get; set; }
        public Nullable<int> F07_ID_TU_F20 { get; set; }
        public Nullable<long> F07_ID_FOURNISSEUR { get; set; }
        public Nullable<int> F07_ID_TVA_F17 { get; set; }
        public string F07_PRODUIT_LIBELLE { get; set; }
        public Nullable<int> F07_ORDRE { get; set; }
        public Nullable<decimal> F07_PRIX_DEVISE { get; set; }
        public Nullable<decimal> F07_PRIX_EURO { get; set; }
        public Nullable<decimal> F07_PRIX_DEVISE_TTC { get; set; }
        public Nullable<decimal> F07_PRIX_EURO_TTC { get; set; }
        public Nullable<decimal> F07_QTE { get; set; }
        public Nullable<decimal> F07_COEF { get; set; }
        public Nullable<decimal> F07_REMISE_DEVISE { get; set; }
        public Nullable<decimal> F07_REMISE_EURO { get; set; }
        public Nullable<decimal> F07_REMISE_DEVISE_TTC { get; set; }
        public Nullable<decimal> F07_REMISE_EURO_TTC { get; set; }
        public Nullable<decimal> F07_REMISE_PCT { get; set; }
        public Nullable<decimal> F07_TVA { get; set; }
        public Nullable<decimal> F07_ASSURANCE { get; set; }
        public string F07_REFERENCE { get; set; }
        public string F07_DESC { get; set; }
        public Nullable<System.DateTime> F07_TPS_PREPARATION { get; set; }
        public Nullable<System.DateTime> F07_HEURE_DEBUT { get; set; }
        public Nullable<System.DateTime> F07_HEURE_FIN { get; set; }
        public Nullable<int> F07_TYPE_RESSOURCE { get; set; }
        public string F07_NOTE { get; set; }
        public Nullable<decimal> F07_PRIX_ACHAT_DEVISE { get; set; }
        public Nullable<decimal> F07_PRIX_ACHAT_EURO { get; set; }
        public Nullable<decimal> F07_PRIX_ACHAT_DEVISE_TTC { get; set; }
        public Nullable<decimal> F07_PRIX_ACHAT_EURO_TTC { get; set; }
        public Nullable<decimal> F07_QTE_EFFECTIVE { get; set; }
        public Nullable<short> F07_GESTION_STOCK { get; set; }
        public string F07_LIBRE1 { get; set; }
        public string F07_LIBRE2 { get; set; }
        public string F07_LIBRE3 { get; set; }
        public string F07_LIBRE4 { get; set; }
        public string F07_LIBRE5 { get; set; }
        public Nullable<int> F07_TYPE_DTC1_F21 { get; set; }
        public Nullable<int> F07_TYPE_DTC2_F22 { get; set; }
        public Nullable<int> F07_TYPE_DTC3_F23 { get; set; }
        public Nullable<int> F07_TYPE_DTC4_F24 { get; set; }
        public Nullable<int> F07_TYPE_DTC5_F25 { get; set; }
        public Nullable<short> F07_FLAG_NOT { get; set; }
        public Nullable<long> F07_DETAILS_COMMANDES_F07 { get; set; }
        public Nullable<short> F07_NIVEAU { get; set; }
        public Nullable<short> F07_COMPOSE { get; set; }
        public Nullable<short> F07_OFFRE { get; set; }
        public Nullable<decimal> F07_COEF_MARGE { get; set; }
        public Nullable<short> F07_CHARGE_FIXE { get; set; }
        public Nullable<long> F07_ID_RESERVATION_H01 { get; set; }
        public Nullable<long> F07_ID_SS_RESA_H02 { get; set; }
        public Nullable<short> F07_GRATUITE { get; set; }
        public Nullable<long> F07_ID_DETAIL_ORI_F07 { get; set; }
        public Nullable<decimal> F07_RATIO { get; set; }
        public Nullable<int> F07_ID_INSCR_A07 { get; set; }
        public Nullable<short> F07_SEQUENCE { get; set; }
        public Nullable<short> F07_ENVOYE { get; set; }
        public Nullable<int> F07_ID_TYPE_RESSOURCES_F37 { get; set; }
        public Nullable<short> F07_ID_ETAT_F38 { get; set; }
        public Nullable<int> F07_ID_TVA_ACHAT_F17 { get; set; }
        public Nullable<long> F07_ID_PART_A09 { get; set; }
        public Nullable<int> F07_ID_NUIT_A76 { get; set; }
        public Nullable<int> F07_ID_CENTRE_DE_PROFIT_F51 { get; set; }
        public Nullable<int> F07_ID_UNITE_F31 { get; set; }
        public Nullable<short> F07_PENALITE { get; set; }
        public Nullable<int> F07_ID_CUISSON_F58 { get; set; }
        public Nullable<decimal> F07_MONTANT_TVASURMARGE { get; set; }
        public Nullable<short> F07_IS_TVASURMARGE { get; set; }
        public Nullable<int> F07_ID_CODE_COMPTABLE_ACHAT_F03 { get; set; }
    
        public virtual FIN_CATEGORIE_PRODUIT_F02 FIN_CATEGORIE_PRODUIT_F02 { get; set; }
        public virtual FIN_CENTRE_DE_PROFIT_F51 FIN_CENTRE_DE_PROFIT_F51 { get; set; }
        public virtual FIN_CODE_COMPTABLE_F03 FIN_CODE_COMPTABLE_F03 { get; set; }
        public virtual FIN_COMMANDES_F04 FIN_COMMANDES_F04 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FIN_DET_COMM_PREFERENCES_F60> FIN_DET_COMM_PREFERENCES_F60 { get; set; }
        public virtual FIN_UNITE_F31 FIN_UNITE_F31 { get; set; }
        public virtual FIN_PRODUITS_F13 FIN_PRODUITS_F13 { get; set; }
        public virtual FIN_TVA_F17 FIN_TVA_F17 { get; set; }
        public virtual FIN_TYPE_UNITE_F20 FIN_TYPE_UNITE_F20 { get; set; }
        public virtual FIN_TYPE_DTC1_F21 FIN_TYPE_DTC1_F21 { get; set; }
        public virtual FIN_TYPE_DTC2_F22 FIN_TYPE_DTC2_F22 { get; set; }
        public virtual FIN_TYPE_DTC3_F23 FIN_TYPE_DTC3_F23 { get; set; }
        public virtual FIN_TYPE_DTC4_F24 FIN_TYPE_DTC4_F24 { get; set; }
        public virtual FIN_TYPE_DTC5_F25 FIN_TYPE_DTC5_F25 { get; set; }
        public virtual MAN_EVENEMENTS_M02 MAN_EVENEMENTS_M02 { get; set; }
        public virtual MAN_LIEUX_M07 MAN_LIEUX_M07 { get; set; }
        public virtual MAN_MANIFESTATIONS_M14 MAN_MANIFESTATIONS_M14 { get; set; }
    }
}
