//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIN_SPECTACLE_F40
    {
        public int F40_ID { get; set; }
        public string F40_TEXT_DETAIL_COMMANDE { get; set; }
        public Nullable<int> F40_ID_USER_INIT_C18 { get; set; }
        public Nullable<System.DateTime> F40_DATE_INIT { get; set; }
        public int F40_DETAIL_COMMANDE_F07 { get; set; }
        public Nullable<int> F40_ID_USER_MODIF_C18 { get; set; }
        public Nullable<System.DateTime> F40_DATE_MODIF { get; set; }
    }
}
