//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIN_DETAIL_COMPLEXE_F05
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FIN_DETAIL_COMPLEXE_F05()
        {
            this.FIN_DETAIL_COMPLEXE_TT_F06 = new HashSet<FIN_DETAIL_COMPLEXE_TT_F06>();
        }
    
        public int F05_ID { get; set; }
        public Nullable<int> F05_ID_PRODUIT_F13 { get; set; }
        public Nullable<int> F05_ID_TVA_F17 { get; set; }
        public Nullable<int> F05_IDSEG1 { get; set; }
        public Nullable<int> F05_IDSEG2 { get; set; }
        public Nullable<int> F05_IDSEG3 { get; set; }
        public Nullable<int> F05_IDSEG4 { get; set; }
        public Nullable<decimal> F05_PRIX_DEVISE { get; set; }
        public Nullable<decimal> F05_PRIX_EURO { get; set; }
        public Nullable<decimal> F05_PRIX_DEVISE_TTC { get; set; }
        public Nullable<decimal> F05_PRIX_EURO_TTC { get; set; }
        public Nullable<float> F05_COEF { get; set; }
        public Nullable<int> F05_QTE { get; set; }
        public Nullable<decimal> F05_TVA { get; set; }
        public string F05_LIB_DETAIL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FIN_DETAIL_COMPLEXE_TT_F06> FIN_DETAIL_COMPLEXE_TT_F06 { get; set; }
        public virtual FIN_PRODUITS_F13 FIN_PRODUITS_F13 { get; set; }
        public virtual FIN_TVA_F17 FIN_TVA_F17 { get; set; }
    }
}
