//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIN_MONTANT_TU_F11
    {
        public int F11_ID { get; set; }
        public Nullable<int> F11_ID_TU_F20 { get; set; }
        public Nullable<int> F11_ID_PRODUIT_F13 { get; set; }
        public Nullable<int> F11_ID_TVA_F17 { get; set; }
        public Nullable<decimal> F11_TVA { get; set; }
        public Nullable<decimal> F11_PRIX_DEVISE { get; set; }
        public Nullable<decimal> F11_PRIX_EURO { get; set; }
        public Nullable<decimal> F11_PRIX_DEVISE_TTC { get; set; }
        public Nullable<decimal> F11_PRIX_EURO_TTC { get; set; }
    
        public virtual FIN_PRODUITS_F13 FIN_PRODUITS_F13 { get; set; }
        public virtual FIN_TVA_F17 FIN_TVA_F17 { get; set; }
        public virtual FIN_TYPE_UNITE_F20 FIN_TYPE_UNITE_F20 { get; set; }
    }
}
