//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIN_DECOTE_F56
    {
        public int F56_ID { get; set; }
        public Nullable<int> F56_ID_PRODUIT_F13 { get; set; }
        public Nullable<int> F56_NBPAX { get; set; }
        public Nullable<decimal> F56_REMISE_PCT { get; set; }
    
        public virtual FIN_PRODUITS_F13 FIN_PRODUITS_F13 { get; set; }
    }
}
