//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIN_DETAIL_JNF_F53
    {
        public int F53_ID { get; set; }
        public Nullable<int> F53_ID_DETAIL_F07 { get; set; }
        public Nullable<decimal> F53_NBH_JOUR { get; set; }
        public Nullable<decimal> F53_NBH_NUIT { get; set; }
        public Nullable<decimal> F53_NBH_FERIE { get; set; }
    }
}
