//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIN_PRODUIT_CATEG_FORMULAIRE_F66
    {
        public int F66_ID { get; set; }
        public int F66_ID_F02 { get; set; }
        public int F66_ID_U28 { get; set; }
    }
}
