//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIN_OCCUPATION_LIEUX_F62
    {
        public int F62_ID { get; set; }
        public int F62_ID_LIEU_M07 { get; set; }
        public int F62_ID_OCCUPATION_F15 { get; set; }
    
        public virtual FIN_RESS_OCCUPATION_F15 FIN_RESS_OCCUPATION_F15 { get; set; }
        public virtual MAN_LIEUX_M07 MAN_LIEUX_M07 { get; set; }
    }
}
