//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRC_TYPES_G40
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GRC_TYPES_G40()
        {
            this.GRC_TYPES_G401 = new HashSet<GRC_TYPES_G40>();
        }
    
        public int G40_ID { get; set; }
        public string G40_LIBELLE { get; set; }
        public Nullable<short> G40_ORDRE { get; set; }
        public Nullable<short> G40_NIVEAU { get; set; }
        public Nullable<int> G40_TYPES_G40 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRC_TYPES_G40> GRC_TYPES_G401 { get; set; }
        public virtual GRC_TYPES_G40 GRC_TYPES_G402 { get; set; }
    }
}
