//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRC_DEPARTEMENT_G31
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GRC_DEPARTEMENT_G31()
        {
            this.GRC_COMMUNES_G54 = new HashSet<GRC_COMMUNES_G54>();
            this.GRC_ORGANISMES_G09 = new HashSet<GRC_ORGANISMES_G09>();
        }
    
        public int G31_ID { get; set; }
        public string G31_LIBELLE { get; set; }
        public Nullable<short> G31_ORDRE { get; set; }
        public Nullable<int> G31_REGION_G30 { get; set; }
        public string G31_CODE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRC_COMMUNES_G54> GRC_COMMUNES_G54 { get; set; }
        public virtual GRC_REGION_G30 GRC_REGION_G30 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRC_ORGANISMES_G09> GRC_ORGANISMES_G09 { get; set; }
    }
}
