//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRC_TYPE_TIERS_G16
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GRC_TYPE_TIERS_G16()
        {
            this.GRC_ORGANISMES_G09 = new HashSet<GRC_ORGANISMES_G09>();
            this.GRC_TYPE_ORG5_G17 = new HashSet<GRC_TYPE_ORG5_G17>();
            this.GRC_TYPE_ORG6_G18 = new HashSet<GRC_TYPE_ORG6_G18>();
            this.GRC_TYPE_ORG7_G19 = new HashSet<GRC_TYPE_ORG7_G19>();
            this.GRC_TYPE_ORG8_G20 = new HashSet<GRC_TYPE_ORG8_G20>();
            this.GRC_TYPE_ORG9_G21 = new HashSet<GRC_TYPE_ORG9_G21>();
        }
    
        public int G16_ID { get; set; }
        public string G16_LIBELLE { get; set; }
        public Nullable<short> G16_ORDRE { get; set; }
        public Nullable<int> G16_PRESTA { get; set; }
        public Nullable<int> G16_TYPE_ORG { get; set; }
        public Nullable<short> G16_NON_SELECTIONNABLE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRC_ORGANISMES_G09> GRC_ORGANISMES_G09 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRC_TYPE_ORG5_G17> GRC_TYPE_ORG5_G17 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRC_TYPE_ORG6_G18> GRC_TYPE_ORG6_G18 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRC_TYPE_ORG7_G19> GRC_TYPE_ORG7_G19 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRC_TYPE_ORG8_G20> GRC_TYPE_ORG8_G20 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRC_TYPE_ORG9_G21> GRC_TYPE_ORG9_G21 { get; set; }
    }
}
