//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRC_ADMCTC_G52
    {
        public int G52_ID { get; set; }
        public string G52_LIBELLE { get; set; }
        public long G52_ID_CTC_G03 { get; set; }
        public int G52_ID_ADM_A48 { get; set; }
        public Nullable<int> G52_VALEUR { get; set; }
        public Nullable<int> G52_TYPE_SVE { get; set; }
    }
}
