//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRC_TYPE_ORG1_G12
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GRC_TYPE_ORG1_G12()
        {
            this.ADH_MESSAGE_A62 = new HashSet<ADH_MESSAGE_A62>();
            this.GRC_ORGANISMES_G09 = new HashSet<GRC_ORGANISMES_G09>();
        }
    
        public int G12_ID { get; set; }
        public string G12_LIBELLE { get; set; }
        public Nullable<short> G12_ORDRE { get; set; }
        public Nullable<short> G12_INACTIF { get; set; }
        public Nullable<short> G12_NON_SELECTIONNABLE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADH_MESSAGE_A62> ADH_MESSAGE_A62 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRC_ORGANISMES_G09> GRC_ORGANISMES_G09 { get; set; }
    }
}
