//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRC_CTC_SOC_G43
    {
        public int G43_ID { get; set; }
        public Nullable<long> G43_ID_CTC_G03 { get; set; }
        public Nullable<int> G43_ID_SOC_C13 { get; set; }
    }
}
