//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRC_LISTES_CTC_G46
    {
        public int G46_ID { get; set; }
        public string G46_LIBELLE { get; set; }
        public Nullable<short> G46_STATUT { get; set; }
        public string G46_LIBRE1 { get; set; }
        public Nullable<System.DateTime> G46_DATE_LISTE { get; set; }
        public Nullable<int> G46_ID_MAILING_P06 { get; set; }
        public Nullable<short> G46_UNITAIRE { get; set; }
        public Nullable<int> G46_ID_ADMIN_A48 { get; set; }
    }
}
