//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRC_PRESTA_DROIT_G49
    {
        public int G49_ID { get; set; }
        public string G49_LIBELLE { get; set; }
        public Nullable<decimal> G49_PRIX_HT { get; set; }
        public Nullable<decimal> G49_PRIX_TTC { get; set; }
        public Nullable<int> G49_ID_TVA_F17 { get; set; }
        public Nullable<int> G49_ID_PRODUIT_F13 { get; set; }
    }
}
