//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRC_TYPES_ORG_G28
    {
        public int G28_ID { get; set; }
        public Nullable<long> G28_ORGANISME_G09 { get; set; }
        public Nullable<int> G28_TYPES_G27 { get; set; }
    
        public virtual GRC_ORGANISMES_G09 GRC_ORGANISMES_G09 { get; set; }
        public virtual GRC_TYPES_G27 GRC_TYPES_G27 { get; set; }
    }
}
