//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRC_ACTIONS_AUTO_G02
    {
        public int G02_ID { get; set; }
        public Nullable<int> G02_ID_STATUT_C14 { get; set; }
        public Nullable<int> G02_ORIGINE_G35 { get; set; }
        public Nullable<short> G02_AUTO_AAU { get; set; }
        public string G02_NOTE { get; set; }
        public Nullable<short> G02_DECALAGE_ACTION { get; set; }
        public Nullable<int> G02_ORDRE { get; set; }
        public Nullable<int> G02_TYPE_ACTIONS_G11 { get; set; }
        public string G02_LIBELLE { get; set; }
        public Nullable<short> G02_MAIL_ALL_USER { get; set; }
        public Nullable<short> G02_MAIL_CONTACT { get; set; }
        public Nullable<short> G02_ID_MODELE_ALL_USER_P08 { get; set; }
        public Nullable<short> G02_ID_MODELE_CONTACT_P08 { get; set; }
        public Nullable<short> G02_MAIL_TECH { get; set; }
        public Nullable<short> G02_MAIL_VALIDEUR { get; set; }
        public Nullable<short> G02_WEB { get; set; }
        public Nullable<short> G02_ALERTE { get; set; }
        public Nullable<short> G02_TERMINE { get; set; }
        public Nullable<short> G02_TYPE_DECALAGE { get; set; }
        public Nullable<short> G02_MAIL_LIEU { get; set; }
        public Nullable<short> G02_MAIL_LIEU_LOGISTIC { get; set; }
        public Nullable<short> G02_MAIL_AUTO { get; set; }
        public Nullable<int> G02_ID_SOC_C13 { get; set; }
        public Nullable<short> G02_MAIL_INSTANTANE { get; set; }
        public Nullable<short> G02_LIE_DATE_ECHEANCE { get; set; }
        public Nullable<int> G02_ID_USER_ATTRIBUE_C18 { get; set; }
        public Nullable<short> G02_MAIL_RESERVATAIRE { get; set; }
        public Nullable<short> G02_MAIL_FOURNISSEUR { get; set; }
    
        public virtual CFG_STATUT_C14 CFG_STATUT_C14 { get; set; }
        public virtual GRC_ACTION_ORIGINE_G35 GRC_ACTION_ORIGINE_G35 { get; set; }
        public virtual GRC_TYPE_ACTIONS_G11 GRC_TYPE_ACTIONS_G11 { get; set; }
    }
}
