//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRC_TYPE_ACTIONS_G11
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GRC_TYPE_ACTIONS_G11()
        {
            this.ADH_ACTIONS_AUTO_A02 = new HashSet<ADH_ACTIONS_AUTO_A02>();
            this.GRC_ACTIONS_AUTO_G02 = new HashSet<GRC_ACTIONS_AUTO_G02>();
            this.GRC_ACTIONS_G01 = new HashSet<GRC_ACTIONS_G01>();
        }
    
        public int G11_ID { get; set; }
        public string G11_LIBELLE { get; set; }
        public Nullable<short> G11_ORDRE { get; set; }
        public Nullable<short> G11_NIVEAU { get; set; }
        public Nullable<int> G11_TYPE_ACTIONS_G11 { get; set; }
        public Nullable<int> G11_COULEUR { get; set; }
        public Nullable<int> G11_ID_ADMIN_A48 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADH_ACTIONS_AUTO_A02> ADH_ACTIONS_AUTO_A02 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRC_ACTIONS_AUTO_G02> GRC_ACTIONS_AUTO_G02 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRC_ACTIONS_G01> GRC_ACTIONS_G01 { get; set; }
    }
}
