//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRC_LISTE_CTC_G47
    {
        public int G47_ID { get; set; }
        public Nullable<long> G47_ID_ORG_G09 { get; set; }
        public Nullable<long> G47_ID_CTC_G03 { get; set; }
        public Nullable<int> G47_LISTE_G46 { get; set; }
        public Nullable<short> G47_STATUT { get; set; }
        public Nullable<System.DateTime> G47_DATE_LISTE { get; set; }
        public Nullable<short> G47_UNSUNSCRIBE { get; set; }
    }
}
