//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRC_NIVEAU_G45
    {
        public short G45_ID { get; set; }
        public string G45_LIBELLE { get; set; }
        public Nullable<short> G45_VALEUR { get; set; }
        public Nullable<short> G45_ORDRE { get; set; }
    }
}
