//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRC_INVITATION_G59
    {
        public long G59_ID { get; set; }
        public Nullable<long> G59_ID_ORGANISME_G09 { get; set; }
        public Nullable<int> G59_ID_USER_C18 { get; set; }
        public Nullable<System.DateTime> G59_DATE_INVITATION { get; set; }
        public Nullable<System.DateTime> G59_DATE_DEBUT { get; set; }
        public Nullable<System.DateTime> G59_DATE_FIN { get; set; }
        public Nullable<int> G59_QTE { get; set; }
    
        public virtual CFG_UTILISATEURS_C18 CFG_UTILISATEURS_C18 { get; set; }
        public virtual GRC_ORGANISMES_G09 GRC_ORGANISMES_G09 { get; set; }
    }
}
