//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRC_ORGANISMES_G09
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GRC_ORGANISMES_G09()
        {
            this.FIN_COMMANDES_F04 = new HashSet<FIN_COMMANDES_F04>();
            this.GRC_ACTIONS_G01 = new HashSet<GRC_ACTIONS_G01>();
            this.GRC_CONTACTS_G03 = new HashSet<GRC_CONTACTS_G03>();
            this.GRC_INVITATION_G59 = new HashSet<GRC_INVITATION_G59>();
            this.GRC_LIENS_CTC_ORG_G38 = new HashSet<GRC_LIENS_CTC_ORG_G38>();
            this.GRC_TYPES_ORG_G28 = new HashSet<GRC_TYPES_ORG_G28>();
            this.MAN_LIEUX_M07 = new HashSet<MAN_LIEUX_M07>();
            this.MAN_LIEUX_MANIF_M10 = new HashSet<MAN_LIEUX_MANIF_M10>();
            this.MAN_MANIFESTATIONS_M14 = new HashSet<MAN_MANIFESTATIONS_M14>();
            this.MAN_MANIFESTATIONS_M141 = new HashSet<MAN_MANIFESTATIONS_M14>();
            this.MAN_MANIFESTATIONS_M142 = new HashSet<MAN_MANIFESTATIONS_M14>();
            this.GRC_ORGANISMES_G091 = new HashSet<GRC_ORGANISMES_G09>();
            this.HOT_RESERVATION_H01 = new HashSet<HOT_RESERVATION_H01>();
            this.MAN_LIEUX_ORG_DROIT_M54 = new HashSet<MAN_LIEUX_ORG_DROIT_M54>();
            this.PDC_USERS_MAIL_P19 = new HashSet<PDC_USERS_MAIL_P19>();
            this.PDC_DOCUMENT_P02 = new HashSet<PDC_DOCUMENT_P02>();
            this.TBL_RESERVATION_T04 = new HashSet<TBL_RESERVATION_T04>();
        }
    
        public long G09_ID { get; set; }
        public string G09_NOM_SOCIAL { get; set; }
        public Nullable<long> G09_ID_PERE_G09 { get; set; }
        public Nullable<int> G09_ID_USER_C18 { get; set; }
        public string G09_NOM_USAGE { get; set; }
        public string G09_ADRESSE { get; set; }
        public string G09_CODE_POSTAL { get; set; }
        public string G09_VILLE { get; set; }
        public string G09_PAYS { get; set; }
        public string G09_NOTE { get; set; }
        public string G09_ADRESSE_FACT { get; set; }
        public string G09_CODE_POSTAL_FACT { get; set; }
        public string G09_VILLE_FACT { get; set; }
        public string G09_SITE_INTERNET { get; set; }
        public string G09_EMAIL { get; set; }
        public string G09_TEL { get; set; }
        public string G09_FAX { get; set; }
        public string G09_CODE_CLIENT { get; set; }
        public string G09_TVA_INTRACO { get; set; }
        public Nullable<int> G09_REGLEMENT_F14 { get; set; }
        public string G09_CODE_REGLEMENT { get; set; }
        public string G09_DESC_REGLEMENT { get; set; }
        public string G09_COMMISSION { get; set; }
        public string G09_DOMICILIATION { get; set; }
        public Nullable<int> G09_NIVEAU { get; set; }
        public Nullable<System.DateTime> G09_DATE_CREATION { get; set; }
        public Nullable<System.DateTime> G09_DATE_VERROU { get; set; }
        public Nullable<System.DateTime> G09_DATE_DERN_MODIF { get; set; }
        public Nullable<int> G09_TYPE_PERS { get; set; }
        public string G09_CODE_COMPTABLE { get; set; }
        public Nullable<int> G09_TYPE_ORG1_G12 { get; set; }
        public Nullable<int> G09_TYPE_ORG2_G13 { get; set; }
        public Nullable<int> G09_TYPE_ORG3_G14 { get; set; }
        public Nullable<int> G09_TYPE_ORG4_G15 { get; set; }
        public Nullable<int> G09_TYPE_TIERS_G16 { get; set; }
        public Nullable<int> G09_TYPE_ORG5_G17 { get; set; }
        public Nullable<int> G09_TYPE_ORG6_G18 { get; set; }
        public Nullable<int> G09_TYPE_ORG7_G19 { get; set; }
        public Nullable<int> G09_TYPE_ORG8_G20 { get; set; }
        public Nullable<int> G09_TYPE_ORG9_G21 { get; set; }
        public string G09_LIBRE1 { get; set; }
        public string G09_LIBRE2 { get; set; }
        public string G09_LIBRE3 { get; set; }
        public string G09_LIBRE4 { get; set; }
        public string G09_LIBRE5 { get; set; }
        public string G09_LIBRE6 { get; set; }
        public string G09_LIBRE7 { get; set; }
        public string G09_LIBRE8 { get; set; }
        public Nullable<int> G09_DEPARTEMENT_G31 { get; set; }
        public Nullable<int> G09_REGION_G30 { get; set; }
        public Nullable<int> G09_PAYS_G29 { get; set; }
        public Nullable<short> G09_CHK1 { get; set; }
        public Nullable<short> G09_CHK2 { get; set; }
        public Nullable<short> G09_CHK3 { get; set; }
        public Nullable<int> G09_TYPE_TARIF_F19 { get; set; }
        public Nullable<int> G09_ID_SOC_C13 { get; set; }
        public Nullable<int> G09_TYPE_LIEN_CTC_ORG_G39 { get; set; }
        public Nullable<int> G09_PAYS_FACT_G29 { get; set; }
        public Nullable<int> G09_ID_USER_MODIF_C18 { get; set; }
        public string G09_NOM_USAGE1 { get; set; }
        public string G09_PREFIXE_ADR { get; set; }
        public string G09_COMPLEMENT_ADR { get; set; }
        public string G09_ZIP_CODE_ADR { get; set; }
        public string G09_PREFIXE_ADR_FACT { get; set; }
        public string G09_COMPLEMENT_ADR_FACT { get; set; }
        public string G09_ZIP_CODE_ADR_FACT { get; set; }
        public string G09_LIBRE9 { get; set; }
        public string G09_LIBRE10 { get; set; }
        public string G09_TMP { get; set; }
        public Nullable<System.DateTime> G09_DATE_CLIENT { get; set; }
        public string G09_MARCHAND_ID { get; set; }
        public string G09_MARCHAND_PAYS { get; set; }
        public string G09_MARCHAND_DEVISE { get; set; }
        public Nullable<int> G09_ID_REGION_FACTURATION_G30 { get; set; }
        public Nullable<int> G09_ID_DEPARTEMENT_FACTURATION_G31 { get; set; }
        public Nullable<int> G09_ID_LAST_USER_C18 { get; set; }
        public string G09_PBX_PBX_SITE { get; set; }
        public string G09_PBX_RANG { get; set; }
        public string G09_PBX_IDENTIFIANT { get; set; }
        public string G09_FOOTER_FACT { get; set; }
        public string G09_IMAGE { get; set; }
        public Nullable<int> G09_ID_ADM_A48 { get; set; }
        public Nullable<int> G09_ID_RIVOLI_G53 { get; set; }
        public Nullable<int> G09_NUM_VOIE { get; set; }
        public Nullable<int> G09_ID_RIVOLI_FACT_G53 { get; set; }
        public Nullable<int> G09_NUM_VOIE_FACT { get; set; }
        public Nullable<short> G09_MODE_POL { get; set; }
        public Nullable<long> G09_BANQUE_F45 { get; set; }
        public string G09_SIRET { get; set; }
        public Nullable<short> G09_CONTENTIEUX { get; set; }
        public string G09_APE { get; set; }
        public Nullable<int> G09_APIID { get; set; }
        public string G09_SAP { get; set; }
        public string G09_HEADER_FACT { get; set; }
        public Nullable<int> G09_TAILLE_FOOTER_FACT { get; set; }
        public Nullable<int> G09_TAILLE_HEADER_FACT { get; set; }
        public Nullable<int> G09_MODE_REGLEMENT_G60 { get; set; }
        public string G09_TITULAIRE_COMPTE { get; set; }
        public string G09_IBAN { get; set; }
        public string G09_BIC { get; set; }
        public string G09_LICENCE { get; set; }
        public Nullable<short> G09_CHKCERTIF { get; set; }
        public Nullable<decimal> G09_PCT_COMMISSION { get; set; }
        public string G09_CONTENT_FACT { get; set; }
        public string G09_PP_CLIENTID { get; set; }
        public string G09_PP_CLIENTSECRET { get; set; }
    
        public virtual CFG_SOCIETE_C13 CFG_SOCIETE_C13 { get; set; }
        public virtual CFG_UTILISATEURS_C18 CFG_UTILISATEURS_C18 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FIN_COMMANDES_F04> FIN_COMMANDES_F04 { get; set; }
        public virtual FIN_REGLEMENT_F14 FIN_REGLEMENT_F14 { get; set; }
        public virtual FIN_TYPE_TARIF_F19 FIN_TYPE_TARIF_F19 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRC_ACTIONS_G01> GRC_ACTIONS_G01 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRC_CONTACTS_G03> GRC_CONTACTS_G03 { get; set; }
        public virtual GRC_DEPARTEMENT_G31 GRC_DEPARTEMENT_G31 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRC_INVITATION_G59> GRC_INVITATION_G59 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRC_LIENS_CTC_ORG_G38> GRC_LIENS_CTC_ORG_G38 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRC_TYPES_ORG_G28> GRC_TYPES_ORG_G28 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAN_LIEUX_M07> MAN_LIEUX_M07 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAN_LIEUX_MANIF_M10> MAN_LIEUX_MANIF_M10 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAN_MANIFESTATIONS_M14> MAN_MANIFESTATIONS_M14 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAN_MANIFESTATIONS_M14> MAN_MANIFESTATIONS_M141 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAN_MANIFESTATIONS_M14> MAN_MANIFESTATIONS_M142 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRC_ORGANISMES_G09> GRC_ORGANISMES_G091 { get; set; }
        public virtual GRC_ORGANISMES_G09 GRC_ORGANISMES_G092 { get; set; }
        public virtual GRC_PAYS_G29 GRC_PAYS_G29 { get; set; }
        public virtual GRC_REGION_G30 GRC_REGION_G30 { get; set; }
        public virtual GRC_TYPE_ORG1_G12 GRC_TYPE_ORG1_G12 { get; set; }
        public virtual GRC_TYPE_ORG2_G13 GRC_TYPE_ORG2_G13 { get; set; }
        public virtual GRC_TYPE_ORG3_G14 GRC_TYPE_ORG3_G14 { get; set; }
        public virtual GRC_TYPE_ORG4_G15 GRC_TYPE_ORG4_G15 { get; set; }
        public virtual GRC_TYPE_ORG5_G17 GRC_TYPE_ORG5_G17 { get; set; }
        public virtual GRC_TYPE_ORG6_G18 GRC_TYPE_ORG6_G18 { get; set; }
        public virtual GRC_TYPE_ORG7_G19 GRC_TYPE_ORG7_G19 { get; set; }
        public virtual GRC_TYPE_ORG8_G20 GRC_TYPE_ORG8_G20 { get; set; }
        public virtual GRC_TYPE_ORG9_G21 GRC_TYPE_ORG9_G21 { get; set; }
        public virtual GRC_TYPE_TIERS_G16 GRC_TYPE_TIERS_G16 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOT_RESERVATION_H01> HOT_RESERVATION_H01 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAN_LIEUX_ORG_DROIT_M54> MAN_LIEUX_ORG_DROIT_M54 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PDC_USERS_MAIL_P19> PDC_USERS_MAIL_P19 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PDC_DOCUMENT_P02> PDC_DOCUMENT_P02 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_RESERVATION_T04> TBL_RESERVATION_T04 { get; set; }
    }
}
