//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRC_ACTIONS_G01
    {
        public long G01_ID { get; set; }
        public Nullable<long> G01_ID_CONTACT_G03 { get; set; }
        public Nullable<long> G01_ID_ORGANISME_G09 { get; set; }
        public Nullable<long> G01_ID_MANIF_M14 { get; set; }
        public Nullable<int> G01_ID_USER_C18 { get; set; }
        public Nullable<int> G01_ID_SOC_C13 { get; set; }
        public Nullable<int> G01_ID_USER_ORI_C18 { get; set; }
        public Nullable<int> G01_CODE_ACTION_G11 { get; set; }
        public Nullable<System.DateTime> G01_DATE_POSE { get; set; }
        public Nullable<System.DateTime> G01_DATE_ACTION { get; set; }
        public Nullable<System.DateTime> G01_HEURE_DEBUT { get; set; }
        public Nullable<System.DateTime> G01_HEURE_FIN { get; set; }
        public string G01_NOTE { get; set; }
        public Nullable<short> G01_STATUT { get; set; }
        public Nullable<long> G01_ID_EVENT_M02 { get; set; }
        public Nullable<long> G01_ID_ACTIONS_FIDELITE_G34 { get; set; }
        public Nullable<long> G01_ID_COMMANDE_F04 { get; set; }
        public Nullable<int> G01_ID_DOCUMENT_P02 { get; set; }
        public Nullable<long> G01_ID_SOUS_RESERVATION_H02 { get; set; }
        public Nullable<long> G01_ID_RESERVATION_H01 { get; set; }
        public Nullable<short> G01_ETAT_G44 { get; set; }
        public Nullable<short> G01_NIVEAU_G45 { get; set; }
        public string G01_LIBRE1 { get; set; }
        public string G01_LIBRE2 { get; set; }
        public Nullable<short> G01_ALERT { get; set; }
        public Nullable<int> G01_ID_ACTION_AUTO_G02 { get; set; }
        public Nullable<int> G01_ID_LAST_USER_C18 { get; set; }
        public Nullable<System.DateTime> G01_DATE_VERROU { get; set; }
        public string G01_NOTE_HTM { get; set; }
        public Nullable<int> G01_ID_ADMIN_A48 { get; set; }
        public string G01_SUJET { get; set; }
    
        public virtual CFG_SOCIETE_C13 CFG_SOCIETE_C13 { get; set; }
        public virtual CFG_UTILISATEURS_C18 CFG_UTILISATEURS_C18 { get; set; }
        public virtual CFG_UTILISATEURS_C18 CFG_UTILISATEURS_C181 { get; set; }
        public virtual FIN_COMMANDES_F04 FIN_COMMANDES_F04 { get; set; }
        public virtual GRC_ACTIONS_FIDELITE_G34 GRC_ACTIONS_FIDELITE_G34 { get; set; }
        public virtual GRC_TYPE_ACTIONS_G11 GRC_TYPE_ACTIONS_G11 { get; set; }
        public virtual GRC_CONTACTS_G03 GRC_CONTACTS_G03 { get; set; }
        public virtual GRC_ORGANISMES_G09 GRC_ORGANISMES_G09 { get; set; }
        public virtual MAN_EVENEMENTS_M02 MAN_EVENEMENTS_M02 { get; set; }
        public virtual MAN_MANIFESTATIONS_M14 MAN_MANIFESTATIONS_M14 { get; set; }
    }
}
