//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRC_PRESTA_RGL_G50
    {
        public int G50_ID { get; set; }
        public long G50_ID_CTC_G03 { get; set; }
        public int G50_ID_LIEU_M07 { get; set; }
        public Nullable<int> G50_ID_DROIT_G49 { get; set; }
        public Nullable<System.DateTime> G50_DATE_DEB { get; set; }
        public Nullable<System.DateTime> G50_DATE_FIN { get; set; }
        public Nullable<short> G50_MODE { get; set; }
        public Nullable<short> G50_ACTIF { get; set; }
        public Nullable<long> G50_ID_COMMANDE_F04 { get; set; }
    }
}
