//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADH_PRESTATION_A10
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ADH_PRESTATION_A10()
        {
            this.ADH_ACTIONS_A01 = new HashSet<ADH_ACTIONS_A01>();
            this.ADH_INSCRIPTION_A07 = new HashSet<ADH_INSCRIPTION_A07>();
            this.ADH_PRESTA_PROD_A41 = new HashSet<ADH_PRESTA_PROD_A41>();
            this.ADH_PRESTATION_A101 = new HashSet<ADH_PRESTATION_A10>();
        }
    
        public int A10_ID { get; set; }
        public string A10_LIBELLE { get; set; }
        public Nullable<short> A10_ORDRE { get; set; }
        public Nullable<int> A10_NUMERO_EVENEMENT { get; set; }
        public Nullable<int> A10_NUMERO_MANIFESTATION { get; set; }
        public Nullable<int> A10_NUMERO_CATEGORIE { get; set; }
        public string A10_DESCRIPTION { get; set; }
        public string A10_EMPLACEMENT { get; set; }
        public Nullable<int> A10_RESPONSABLE_A09 { get; set; }
        public Nullable<System.DateTime> A10_DATE_DEBUT { get; set; }
        public Nullable<System.DateTime> A10_DATE_FIN { get; set; }
        public Nullable<System.DateTime> A10_HEURE_DEBUT { get; set; }
        public Nullable<System.DateTime> A10_HEURE_FIN { get; set; }
        public Nullable<decimal> A10_PLACE_DISPO { get; set; }
        public Nullable<int> A10_PLACE_RESTANTE { get; set; }
        public Nullable<int> A10_STATUT_PRESTA_A31 { get; set; }
        public Nullable<decimal> A10_DROIT_INSCRIPTION { get; set; }
        public Nullable<decimal> A10_TAUX_TVA { get; set; }
        public Nullable<float> A10_AHRES { get; set; }
        public Nullable<int> A10_AHRES_PCT { get; set; }
        public Nullable<int> A10_ID_TYPE_PRESTATION { get; set; }
        public Nullable<int> A10_ETOILE { get; set; }
        public Nullable<int> A10_CHAMBRE { get; set; }
        public Nullable<int> A10_ID_CLIENT { get; set; }
        public string A10_NOM_CLIENT { get; set; }
        public string A10_TYPE_H { get; set; }
        public Nullable<decimal> A10_MONTANT { get; set; }
        public string A10_NOM_LIEU { get; set; }
        public string A10_ADRESSE { get; set; }
        public string A10_CP { get; set; }
        public string A10_VILLE { get; set; }
        public Nullable<int> A10_NUMERO_MANIF_IMPORT { get; set; }
        public Nullable<int> A10_TYPE_INSC1_A32 { get; set; }
        public Nullable<int> A10_TYPE_INSC1_A33 { get; set; }
        public Nullable<int> A10_TYPE_INSC1_A34 { get; set; }
        public Nullable<int> A10_TYPE_INSC1_A35 { get; set; }
        public Nullable<int> A10_TYPE_INSC1_A36 { get; set; }
        public string A10_LIB1 { get; set; }
        public string A10_LIB2 { get; set; }
        public string A10_LIB3 { get; set; }
        public string A10_LIB4 { get; set; }
        public string A10_LIB5 { get; set; }
        public Nullable<int> A10_ID_ANIM1 { get; set; }
        public Nullable<int> A10_ID_ANIM2 { get; set; }
        public Nullable<int> A10_TYPE_PRES1_A22 { get; set; }
        public Nullable<int> A10_TYPE_PRES2_A23 { get; set; }
        public Nullable<int> A10_TYPE_PRES3_A24 { get; set; }
        public Nullable<int> A10_TYPE_PRESTA_A25 { get; set; }
        public Nullable<int> A10_PRESTATION_A10 { get; set; }
        public Nullable<int> A10_NIVEAU { get; set; }
        public Nullable<int> A10_PACK_A25 { get; set; }
        public Nullable<short> A10_GRP_COV { get; set; }
        public string A10_NOTE { get; set; }
        public Nullable<short> A10_FLAG_DESIDERATA { get; set; }
        public Nullable<int> A10_TYPE_DESID_A40 { get; set; }
        public Nullable<int> A10_ID_SOC_C13 { get; set; }
        public Nullable<short> A10_PRESTA_GLOBAL { get; set; }
        public Nullable<int> A10_ID_PRODUIT_F13 { get; set; }
        public string A10_TEL { get; set; }
        public string A10_FAX { get; set; }
        public string A10_MAIL { get; set; }
        public Nullable<long> A10_ID_ORG_G09 { get; set; }
        public string A10_REF { get; set; }
        public string A10_IMAGE_URL { get; set; }
        public string A10_IMAGE_STRING { get; set; }
        public string A10_IMAGE_SIZE { get; set; }
        public string A10_IMAGE_EXTENSION { get; set; }
        public Nullable<int> A10_IMAGE_HAUTEUR { get; set; }
        public Nullable<int> A10_VISIBLEWEB { get; set; }
        public Nullable<int> A10_IMAGE_LARGEUR { get; set; }
        public string A10_TEXT_DESC { get; set; }
        public Nullable<short> A10_CATEG { get; set; }
        public Nullable<int> A10_ID_TVA_F17 { get; set; }
        public Nullable<decimal> A10_PRIX_ACHAT_HT { get; set; }
        public Nullable<decimal> A10_PRIX_ACHAT_TTC { get; set; }
        public Nullable<short> A10_OBLIGATOIRE { get; set; }
        public Nullable<short> A10_INSCR_AUTO { get; set; }
        public Nullable<int> A10_ID_LIEU_M07 { get; set; }
        public string A10_IDS_A13_STATUT { get; set; }
        public string A10_LIBELLE_EN { get; set; }
        public string A10_LIBELLE_AL { get; set; }
        public string A10_LIBELLE_ES { get; set; }
        public string A10_LIBELLE_IT { get; set; }
        public Nullable<decimal> A10_MONTANT_HT { get; set; }
        public string A10_DESCRIPTION_EN { get; set; }
        public string A10_DESCRIPTION_AL { get; set; }
        public string A10_DESCRIPTION_ES { get; set; }
        public string A10_DESCRIPTION_IT { get; set; }
        public string A10_TEXT_DESC_EN { get; set; }
        public string A10_TEXT_DESC_AL { get; set; }
        public string A10_TEXT_DESC_ES { get; set; }
        public string A10_TEXT_DESC_IT { get; set; }
        public Nullable<short> A10_TYPE_INV_AUTORISE { get; set; }
        public string A10_TEXT_GRATUITE { get; set; }
        public string A10_TEXT_GRATUITE_EN { get; set; }
        public string A10_TEXT_GRATUITE_ES { get; set; }
        public string A10_TEXT_GRATUITE_AL { get; set; }
        public string A10_TEXT_GRATUITE_IT { get; set; }
        public string A10_TEXT_PLACE_RESTANTE { get; set; }
        public string A10_TEXT_PLACE_RESTANTE_EN { get; set; }
        public string A10_TEXT_PLACE_RESTANTE_ES { get; set; }
        public string A10_TEXT_PLACE_RESTANTE_AL { get; set; }
        public string A10_TEXT_PLACE_RESTANTE_IT { get; set; }
        public Nullable<short> A10_RECCURENT { get; set; }
        public Nullable<short> A10_FORFAIT { get; set; }
        public Nullable<short> A10_MASQUER_DETAIL { get; set; }
        public Nullable<short> A10_FORFAIT_CHOIX_EXCLUSIF { get; set; }
        public Nullable<short> A10_FORFAIT_ELT_OBLIGATOIRE { get; set; }
        public Nullable<short> A10_ARTICLE_ZERO_FACT { get; set; }
        public Nullable<short> A10_EBILLET { get; set; }
        public Nullable<short> A10_NBR_PRESTA_MIN { get; set; }
        public Nullable<int> A10_EBILLET_MODELE_B01 { get; set; }
        public Nullable<short> A10_NOMINATIF { get; set; }
        public Nullable<short> A10_GROUPE { get; set; }
        public Nullable<short> A10_IS_DELAYED { get; set; }
        public Nullable<short> A10_IS_FREE { get; set; }
        public Nullable<short> A10_IS_LIMITED { get; set; }
        public Nullable<short> A10_QUANTITE_MAX { get; set; }
        public Nullable<short> A10_FORCE_VISIBLE { get; set; }
        public Nullable<short> A10_MASQUER_PRIX { get; set; }
        public Nullable<short> A10_USE_PAX { get; set; }
        public Nullable<short> A10_DELAYED { get; set; }
        public Nullable<short> A10_TARIF_HT { get; set; }
        public Nullable<short> A10_NBR_PRESTA_MAX { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADH_ACTIONS_A01> ADH_ACTIONS_A01 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADH_INSCRIPTION_A07> ADH_INSCRIPTION_A07 { get; set; }
        public virtual ADH_PARTICIPANT_A09 ADH_PARTICIPANT_A09 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADH_PRESTA_PROD_A41> ADH_PRESTA_PROD_A41 { get; set; }
        public virtual ADH_TYPE_PRES1_A22 ADH_TYPE_PRES1_A22 { get; set; }
        public virtual ADH_TYPE_PRES2_A23 ADH_TYPE_PRES2_A23 { get; set; }
        public virtual ADH_TYPE_PRES3_A24 ADH_TYPE_PRES3_A24 { get; set; }
        public virtual ADH_TYPE_PRESTA_A25 ADH_TYPE_PRESTA_A25 { get; set; }
        public virtual ADH_TYPE_PRESTA_A25 ADH_TYPE_PRESTA_A251 { get; set; }
        public virtual ADH_TYPE_INSC1_A32 ADH_TYPE_INSC1_A32 { get; set; }
        public virtual ADH_TYPE_INSC2_A33 ADH_TYPE_INSC2_A33 { get; set; }
        public virtual ADH_TYPE_INSC3_A34 ADH_TYPE_INSC3_A34 { get; set; }
        public virtual ADH_TYPE_INSC4_A35 ADH_TYPE_INSC4_A35 { get; set; }
        public virtual ADH_TYPE_INSC5_A36 ADH_TYPE_INSC5_A36 { get; set; }
        public virtual ADH_TYPE_DESID_A40 ADH_TYPE_DESID_A40 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADH_PRESTATION_A10> ADH_PRESTATION_A101 { get; set; }
        public virtual ADH_PRESTATION_A10 ADH_PRESTATION_A102 { get; set; }
        public virtual ADH_STATUT_PRESTA_A31 ADH_STATUT_PRESTA_A31 { get; set; }
        public virtual CFG_SOCIETE_C13 CFG_SOCIETE_C13 { get; set; }
        public virtual MAN_LIEUX_M07 MAN_LIEUX_M07 { get; set; }
    }
}
