//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADH_TACHES_A58
    {
        public int A58_ID { get; set; }
        public Nullable<long> A58_ID_MANIF_M14 { get; set; }
        public Nullable<long> A58_ID_ADM_A48 { get; set; }
        public string A58_LIBELLE { get; set; }
        public Nullable<short> A58_STATUT { get; set; }
        public string A58_NOTE { get; set; }
        public string A58_LIBRE1 { get; set; }
        public Nullable<System.DateTime> A58_DATE_CREATION { get; set; }
        public Nullable<System.DateTime> A58_DATE_ACTION { get; set; }
        public Nullable<short> A58_DECALAGE { get; set; }
    }
}
