//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADH_TITRE_A15
    {
        public int A15_ID { get; set; }
        public string A15_LIBELLE { get; set; }
        public Nullable<short> A15_ORDRE { get; set; }
        public string A15_SIGLE { get; set; }
        public string A15_POLITESSE { get; set; }
    }
}
