//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADH_STATUT_A13
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ADH_STATUT_A13()
        {
            this.ADH_PARTICIPANT_A09 = new HashSet<ADH_PARTICIPANT_A09>();
            this.BIL_BADGE_MODELE_B02 = new HashSet<BIL_BADGE_MODELE_B02>();
            this.INV_REGLES_CATEGORIES_I02 = new HashSet<INV_REGLES_CATEGORIES_I02>();
            this.INV_REGLES_CATEGORIES_I021 = new HashSet<INV_REGLES_CATEGORIES_I02>();
        }
    
        public int A13_ID { get; set; }
        public string A13_LIBELLE { get; set; }
        public Nullable<short> A13_ORDRE { get; set; }
        public string A13_NOTE_STATUT { get; set; }
        public Nullable<long> A13_ID_MANIF_M14 { get; set; }
        public string A13_CODE_COULEUR { get; set; }
        public Nullable<short> A13_VISIBLE { get; set; }
        public Nullable<short> A13_PRIX_MASQUE { get; set; }
        public string A13_LIBELLE_EN { get; set; }
        public string A13_LIBELLE_AL { get; set; }
        public string A13_LIBELLE_IT { get; set; }
        public string A13_LIBELLE_ES { get; set; }
        public string A13_NOTE_STATUT_EN { get; set; }
        public string A13_NOTE_STATUT_AL { get; set; }
        public string A13_NOTE_STATUT_IT { get; set; }
        public string A13_NOTE_STATUT_ES { get; set; }
        public Nullable<int> A13_MAX_INVITE { get; set; }
        public Nullable<short> A13_HEBERGEMENT { get; set; }
        public Nullable<short> A13_PARTAGE { get; set; }
        public string A13_CODE { get; set; }
        public Nullable<short> A13_MASQUE { get; set; }
        public Nullable<short> A13_MASQUE_EBILLET { get; set; }
        public Nullable<short> A13_ACCOMP { get; set; }
        public Nullable<short> A13_MASQUER_INVITANT { get; set; }
        public Nullable<short> A13_GRATUITE { get; set; }
        public Nullable<short> A13_DEFAUT_ACCOMP { get; set; }
        public Nullable<short> A13_EXPOSANT { get; set; }
        public Nullable<int> A13_MAX_INSCRIT { get; set; }
        public Nullable<int> A13_STATUT_ACCOMP { get; set; }
        public Nullable<int> A13_NB_ACCOMP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADH_PARTICIPANT_A09> ADH_PARTICIPANT_A09 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BIL_BADGE_MODELE_B02> BIL_BADGE_MODELE_B02 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_REGLES_CATEGORIES_I02> INV_REGLES_CATEGORIES_I02 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_REGLES_CATEGORIES_I02> INV_REGLES_CATEGORIES_I021 { get; set; }
    }
}
