//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADH_REGISTRE_A46
    {
        public int A46_ID { get; set; }
        public Nullable<short> A46_ARRIVE { get; set; }
        public string A46_LIBELLE { get; set; }
        public Nullable<System.DateTime> A46_DATE_RECEPTION { get; set; }
        public Nullable<System.DateTime> A46_DATE_PRISE_CHARGE { get; set; }
        public string A46_EXPEDITEUR { get; set; }
        public string A46_DESTINATAIRE { get; set; }
        public string A46_SOC_COURSE { get; set; }
        public string A46_NOM_COURSIER { get; set; }
        public string A46_NOM_PRISECHARGE { get; set; }
    }
}
