//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADH_FICHIERS_PARTICIPANT_A99
    {
        public int A99_ID { get; set; }
        public string A99_FILENAME { get; set; }
        public string A99_FILE_BINARY { get; set; }
        public Nullable<int> A99_ID_PARTICIPANT_A09 { get; set; }
        public Nullable<System.DateTime> A99_DATE_UPLOAD { get; set; }
        public string A99_ASSOCIATED_CONTROL { get; set; }
        public string A99_URL { get; set; }
    
        public virtual ADH_PARTICIPANT_A09 ADH_PARTICIPANT_A09 { get; set; }
    }
}
