//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADH_EPARTICIPANT_DROIT_A49
    {
        public int A49_ID { get; set; }
        public string A49_LIBELLE { get; set; }
        public Nullable<decimal> A49_PRIX_HT { get; set; }
        public Nullable<decimal> A49_PRIX_TTC { get; set; }
        public Nullable<int> A49_ID_TVA_F17 { get; set; }
        public Nullable<int> A49_ID_PRODUIT_F13 { get; set; }
        public Nullable<int> A49_NB_INVITE { get; set; }
        public Nullable<int> A49_NB_PART { get; set; }
        public Nullable<int> A49_NB_MAIL { get; set; }
        public Nullable<short> A49_TAILLE_GAL { get; set; }
        public Nullable<short> A49_TROMBI { get; set; }
        public Nullable<short> A49_MUR { get; set; }
        public Nullable<short> A49_GESTABLES { get; set; }
        public Nullable<short> A49_COVOIT { get; set; }
        public Nullable<short> A49_EBILLET { get; set; }
        public Nullable<short> A49_FACT { get; set; }
        public Nullable<short> A49_PAIEMENT_EL { get; set; }
        public Nullable<short> A49_ENQSAT { get; set; }
        public Nullable<short> A49_MULTILANG { get; set; }
        public Nullable<short> A49_GESTABLE { get; set; }
        public string A49_DESCRIPTION { get; set; }
        public Nullable<short> A49_NB_MOIS_ABT { get; set; }
        public string A49_SUFFIXE_PRIX { get; set; }
    }
}
