//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADH_ROOMING_LIST_A97
    {
        public int A97_ID { get; set; }
        public string A97_NOM { get; set; }
        public string A97_PRENOM { get; set; }
        public Nullable<int> A97_ID_NUIT_PART_HOT_A76 { get; set; }
        public Nullable<long> A97_ID_PART_A09 { get; set; }
        public Nullable<short> A97_PERS_SUPPL { get; set; }
    
        public virtual ADH_NUIT_PART_HOT_A76 ADH_NUIT_PART_HOT_A76 { get; set; }
    }
}
