//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADH_LIST_IMPORT_A60
    {
        public int A60_ID { get; set; }
        public string A60_EMAIL { get; set; }
        public string A60_NOM { get; set; }
        public string A60_PRENOM { get; set; }
        public string A60_SOCIETE { get; set; }
        public Nullable<int> A60_ID_A48 { get; set; }
        public string A60_ADRESSE { get; set; }
        public string A60_CP { get; set; }
        public string A60_VILLE { get; set; }
        public string A60_TEL { get; set; }
        public Nullable<int> A60_ID_DPT_G31 { get; set; }
        public Nullable<int> A60_ID_REGION_G30 { get; set; }
        public Nullable<int> A60_ID_CTC_G03 { get; set; }
        public Nullable<System.DateTime> A60_DATE_CREATION { get; set; }
        public Nullable<System.DateTime> A60_DATE_MODIFICATION { get; set; }
    
        public virtual ADH_EPARTICIPANT_ADMIN_A48 ADH_EPARTICIPANT_ADMIN_A48 { get; set; }
    }
}
