//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADH_NUIT_A63
    {
        public int A63_ID { get; set; }
        public long A63_ID_MAN_M14 { get; set; }
        public string A63_LIBELLE { get; set; }
        public System.DateTime A63_DATE_DEB { get; set; }
        public string A63_DESC { get; set; }
        public string A63_IDS_A13_STATUT { get; set; }
    }
}
