//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADH_ALLOTEMENT_PART_A90
    {
        public int A90_ID { get; set; }
        public Nullable<int> A90_ID_NUITEE_A64 { get; set; }
        public Nullable<short> A90_ID_TYPE_CHAMBRE_H45 { get; set; }
        public Nullable<int> A90_QTE { get; set; }
        public Nullable<int> A90_NB_RESTANTES { get; set; }
        public Nullable<decimal> A90_PRIX_HT { get; set; }
        public Nullable<decimal> A90_PRIX_TTC { get; set; }
        public Nullable<short> A90_ID_TVA_F17 { get; set; }
    }
}
