//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADH_PANIER_A61
    {
        public short A61_ID { get; set; }
        public Nullable<long> A61_ID_G03 { get; set; }
        public Nullable<int> A61_ID_M07 { get; set; }
    
        public virtual GRC_CONTACTS_G03 GRC_CONTACTS_G03 { get; set; }
        public virtual MAN_LIEUX_M07 MAN_LIEUX_M07 { get; set; }
    }
}
