//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADH_INTERFACE_GESTION_ACCES_TYPE_LOGIN_A44
    {
        public long A44_ID { get; set; }
        public string A44_CODE_TYPE_LOGIN { get; set; }
        public string A44_LIBELLE { get; set; }
        public Nullable<int> A44_ORDRE { get; set; }
    }
}
