//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADH_INTERFACE_GESTION_ACCES_A42
    {
        public long A42_ID { get; set; }
        public Nullable<int> A42_ID_PARTICIPANT { get; set; }
        public string A42_NOM_PARTICIPANT { get; set; }
        public string A42_PRENOM_PARTICIPANT { get; set; }
        public string A42_NOM_SOCIETE { get; set; }
        public string A42_LOGIN_ID { get; set; }
        public Nullable<int> A42_PINCODE_WITH { get; set; }
        public string A42_PINCODE { get; set; }
        public Nullable<int> A42_ID_LIEUX { get; set; }
        public Nullable<int> A42_LOGIN_TYPE { get; set; }
        public Nullable<System.DateTime> A42_DATE_DEBUT { get; set; }
        public Nullable<System.DateTime> A42_DATE_FIN { get; set; }
    }
}
