//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADH_CATEGORIE_PRODUIT_PARTICIPANT_A03
    {
        public int A03_ID { get; set; }
        public string A03_REFERENCE { get; set; }
        public string A03_NOM_DE_CATEGORIE { get; set; }
        public string A03_DESCRIPTION { get; set; }
        public Nullable<int> A03_CODE_CATEG_MERE { get; set; }
        public Nullable<short> A03_ORDRECHAMP { get; set; }
        public Nullable<int> A03_NIVEAU { get; set; }
        public Nullable<int> A03_CODE_CATEG_ORIGINE { get; set; }
    }
}
