//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADH_TYPE_PART_A88
    {
        public int A88_ID { get; set; }
        public string A88_LIBELLE { get; set; }
        public Nullable<short> A88_ORDRE { get; set; }
        public Nullable<long> A88_ID_MANIF_M14 { get; set; }
        public string A88_LIBELLE_EN { get; set; }
        public string A88_LIBELLE_ES { get; set; }
        public string A88_LIBELLE_AL { get; set; }
        public string A88_LIBELLE_IT { get; set; }
    }
}
