//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADH_EVENT_DROIT_A56
    {
        public int A56_ID { get; set; }
        public string A56_LIBELLE { get; set; }
        public Nullable<long> A56_ID_MANIF_M14 { get; set; }
        public long A56_ID_DROIT_A49 { get; set; }
        public Nullable<System.DateTime> A56_DATE_DEB { get; set; }
        public Nullable<System.DateTime> A56_DATE_FIN { get; set; }
        public Nullable<short> A56_MODE { get; set; }
        public Nullable<long> A56_ID_COMMANDE_F04 { get; set; }
        public Nullable<long> A56_ID_ADMIN_A48 { get; set; }
        public Nullable<short> A56_ACTIF { get; set; }
        public Nullable<int> A56_NB_INVITE { get; set; }
        public Nullable<int> A56_NB_PART { get; set; }
        public Nullable<int> A56_NB_MAIL { get; set; }
        public Nullable<short> A56_TAILLE_GAL { get; set; }
        public Nullable<short> A56_TROMBI { get; set; }
        public Nullable<short> A56_MUR { get; set; }
        public Nullable<short> A56_GESTABLES { get; set; }
        public Nullable<short> A56_COVOIT { get; set; }
        public Nullable<short> A56_EBILLET { get; set; }
        public Nullable<short> A56_FACT { get; set; }
        public Nullable<short> A56_PAIEMENT_EL { get; set; }
        public Nullable<short> A56_ENQSAT { get; set; }
        public Nullable<short> A56_MULTILANG { get; set; }
        public Nullable<short> A56_GESTABLE { get; set; }
        public Nullable<short> A56_CONTACTS { get; set; }
        public Nullable<short> A56_PROFILS_CTC { get; set; }
    }
}
