//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADH_ACTIONS_A01
    {
        public int A01_ID { get; set; }
        public Nullable<int> A01_PARTICIPANT_A09 { get; set; }
        public Nullable<int> A01_USER_C18 { get; set; }
        public string A01_NOTE { get; set; }
        public Nullable<System.DateTime> A01_DATE_ACTION { get; set; }
        public Nullable<long> A01_ID_MANIF_M14 { get; set; }
        public Nullable<System.DateTime> A01_HEURE_DEBUT { get; set; }
        public Nullable<System.DateTime> A01_HEURE_FIN { get; set; }
        public Nullable<int> A01_IDSOC { get; set; }
        public Nullable<int> A01_INSCRIPTION_A07 { get; set; }
        public Nullable<int> A01_PRESTATION_A10 { get; set; }
        public Nullable<int> A01_TYPE_ACTION_A17 { get; set; }
        public Nullable<System.DateTime> A01_DATE_POSE { get; set; }
        public Nullable<short> A01_STATUT { get; set; }
    
        public virtual ADH_INSCRIPTION_A07 ADH_INSCRIPTION_A07 { get; set; }
        public virtual ADH_PARTICIPANT_A09 ADH_PARTICIPANT_A09 { get; set; }
        public virtual ADH_PRESTATION_A10 ADH_PRESTATION_A10 { get; set; }
        public virtual ADH_TYPE_ACTION_A17 ADH_TYPE_ACTION_A17 { get; set; }
        public virtual MAN_MANIFESTATIONS_M14 MAN_MANIFESTATIONS_M14 { get; set; }
    }
}
