//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADH_TYPE_PRESTA_A25
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ADH_TYPE_PRESTA_A25()
        {
            this.ADH_PARTICIPANT_A09 = new HashSet<ADH_PARTICIPANT_A09>();
            this.ADH_PRESTATION_A10 = new HashSet<ADH_PRESTATION_A10>();
            this.ADH_PRESTATION_A101 = new HashSet<ADH_PRESTATION_A10>();
        }
    
        public int A25_ID { get; set; }
        public string A25_LIBELLE { get; set; }
        public Nullable<short> A25_ORDRE { get; set; }
        public string A25_NOTE { get; set; }
        public Nullable<int> A25_ID_EVENT { get; set; }
        public Nullable<int> A25_ID_MANIF { get; set; }
        public Nullable<short> A25_PACK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADH_PARTICIPANT_A09> ADH_PARTICIPANT_A09 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADH_PRESTATION_A10> ADH_PRESTATION_A10 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADH_PRESTATION_A10> ADH_PRESTATION_A101 { get; set; }
    }
}
