//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADH_EPARTICIPANT_CSS_PARAM_A52
    {
        public int A52_ID { get; set; }
        public Nullable<int> A52_ID_CSS_A51 { get; set; }
        public string A52_LIBELLE { get; set; }
        public string A52_CHAMP { get; set; }
        public string A52_VALEUR { get; set; }
        public Nullable<int> A52_ID_TYPE_A53 { get; set; }
        public Nullable<int> A52_ORDRE { get; set; }
        public Nullable<int> A52_REF { get; set; }
    }
}
