//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADH_NUIT_PART_HOT_A76
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ADH_NUIT_PART_HOT_A76()
        {
            this.ADH_PARTAGE_HEB_A96 = new HashSet<ADH_PARTAGE_HEB_A96>();
            this.ADH_ROOMING_LIST_A97 = new HashSet<ADH_ROOMING_LIST_A97>();
            this.INV_TRANSFERT_I15 = new HashSet<INV_TRANSFERT_I15>();
            this.INV_NOTIFICATION_I28 = new HashSet<INV_NOTIFICATION_I28>();
        }
    
        public int A76_ID { get; set; }
        public int A76_ID_NUIT_A63 { get; set; }
        public int A76_ID_HOT_H44 { get; set; }
        public long A76_ID_MAN_M14 { get; set; }
        public long A76_ID_PART_A09 { get; set; }
        public Nullable<short> A76_NB_CH { get; set; }
        public Nullable<short> A76_TYPE_CH_H22 { get; set; }
        public string A76_DEMANDE_PART { get; set; }
        public Nullable<long> A76_ID_ALLOTEMENT_A90 { get; set; }
        public Nullable<short> A76_STATUT_H42 { get; set; }
        public Nullable<int> A76_NB_PERSONNES { get; set; }
        public Nullable<long> A76_ID_PART1_A09 { get; set; }
        public string A76_NOM_PART1 { get; set; }
        public Nullable<System.DateTime> A76_DATE_RESA { get; set; }
        public Nullable<int> A76_NB_PETIT_DEJ { get; set; }
        public Nullable<short> A76_STATUT_PARTAGE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADH_PARTAGE_HEB_A96> ADH_PARTAGE_HEB_A96 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADH_ROOMING_LIST_A97> ADH_ROOMING_LIST_A97 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_TRANSFERT_I15> INV_TRANSFERT_I15 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_NOTIFICATION_I28> INV_NOTIFICATION_I28 { get; set; }
    }
}
