//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADH_EPART_ADMPART_A57
    {
        public int A57_ID { get; set; }
        public string A57_LIBELLE { get; set; }
        public long A57_ID_PART_A09 { get; set; }
        public int A57_ID_ADM_A48 { get; set; }
        public Nullable<int> A57_VALEUR { get; set; }
        public Nullable<int> A57_TYPE_SVE { get; set; }
    }
}
