//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADH_EPARTICIPANT_CONFIG_PAGES_A54
    {
        public int A54_ID { get; set; }
        public string A54_LIBELLE { get; set; }
        public Nullable<short> A54_INSCR { get; set; }
        public Nullable<short> A54_RECAP { get; set; }
        public Nullable<short> A54_PAIEMENT { get; set; }
        public Nullable<short> A54_CUSTOM1 { get; set; }
        public string A54_LIB_CUSTOM1 { get; set; }
        public Nullable<short> A54_CUSTOM2 { get; set; }
        public string A54_LIB_CUSTOM2 { get; set; }
        public Nullable<short> A54_CUSTOM3 { get; set; }
        public string A54_LIB_CUSTOM3 { get; set; }
        public string A54_TEXT_CUSTOM1 { get; set; }
        public string A54_TEXT_CUSTOM2 { get; set; }
        public string A54_TEXT_CUSTOM3 { get; set; }
        public string A54_RECAP_TEXTE { get; set; }
        public string A54_LIB_CUSTOM1_EN { get; set; }
        public string A54_LIB_CUSTOM1_AL { get; set; }
        public string A54_LIB_CUSTOM1_ES { get; set; }
        public string A54_LIB_CUSTOM1_IT { get; set; }
        public string A54_LIB_CUSTOM2_EN { get; set; }
        public string A54_LIB_CUSTOM2_AL { get; set; }
        public string A54_LIB_CUSTOM2_ES { get; set; }
        public string A54_LIB_CUSTOM2_IT { get; set; }
        public string A54_LIB_CUSTOM3_EN { get; set; }
        public string A54_LIB_CUSTOM3_AL { get; set; }
        public string A54_LIB_CUSTOM3_ES { get; set; }
        public string A54_LIB_CUSTOM3_IT { get; set; }
        public string A54_TEXT_CUSTOM1_EN { get; set; }
        public string A54_TEXT_CUSTOM1_AL { get; set; }
        public string A54_TEXT_CUSTOM1_ES { get; set; }
        public string A54_TEXT_CUSTOM1_IT { get; set; }
        public string A54_TEXT_CUSTOM2_EN { get; set; }
        public string A54_TEXT_CUSTOM2_AL { get; set; }
        public string A54_TEXT_CUSTOM2_ES { get; set; }
        public string A54_TEXT_CUSTOM2_IT { get; set; }
        public string A54_TEXT_CUSTOM3_EN { get; set; }
        public string A54_TEXT_CUSTOM3_AL { get; set; }
        public string A54_TEXT_CUSTOM3_ES { get; set; }
        public string A54_TEXT_CUSTOM3_IT { get; set; }
        public string A54_LIBELLE_EN { get; set; }
        public string A54_LIBELLE_AL { get; set; }
        public string A54_LIBELLE_ES { get; set; }
        public string A54_LIBELLE_IT { get; set; }
        public string A54_RECAP_TEXTE_EN { get; set; }
        public string A54_RECAP_TEXTE_AL { get; set; }
        public string A54_RECAP_TEXTE_ES { get; set; }
        public string A54_RECAP_TEXTE_IT { get; set; }
    }
}
