//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADH_PARAM_INSCR_A79
    {
        public int A79_ID { get; set; }
        public long A79_ID_MAN_M14 { get; set; }
        public Nullable<short> A79_ASSISTE { get; set; }
        public string A79_IDS_STATUT_ASS { get; set; }
        public Nullable<short> A79_COORDONEE { get; set; }
        public string A79_IDS_STATUT_COO { get; set; }
        public Nullable<short> A79_HEBERG { get; set; }
        public string A79_IDS_STATUT_HEB { get; set; }
        public Nullable<short> A79_TRANSPORT { get; set; }
        public string A79_IDS_STATUT_TRA { get; set; }
        public Nullable<short> A79_PRESTA { get; set; }
        public string A79_IDS_STATUT_PRE { get; set; }
    }
}
