//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADH_EPARTICIPANT_ACCUEIL_A50
    {
        public int A50_ID { get; set; }
        public string A50_TITRE { get; set; }
        public string A50_LOGO { get; set; }
        public string A50_DESCRIPTION { get; set; }
        public Nullable<int> A50_ID_CSS_A51 { get; set; }
        public Nullable<int> A50_ID_MANIF_M14 { get; set; }
        public Nullable<int> A50_LANGUE_C40 { get; set; }
        public int A50_RECUP_MDP { get; set; }
        public int A50_INSCRIPTION { get; set; }
        public Nullable<int> A50_CONFIG_PAGES_A54 { get; set; }
        public Nullable<short> A50_ETAT_SITE { get; set; }
        public Nullable<short> A50_FB_ACTIVE { get; set; }
        public string A50_COULEUR_TITRE { get; set; }
        public Nullable<short> A50_FICHE_LIEU { get; set; }
        public Nullable<short> A50_PG { get; set; }
        public Nullable<short> A50_COORDONEE { get; set; }
        public Nullable<short> A50_MONCOMPTE { get; set; }
        public string A50_DOMAINE { get; set; }
        public string A50_FOOTER { get; set; }
        public Nullable<short> A50_NB_ACCOMP { get; set; }
        public Nullable<short> A50_TROMBI { get; set; }
        public Nullable<short> A50_SOUSINSCR { get; set; }
        public Nullable<short> A50_GALERIE { get; set; }
        public string A50_ID_GOOGLE_AN { get; set; }
        public string A50_DESCRIPTION_EN { get; set; }
        public string A50_DESCRIPTION_AL { get; set; }
        public string A50_DESCRIPTION_ES { get; set; }
        public string A50_DESCRIPTION_IT { get; set; }
        public string A50_FOOTER_EN { get; set; }
        public string A50_FOOTER_AL { get; set; }
        public string A50_FOOTER_ES { get; set; }
        public string A50_FOOTER_IT { get; set; }
        public string A50_TITRE_EN { get; set; }
        public string A50_TITRE_AL { get; set; }
        public string A50_TITRE_ES { get; set; }
        public string A50_TITRE_IT { get; set; }
        public string A50_DESCRIPTIF_EN { get; set; }
        public string A50_DESCRIPTIF_AL { get; set; }
        public string A50_DESCRIPTIF_ES { get; set; }
        public string A50_DESCRIPTIF_IT { get; set; }
        public Nullable<short> A50_FACT { get; set; }
        public Nullable<short> A50_EBILLET { get; set; }
        public Nullable<short> A50_MUR { get; set; }
        public Nullable<int> A50_DEFAUT_A13 { get; set; }
        public Nullable<int> A50_MULTILANG { get; set; }
        public Nullable<short> A50_POL_ACTIV { get; set; }
        public Nullable<short> A50_HEBERGEMENT { get; set; }
        public Nullable<short> A50_IS_DOMAIN_FULL { get; set; }
        public string A50_HMAIL_ADDRESS { get; set; }
        public Nullable<int> A50_HMAIL_ID { get; set; }
        public Nullable<short> A50_DIRECTION_MENU { get; set; }
        public string A50_CGV { get; set; }
        public Nullable<short> A50_MAIL_CONFIRM { get; set; }
        public Nullable<short> A50_ETAPE_HEBERGEMENT { get; set; }
        public Nullable<short> A50_ETAPE_TRANSPORT { get; set; }
        public Nullable<short> A50_ETAPE_PRESTATION { get; set; }
        public Nullable<short> A50_ETAPE_PAIEMENT { get; set; }
        public Nullable<short> A50_ETAPE_ACCOMPGNANTS { get; set; }
        public string A50_NOM { get; set; }
        public string A50_PRENOM { get; set; }
        public string A50_DOMAINE_MAIL { get; set; }
        public Nullable<short> A50_ECRASE_MAIL_INSCRIPTION { get; set; }
        public string A50_DESCRIPTIF { get; set; }
        public Nullable<short> A50_RAZ_COOKIE_INSCRIPTION { get; set; }
        public Nullable<short> A50_USE_STYLE_STR { get; set; }
        public string A50_STYLE { get; set; }
        public Nullable<short> A50_JESAISPAS { get; set; }
        public string A50_TEXTINSCR { get; set; }
        public string A50_TEXTINSCR_EN { get; set; }
        public string A50_TEXTINSCR_AL { get; set; }
        public string A50_TEXTINSCR_ES { get; set; }
        public string A50_TEXTINSCR_IT { get; set; }
        public Nullable<short> A50_RECAP_AVANCE { get; set; }
        public Nullable<short> A50_HISTO { get; set; }
        public Nullable<short> A50_NOTIFICATIONS { get; set; }
        public string A50_RECAP_SIDE_FR { get; set; }
        public string A50_RECAP_SIDE_EN { get; set; }
        public string A50_RECAP_SIDE_AL { get; set; }
        public string A50_RECAP_SIDE_ES { get; set; }
        public Nullable<int> A50_SOCIAL { get; set; }
        public Nullable<short> A50_INSCRIPTION_AUTORISE { get; set; }
        public string A50_LANGUE_FORCEE { get; set; }
        public Nullable<short> A50_FR { get; set; }
        public Nullable<short> A50_EN { get; set; }
        public Nullable<short> A50_ES { get; set; }
        public Nullable<short> A50_AL { get; set; }
        public Nullable<short> A50_IT { get; set; }
        public Nullable<short> A50_CHOIX_CATEGORIES { get; set; }
        public Nullable<short> A50_USE_VERROUILLAGE { get; set; }
        public string A50_TEXTE_VERROUILLAGE { get; set; }
        public string A50_TEXTE_VERROUILLAGE_EN { get; set; }
        public string A50_TEXTE_VERROUILLAGE_AL { get; set; }
        public string A50_TEXTE_VERROUILLAGE_ES { get; set; }
        public string A50_TEXTE_VERROUILLAGE_IT { get; set; }
        public Nullable<short> A50_QUESTION { get; set; }
        public Nullable<short> A50_TRANSFERT { get; set; }
        public Nullable<short> A50_FACT_INVITANT { get; set; }
        public Nullable<short> A50_RECURRENCE { get; set; }
        public Nullable<short> A50_ALERTE_FORMULAIRE_ACTIVEE { get; set; }
        public Nullable<short> A50_RECAP_CHAMPTEXT { get; set; }
        public string A50_CGV_EN { get; set; }
        public string A50_CGV_AL { get; set; }
        public string A50_CGV_ES { get; set; }
        public string A50_CGV_IT { get; set; }
        public string A50_SENDGRID_USER { get; set; }
        public string A50_SENDGRID_PASSWORD { get; set; }
        public string A50_EMAILS_NOTIFICATION { get; set; }
        public string A50_HEADER_HTML { get; set; }
        public string A50_HEADER_HTML_EN { get; set; }
        public string A50_HEADER_HTML_AL { get; set; }
        public string A50_HEADER_HTML_ES { get; set; }
        public string A50_HEADER_HTML_IT { get; set; }
        public Nullable<short> A50_ALLOW_MULTIPLE_EMAILS { get; set; }
        public Nullable<short> A50_HIDDEN_TITLE { get; set; }
        public Nullable<int> A50_MAX_INVITE { get; set; }
        public Nullable<int> A50_PROTEGER_MDP { get; set; }
        public string A50_MDP { get; set; }
        public Nullable<short> A50_TRANSPORT { get; set; }
        public Nullable<short> A50_BUDGET { get; set; }
        public Nullable<short> A50_INVITANT_DEFAUT { get; set; }
        public Nullable<short> A50_CONF_SIGNAL_PAYMENT { get; set; }
        public Nullable<short> A50_IMPORT_INVITANT { get; set; }
        public Nullable<short> A50_PRESTASIMPLE { get; set; }
        public string A50_TEXTFERMETURE { get; set; }
        public string A50_TEXTFERMETURE_EN { get; set; }
        public string A50_TEXTFERMETURE_AL { get; set; }
        public string A50_TEXTFERMETURE_ES { get; set; }
        public string A50_TEXTFERMETURE_IT { get; set; }
        public Nullable<short> A50_USE_CALENDAR_LINK { get; set; }
        public Nullable<short> A50_MASQUER_LOGIN { get; set; }
        public Nullable<short> A50_CUSTOM_JAVASCRIPT_ENABLED { get; set; }
        public string A50_CUSTOM_JAVASCRIPT_CONTENT { get; set; }
        public Nullable<short> A50_FREE_PRESTA_IN_FACT_ENABLED { get; set; }
        public Nullable<short> A50_DISABLE_TUTORIAL { get; set; }
        public Nullable<short> A50_ENQUETE_ANONYME { get; set; }
        public Nullable<int> A50_ID_FORM_U28 { get; set; }
        public string A50_FORMAT_DEVISE { get; set; }
        public Nullable<short> A50_RECAP_BTN_NEWINSCR { get; set; }
        public string A50_SMS_SENDER { get; set; }
        public Nullable<short> A50_MAIL_CONFIRM_REFUS { get; set; }
        public Nullable<int> A50_TYPE_DOCUMENT_C08 { get; set; }
        public string A50_HEADER_BANNIERE { get; set; }
        public Nullable<short> A50_NEWFORM { get; set; }
        public Nullable<short> A50_MAIL_MODIF { get; set; }
        public Nullable<short> A50_MODULE_RDV { get; set; }
        public Nullable<short> A50_PRESTA_FAMILLE_COLLAPSE { get; set; }
        public Nullable<short> A50_NEW_DESIGN_FORMULAIRE { get; set; }
        public Nullable<short> A50_MASQUER_FORM_ABS { get; set; }
        public Nullable<short> A50_MAIL_CONF_ACCOMP { get; set; }
        public Nullable<short> A50_MASQUER_FORM_REFUS_ABS { get; set; }
        public Nullable<short> A50_WIZNAVPOS { get; set; }
    
        public virtual USR_FORMULAIRE_U28 USR_FORMULAIRE_U28 { get; set; }
    }
}
