//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADH_TYPE_PART_A85
    {
        public int A85_ID { get; set; }
        public string A85_LIBELLE { get; set; }
        public Nullable<short> A85_ORDRE { get; set; }
        public Nullable<long> A85_ID_MANIF_M14 { get; set; }
        public string A85_LIBELLE_EN { get; set; }
        public string A85_LIBELLE_ES { get; set; }
        public string A85_LIBELLE_AL { get; set; }
        public string A85_LIBELLE_IT { get; set; }
    }
}
