//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADH_NUIT_HOT_A64
    {
        public int A64_ID { get; set; }
        public int A64_ID_NUIT_A63 { get; set; }
        public int A64_ID_HOT_H44 { get; set; }
        public long A64_ID_MAN_M14 { get; set; }
        public Nullable<short> A64_NB_CH { get; set; }
        public Nullable<short> A64_NUM_CH_BY_HOT { get; set; }
        public string A64_NUM_CH { get; set; }
    }
}
