//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADH_TYPE_INSC4_A35
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ADH_TYPE_INSC4_A35()
        {
            this.ADH_INSCRIPTION_A07 = new HashSet<ADH_INSCRIPTION_A07>();
            this.ADH_PRESTATION_A10 = new HashSet<ADH_PRESTATION_A10>();
        }
    
        public int A35_ID { get; set; }
        public string A35_LIBELLE { get; set; }
        public Nullable<int> A35_ORDRE { get; set; }
        public Nullable<int> A35_ID_EVENT { get; set; }
        public Nullable<int> A35_ID_MANIF { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADH_INSCRIPTION_A07> ADH_INSCRIPTION_A07 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADH_PRESTATION_A10> ADH_PRESTATION_A10 { get; set; }
    }
}
