//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADH_TYPE_TARIF_A26
    {
        public int A26_ID { get; set; }
        public Nullable<int> A26_ID_PRESTA { get; set; }
        public Nullable<int> A26_ID_STATUT { get; set; }
        public Nullable<decimal> A26_DROIT_INSCRIPTION { get; set; }
        public Nullable<int> A26_AHRES_PCT { get; set; }
        public Nullable<decimal> A26_AHRES { get; set; }
        public Nullable<int> A26_TAUX_TVA { get; set; }
    }
}
