//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADH_TRANSPORT_PART_A78
    {
        public int A78_ID { get; set; }
        public long A78_ID_PART_A09 { get; set; }
        public Nullable<short> A78_MODE_ARR { get; set; }
        public Nullable<short> A78_MODE_DEP { get; set; }
        public string A78_PAYS_ARR { get; set; }
        public string A78_PAYS_DEP { get; set; }
        public string A78_VILLE_ARR_ARR { get; set; }
        public string A78_VILLE_ARR_DEP { get; set; }
        public string A78_VILLE_DEP_ARR { get; set; }
        public string A78_VILLE_DEP_DEP { get; set; }
        public string A78_AEROPORT_ARR_ARR { get; set; }
        public string A78_AEROPORT_ARR_DEP { get; set; }
        public string A78_AEROPORT_DEP_ARR { get; set; }
        public string A78_AEROPORT_DEP_DEP { get; set; }
        public string A78_GARE_ARR { get; set; }
        public string A78_GARE_DEP { get; set; }
        public string A78_COMPAGNIE { get; set; }
        public Nullable<System.DateTime> A78_DATE_ARR { get; set; }
        public Nullable<System.DateTime> A78_DATE_DEP { get; set; }
        public string A78_NUM_TRAIN_ARR { get; set; }
        public Nullable<short> A78_TRANSFERT { get; set; }
        public string A78_NOTE_ARR { get; set; }
        public Nullable<int> A78_NUMVOL_ARR { get; set; }
        public Nullable<int> A78_NUMVOL_DEP { get; set; }
        public string A78_CODE_COMP_ARR { get; set; }
        public string A78_CODE_COMP_DEP { get; set; }
        public string A78_NUM_TRAIN_DEP { get; set; }
        public string A78_NOTE_DEP { get; set; }
    }
}
