//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADH_TYPE_ACTION_A17
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ADH_TYPE_ACTION_A17()
        {
            this.ADH_ACTIONS_A01 = new HashSet<ADH_ACTIONS_A01>();
            this.ADH_PARTICIPANT_A09 = new HashSet<ADH_PARTICIPANT_A09>();
        }
    
        public int A17_ID { get; set; }
        public string A17_LIBELLE { get; set; }
        public Nullable<short> A17_ORDRE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADH_ACTIONS_A01> ADH_ACTIONS_A01 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADH_PARTICIPANT_A09> ADH_PARTICIPANT_A09 { get; set; }
    }
}
