//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADH_SOCIETE_A12
    {
        public int A12_ID { get; set; }
        public string A12_NOM_SOCIETE { get; set; }
        public string A12_TEXTE_ADRESSE_SOCIETE { get; set; }
        public string A12_CODE_POSTAL_SOCIETE { get; set; }
        public string A12_VILLE_SOCIETE { get; set; }
        public string A12_PAYS_SOCIETE { get; set; }
        public string A12_TELEPHONE_SOCIETE { get; set; }
        public string A12_FAX_SOCIETE { get; set; }
        public string A12_EMAIL_SOCIETE { get; set; }
        public Nullable<int> A12_UTILISATEUR { get; set; }
    }
}
