//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADH_TYPE_PRESTA_PARAM_A55
    {
        public int A55_ID { get; set; }
        public Nullable<int> A55_ID_A25 { get; set; }
        public Nullable<int> A55_ID_C43 { get; set; }
        public string A55_NOM_CHAMP { get; set; }
        public string A55_NOM_CTL { get; set; }
        public string A55_NOM_CTL_LIE { get; set; }
        public string A55_LIBELLE { get; set; }
        public string A55_VALUES_SEG { get; set; }
        public Nullable<short> A55_ORIGINAL { get; set; }
        public Nullable<short> A55_ORDRE { get; set; }
    }
}
