//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_POSITION_T02
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_POSITION_T02()
        {
            this.TBL_RESERVATION_POSITION_T05 = new HashSet<TBL_RESERVATION_POSITION_T05>();
        }
    
        public int T02_ID { get; set; }
        public string T02_LIBELLE { get; set; }
        public Nullable<int> T02_ID_LIEU_M07 { get; set; }
        public Nullable<int> T02_ID_TABLE_T01 { get; set; }
        public Nullable<short> T02_TYPE { get; set; }
        public Nullable<int> T02_TTOP { get; set; }
        public Nullable<int> T02_TLEFT { get; set; }
        public Nullable<int> T02_TWIDTH { get; set; }
        public Nullable<int> T02_THEIGHT { get; set; }
        public Nullable<short> T01_PLACES { get; set; }
        public Nullable<int> T02_ID_PLAN_T03 { get; set; }
        public Nullable<int> T02_ANGLE { get; set; }
        public Nullable<int> T02_ETAT_T09 { get; set; }
        public Nullable<int> T02_NUMERO_TABLE { get; set; }
        public Nullable<int> T02_ETAT { get; set; }
    
        public virtual TBL_ETAT_T09 TBL_ETAT_T09 { get; set; }
        public virtual TBL_PLAN_SALLE_T03 TBL_PLAN_SALLE_T03 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_RESERVATION_POSITION_T05> TBL_RESERVATION_POSITION_T05 { get; set; }
    }
}
