//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_RESERVATION_POSITION_T05
    {
        public int T05_ID { get; set; }
        public Nullable<int> T05_ID_T04 { get; set; }
        public Nullable<int> T05_ID_T02 { get; set; }
        public Nullable<int> T05_NBPAX { get; set; }
    
        public virtual TBL_POSITION_T02 TBL_POSITION_T02 { get; set; }
        public virtual TBL_RESERVATION_T04 TBL_RESERVATION_T04 { get; set; }
    }
}
