//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_LOG_MODIF_T08
    {
        public int T08_ID { get; set; }
        public Nullable<int> T08_ID_TBL { get; set; }
        public string T08_NOM_TBL { get; set; }
        public string T08_NOM_CHAMP { get; set; }
        public string T08_COMMENTAIRE { get; set; }
        public Nullable<int> T08_ID_UTILISATEUR { get; set; }
        public string T08_NOM_UTILISATEUR { get; set; }
        public Nullable<System.DateTime> T08_DATE_MODIF { get; set; }
    
        public virtual CFG_UTILISATEURS_C18 CFG_UTILISATEURS_C18 { get; set; }
    }
}
