//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_TYPE_RESA1_T10
    {
        public int T10_ID { get; set; }
        public string T10_LIBELLE { get; set; }
        public Nullable<int> T10_ORDRE { get; set; }
    }
}
