//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ETAT_T09
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_ETAT_T09()
        {
            this.TBL_POSITION_T02 = new HashSet<TBL_POSITION_T02>();
            this.TBL_RESERVATION_T04 = new HashSet<TBL_RESERVATION_T04>();
        }
    
        public int T09_ID { get; set; }
        public string T09_LIBELLE { get; set; }
        public Nullable<int> T09_ORDRE { get; set; }
        public Nullable<int> T09_COULEUR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_POSITION_T02> TBL_POSITION_T02 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_RESERVATION_T04> TBL_RESERVATION_T04 { get; set; }
    }
}
