//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_FORFAIT_I24
    {
        public int I24_ID { get; set; }
        public long I24_ID_MANIF_M14 { get; set; }
        public int I24_ID_PRESTA_A10 { get; set; }
        public string I24_LIBELLE { get; set; }
        public string I24_DESCRIPTION { get; set; }
        public Nullable<decimal> I24_MONTANT_HT { get; set; }
        public Nullable<decimal> I24_MONTANT_TTC { get; set; }
        public Nullable<int> I24_ID_TVA_F17 { get; set; }
        public Nullable<short> I24_CHOIX_EXCLUSIF { get; set; }
        public Nullable<short> I24_OBLIGATOIRE { get; set; }
        public Nullable<short> I24_INVISIBLE { get; set; }
        public Nullable<short> I24_TYPE_INV_AUTORISE { get; set; }
        public string I24_IDS_A13_STATUT { get; set; }
        public string I24_LIBELLE_EN { get; set; }
        public string I24_LIBELLE_ES { get; set; }
        public string I24_LIBELLE_AL { get; set; }
        public string I24_LIBELLE_IT { get; set; }
        public string I24_DESCRIPTION_EN { get; set; }
        public string I24_DESCRIPTION_ES { get; set; }
        public string I24_DESCRIPTION_AL { get; set; }
        public string I24_DESCRIPTION_IT { get; set; }
        public Nullable<int> I24_QUOTA { get; set; }
    
        public virtual MAN_MANIFESTATIONS_M14 MAN_MANIFESTATIONS_M14 { get; set; }
    }
}
