//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_COMMANDES_I32
    {
        public int I32_ID { get; set; }
        public Nullable<int> I32_ID_ADMIN_A48 { get; set; }
        public Nullable<long> I32_ID_COMMANDE_F04 { get; set; }
        public Nullable<int> I32_ID_TVA_F17 { get; set; }
        public Nullable<int> I32_STATUT { get; set; }
        public Nullable<System.DateTime> I32_DATE_CREATION { get; set; }
        public Nullable<System.DateTime> I32_DATE_MODIFICATION { get; set; }
        public Nullable<System.DateTime> I32_DATE_VALIDATION { get; set; }
        public Nullable<System.DateTime> I32_DATE_REGLEMENT { get; set; }
        public Nullable<int> I32_NB_INSCRITS { get; set; }
        public Nullable<int> I32_NB_PARTICIPANTS { get; set; }
        public Nullable<int> I32_NB_CONTACTS { get; set; }
        public Nullable<int> I32_NB_MAILS { get; set; }
        public Nullable<decimal> I32_MONANT_HT { get; set; }
        public Nullable<int> I32_NB_SMS { get; set; }
    }
}
