//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_FORMAT_PRESTA_I09
    {
        public int I09_ID { get; set; }
        public long I09_ID_MANIF_M14 { get; set; }
        public Nullable<short> I09_TAILLE_LIB { get; set; }
        public Nullable<short> I09_PRIX_VISIBLE { get; set; }
        public Nullable<short> I09_PLACES_DISPO_VISIBLE { get; set; }
        public Nullable<short> I09_PLACES_RESTANTES_VISIBLE { get; set; }
        public Nullable<short> I09_DESCRIPTION_VISIBLE { get; set; }
        public Nullable<short> I09_DESCRIPTION_HTML_VISIBLE { get; set; }
        public Nullable<short> I09_DATE_DEBUT_VISIBLE { get; set; }
        public Nullable<short> I09_DATE_FIN_VISIBLE { get; set; }
    
        public virtual MAN_MANIFESTATIONS_M14 MAN_MANIFESTATIONS_M14 { get; set; }
    }
}
