//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_CONFIG_HEBERGEMENT_I10
    {
        public int I10_ID { get; set; }
        public Nullable<long> I10_ID_MANIF_M14 { get; set; }
        public Nullable<short> I10_PRIX_MASQUE { get; set; }
        public Nullable<short> I10_PLACES_MASQUE { get; set; }
        public Nullable<short> I10_TRANSFERT_ACTIF { get; set; }
        public Nullable<short> I10_ACCOMPAGNE_PAR_VISIBLE { get; set; }
        public Nullable<short> I10_HEBERGEMENT_OBLIGATOIRE { get; set; }
        public Nullable<short> I10_NB_RESA_MAX { get; set; }
        public Nullable<short> I10_DESC_MASQUE { get; set; }
        public string I10_TEXTE_ETAPE { get; set; }
        public string I10_TEXTE_ETAPE_EN { get; set; }
        public string I10_TEXTE_ETAPE_ES { get; set; }
    
        public virtual MAN_MANIFESTATIONS_M14 MAN_MANIFESTATIONS_M14 { get; set; }
    }
}
