//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_TRANSFERT_I15
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INV_TRANSFERT_I15()
        {
            this.INV_NOTIFICATION_I28 = new HashSet<INV_NOTIFICATION_I28>();
        }
    
        public int I15_ID { get; set; }
        public long I15_ID_MANIF_M14 { get; set; }
        public Nullable<int> I15_ID_NAVETTE_I14 { get; set; }
        public Nullable<int> I15_ID_NUITEE_A76 { get; set; }
        public Nullable<short> I15_SENS { get; set; }
        public Nullable<System.DateTime> I15_DATE_DEPART { get; set; }
        public Nullable<System.DateTime> I15_DATE_ARRIVEE { get; set; }
        public string I15_NOTE { get; set; }
        public Nullable<long> I15_ID_PART_A09 { get; set; }
    
        public virtual ADH_NUIT_PART_HOT_A76 ADH_NUIT_PART_HOT_A76 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_NOTIFICATION_I28> INV_NOTIFICATION_I28 { get; set; }
        public virtual INV_TRANSFERT_NAVETTE_I14 INV_TRANSFERT_NAVETTE_I14 { get; set; }
        public virtual MAN_MANIFESTATIONS_M14 MAN_MANIFESTATIONS_M14 { get; set; }
    }
}
