//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_TRANSPORT_I39
    {
        public int I39_ID { get; set; }
        public long I39_ID_MANIF_M14 { get; set; }
        public Nullable<int> I39_ID_NAVETTE_I38 { get; set; }
        public string I39_LIBELLE_NAVETTE { get; set; }
        public Nullable<short> I39_SENS { get; set; }
        public Nullable<System.DateTime> I39_DATE_DEPART { get; set; }
        public Nullable<System.DateTime> I39_DATE_ARRIVEE { get; set; }
        public string I39_NOTE { get; set; }
        public Nullable<long> I39_ID_PART_A09 { get; set; }
        public Nullable<short> I39_NB_PLACE { get; set; }
    
        public virtual INV_TRANSPORT_NAVETTE_I38 INV_TRANSPORT_NAVETTE_I38 { get; set; }
        public virtual MAN_MANIFESTATIONS_M14 MAN_MANIFESTATIONS_M14 { get; set; }
    }
}
