//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_TYPE_COMBINAISONS_I03
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INV_TYPE_COMBINAISONS_I03()
        {
            this.INV_REGLES_CATEGORIES_I02 = new HashSet<INV_REGLES_CATEGORIES_I02>();
        }
    
        public int I03_ID { get; set; }
        public string I03_LIBELLE { get; set; }
        public string I03_DESCRIPTION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_REGLES_CATEGORIES_I02> INV_REGLES_CATEGORIES_I02 { get; set; }
    }
}
