//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_CONFIG_TRANSPORT_I40
    {
        public int I40_ID { get; set; }
        public long I40_ID_MANIF_M14 { get; set; }
        public Nullable<short> I40_DEMANDES_ONLY { get; set; }
        public Nullable<short> I40_OBLIGATOIRE { get; set; }
        public Nullable<short> I40_NOTE { get; set; }
        public Nullable<short> I40_VIA { get; set; }
        public Nullable<short> I40_QUOTA { get; set; }
        public Nullable<short> I40_GESTION_ACCOMP { get; set; }
    }
}
