//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_REC_CONF_I27
    {
        public int I27_ID { get; set; }
        public Nullable<long> I27_ID_MANIF_M14 { get; set; }
        public string I27_TEXTE { get; set; }
        public string I27_TEXTE_EN { get; set; }
        public string I27_TEXTE_AL { get; set; }
        public string I27_TEXTE_ES { get; set; }
        public string I27_TEXTE_IT { get; set; }
        public string I27_TEXT_SEL { get; set; }
        public string I27_TEXT_SEL_EN { get; set; }
        public string I27_TEXT_SEL_AL { get; set; }
        public string I27_TEXT_SEL_ES { get; set; }
        public string I27_TEXT_SEL_IT { get; set; }
        public Nullable<short> I27_MODE_PRES { get; set; }
        public Nullable<short> I27_WIDTH { get; set; }
        public Nullable<short> I27_HEIGHT { get; set; }
        public Nullable<short> I27_NOT_MODAL { get; set; }
        public Nullable<short> I27_DUREE_VERROUILLAGE { get; set; }
        public Nullable<short> I27_DUREE_OUVERTURE { get; set; }
        public Nullable<short> I27_DUREE_RESERVATION { get; set; }
        public Nullable<short> I27_DAYSTARTTIME { get; set; }
        public Nullable<short> I27_DAYENDTIME { get; set; }
    }
}
