//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_MOTS_CLES_AIDE_I06
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INV_MOTS_CLES_AIDE_I06()
        {
            this.INV_MOTS_CLES_PAR_PAGE_I07 = new HashSet<INV_MOTS_CLES_PAR_PAGE_I07>();
        }
    
        public int I06_ID { get; set; }
        public string I06_MOT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_MOTS_CLES_PAR_PAGE_I07> INV_MOTS_CLES_PAR_PAGE_I07 { get; set; }
    }
}
