//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_NOTIFICATION_I28
    {
        public long I28_ID { get; set; }
        public Nullable<int> I28_ID_ADMIN_A48 { get; set; }
        public Nullable<long> I28_ID_MANIF_M14 { get; set; }
        public string I28_DESCRIPTION { get; set; }
        public string I28_NOM_MODULE { get; set; }
        public string I28_TITRE { get; set; }
        public string I28_URL_NOTIF { get; set; }
        public Nullable<short> I28_IS_READ { get; set; }
        public Nullable<System.DateTime> I28_KEEP_UNTIL { get; set; }
        public Nullable<int> I28_ID_PART_A09 { get; set; }
        public Nullable<int> I28_ID_MAIL_U14 { get; set; }
        public Nullable<int> I28_ID_TRANSFERT_I15 { get; set; }
        public Nullable<int> I28_ID_NUITEE_A76 { get; set; }
        public System.DateTime I28_DATE_CREATION { get; set; }
        public Nullable<int> I28_ID_PRESTA_A07 { get; set; }
        public Nullable<short> I28_TOP_NEW_NOTIFICATION { get; set; }
    
        public virtual ADH_EPARTICIPANT_ADMIN_A48 ADH_EPARTICIPANT_ADMIN_A48 { get; set; }
        public virtual ADH_INSCRIPTION_A07 ADH_INSCRIPTION_A07 { get; set; }
        public virtual ADH_NUIT_PART_HOT_A76 ADH_NUIT_PART_HOT_A76 { get; set; }
        public virtual ADH_PARTICIPANT_A09 ADH_PARTICIPANT_A09 { get; set; }
        public virtual INV_TRANSFERT_I15 INV_TRANSFERT_I15 { get; set; }
        public virtual MAN_MANIFESTATIONS_M14 MAN_MANIFESTATIONS_M14 { get; set; }
        public virtual USR_MESSAGE_U14 USR_MESSAGE_U14 { get; set; }
    }
}
