//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_TRANSPORT_NAVETTE_I38
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INV_TRANSPORT_NAVETTE_I38()
        {
            this.INV_TRANSPORT_I39 = new HashSet<INV_TRANSPORT_I39>();
        }
    
        public int I38_ID { get; set; }
        public long I38_ID_MANIF_M14 { get; set; }
        public Nullable<int> I38_ID_LIEU_DEPART_I37 { get; set; }
        public Nullable<int> I38_ID_LIEU_ARRIVEE_I37 { get; set; }
        public string I38_LIBELLE { get; set; }
        public Nullable<System.DateTime> I38_DATE_DEPART { get; set; }
        public Nullable<System.DateTime> I38_DATE_ARRIVEE { get; set; }
        public Nullable<short> I38_SENS { get; set; }
        public Nullable<decimal> I38_PRIX_HT { get; set; }
        public Nullable<int> I38_ID_TVA_F17 { get; set; }
        public Nullable<int> I38_NB_PLACES { get; set; }
        public string I38_COMPAGNIE { get; set; }
        public string I38_REFERENCE { get; set; }
        public Nullable<short> I38_MODE { get; set; }
        public Nullable<int> I38_QUOTA { get; set; }
        public Nullable<decimal> I38_PRIX_HT_PERS_SUPPL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_TRANSPORT_I39> INV_TRANSPORT_I39 { get; set; }
        public virtual INV_TRANSPORT_LIEU_I37 INV_TRANSPORT_LIEU_I37 { get; set; }
        public virtual INV_TRANSPORT_LIEU_I37 INV_TRANSPORT_LIEU_I371 { get; set; }
    }
}
