//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_DECOMPTE_SMS_I41
    {
        public int I41_ID { get; set; }
        public Nullable<int> I41_ID_ADMIN_A48 { get; set; }
        public Nullable<int> I41_ID_MAILING_U15 { get; set; }
        public Nullable<int> I41_NB_SMS { get; set; }
        public Nullable<System.DateTime> I41_DATE_DECOMPTE { get; set; }
    }
}
