//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_TRANSPORT_LIEU_I37
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INV_TRANSPORT_LIEU_I37()
        {
            this.INV_TRANSPORT_NAVETTE_I38 = new HashSet<INV_TRANSPORT_NAVETTE_I38>();
            this.INV_TRANSPORT_NAVETTE_I381 = new HashSet<INV_TRANSPORT_NAVETTE_I38>();
        }
    
        public int I37_ID { get; set; }
        public long I37_ID_MANIF_M14 { get; set; }
        public string I37_LIBELLE { get; set; }
        public Nullable<short> I37_SENS { get; set; }
        public Nullable<short> I37_ARRIVEE_DEPART { get; set; }
        public Nullable<short> I37_PROVENANCE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_TRANSPORT_NAVETTE_I38> INV_TRANSPORT_NAVETTE_I38 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_TRANSPORT_NAVETTE_I38> INV_TRANSPORT_NAVETTE_I381 { get; set; }
    }
}
