//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_COL_GRDINVITE_I01
    {
        public int I01_ID { get; set; }
        public Nullable<long> I01_ID_MANIF_M14 { get; set; }
        public Nullable<long> I01_ID_ADMIN_A48 { get; set; }
        public Nullable<int> I01_ORDRE { get; set; }
        public Nullable<short> I01_TYPEMAPPING { get; set; }
        public Nullable<short> I01_VISIBLE { get; set; }
        public string I01_NOM_TBL { get; set; }
        public string I01_NOM_COL { get; set; }
        public string I01_FILTRE { get; set; }
        public string I01_FORMAT { get; set; }
        public string I01_TYPE { get; set; }
        public string I01_SPECIFICSQL { get; set; }
        public string I01_FOREIGNKEY_FIELD_NAME { get; set; }
        public Nullable<short> I01_FOR_XLS_EXPORT { get; set; }
        public Nullable<int> I01_ID_CHAMP_DYNAMIQUE_C54 { get; set; }
        public string I01_FIELD_TYPE { get; set; }
        public string I01_LIST_SQL { get; set; }
        public Nullable<int> I01_ID_LIB { get; set; }
        public string I01_CPL_LIB { get; set; }
        public Nullable<short> I01_CONTROLE { get; set; }
    
        public virtual CFG_CHAMP_DYNAMIQUE_C54 CFG_CHAMP_DYNAMIQUE_C54 { get; set; }
    }
}
