//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_PRODUIT_CATEG_I35
    {
        public int I35_ID { get; set; }
        public Nullable<int> I35_ID_PRODUIT_I34 { get; set; }
        public Nullable<int> I35_ID_STATUT_A13 { get; set; }
        public Nullable<decimal> I35_MONTANT_ACHAT { get; set; }
        public Nullable<int> I35_ID_TVA_ACHAT_F17 { get; set; }
        public Nullable<decimal> I35_MONTANT_VENTE { get; set; }
        public Nullable<int> I35_ID_TVA_VENTE_F17 { get; set; }
    }
}
