//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_REC_PRESTA_I23
    {
        public int I23_ID { get; set; }
        public Nullable<int> I23_ID_REC_I22 { get; set; }
        public Nullable<int> I23_ID_PRESTA_A10 { get; set; }
        public Nullable<int> I23_QUOTA { get; set; }
    
        public virtual INV_REC_I22 INV_REC_I22 { get; set; }
    }
}
