//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_APPOINTMENT_CONFIG_I46
    {
        public int I46_ID { get; set; }
        public int I46_ID_MANIF_M14 { get; set; }
        public int I46_ID_ADMIN_A48 { get; set; }
        public string I46_LIBELLE { get; set; }
        public string I46_SKIN { get; set; }
        public Nullable<short> I46_SELECTEDVIEW { get; set; }
    }
}
