//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_CONFIG_EVENT_I43
    {
        public int I43_ID { get; set; }
        public Nullable<int> I43_ID_ADMIN_A48 { get; set; }
        public string I43_CHAMPS_LIBRES { get; set; }
        public Nullable<short> I43_TYPES_VISIBLE { get; set; }
    }
}
