//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_TRANSFERT_NAVETTE_I14
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INV_TRANSFERT_NAVETTE_I14()
        {
            this.INV_TRANSFERT_I15 = new HashSet<INV_TRANSFERT_I15>();
        }
    
        public int I14_ID { get; set; }
        public long I14_ID_MANIF_M14 { get; set; }
        public Nullable<int> I14_ID_LIEU_DEPART_I13 { get; set; }
        public Nullable<int> I14_ID_LIEU_ARRIVEE_I13 { get; set; }
        public string I14_LIBELLE { get; set; }
        public Nullable<System.DateTime> I14_DATE_DEPART { get; set; }
        public Nullable<System.DateTime> I14_DATE_ARRIVEE { get; set; }
        public Nullable<short> I14_SENS { get; set; }
        public Nullable<decimal> I14_PRIX_HT { get; set; }
        public Nullable<int> I14_ID_TVA_F17 { get; set; }
        public Nullable<int> I14_NB_PLACES { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_TRANSFERT_I15> INV_TRANSFERT_I15 { get; set; }
        public virtual INV_TRANSFERT_LIEU_I13 INV_TRANSFERT_LIEU_I13 { get; set; }
        public virtual INV_TRANSFERT_LIEU_I13 INV_TRANSFERT_LIEU_I131 { get; set; }
    }
}
