//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_COL_GRDFIN_I49
    {
        public int I49_ID { get; set; }
        public Nullable<long> I49_ID_ADMIN_A48 { get; set; }
        public Nullable<int> I49_ORDRE { get; set; }
        public Nullable<short> I49_TYPEMAPPING { get; set; }
        public Nullable<short> I49_VISIBLE { get; set; }
        public string I49_NOM_TBL { get; set; }
        public string I49_NOM_COL { get; set; }
        public string I49_FILTRE { get; set; }
        public string I49_FORMAT { get; set; }
        public string I49_TYPE { get; set; }
        public string I49_SPECIFICSQL { get; set; }
        public string I49_FOREIGNKEY_FIELD_NAME { get; set; }
        public Nullable<short> I49_FOR_XLS_EXPORT { get; set; }
        public Nullable<int> I49_ID_LIB { get; set; }
        public string I49_CPL_LIB { get; set; }
    }
}
