//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_CHAMPS_PRIORISES_I29
    {
        public int I29_ID { get; set; }
        public Nullable<int> I29_ID_ADMIN_A48 { get; set; }
        public Nullable<long> I29_ID_MANIF_M14 { get; set; }
        public string I29_NOM_TABLE { get; set; }
        public string I29_CHAMP { get; set; }
        public Nullable<short> I29_PRIORITE { get; set; }
        public Nullable<short> I29_ETAT { get; set; }
        public string I29_INTITULE { get; set; }
        public string I29_NOM_TABLE_DEST { get; set; }
        public string I29_NOM_CHAMP_DEST { get; set; }
        public Nullable<short> I29_TYPE_CHAMP { get; set; }
    
        public virtual ADH_EPARTICIPANT_ADMIN_A48 ADH_EPARTICIPANT_ADMIN_A48 { get; set; }
        public virtual MAN_MANIFESTATIONS_M14 MAN_MANIFESTATIONS_M14 { get; set; }
    }
}
