//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAgoraV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_APPOINTMENT_TYPE_I45
    {
        public int I45_ID { get; set; }
        public int I45_ID_MANIF_M14 { get; set; }
        public int I45_ID_ADMIN_A48 { get; set; }
        public string I45_LIBELLE { get; set; }
    }
}
